'use client';

import React, { useState, useEffect } from 'react';
import Papa from 'papaparse';
import { CopyButton } from '@/components/shared/CopyButton';
import { Database, Upload, Download, Sparkles, AlertCircle } from 'lucide-react';

function escapeSqlValue(val: string, dialect: string): string {
  const trimmed = val.trim();
  if (trimmed === '' || trimmed.toUpperCase() === 'NULL') {
    return 'NULL';
  }
  if (trimmed.toUpperCase() === 'TRUE') return 'TRUE';
  if (trimmed.toUpperCase() === 'FALSE') return 'FALSE';
  if (!isNaN(Number(trimmed)) && !trimmed.startsWith('0') && trimmed.length < 16) {
    return trimmed;
  }
  // Escape single quotes
  const escaped = trimmed.replace(/'/g, "''");
  return `'${escaped}'`;
}

function escapeIdentifier(id: string, dialect: string): string {
  const clean = id.trim();
  if (dialect === 'mysql') return `\`${clean}\``;
  if (dialect === 'mssql') return `[${clean}]`;
  return `"${clean}"`; // Postgres, SQLite
}

const DEFAULT_CSV = `id,name,email,age,is_active,role
1,Alice Johnson,alice@example.com,28,true,admin
2,Bob Smith,bob@example.com,34,false,user
3,Charlie Brown,charlie@example.com,22,true,developer
4,Diana Prince,diana@example.com,31,true,lead`;

export function CsvToSqlConverter() {
  const [csvText, setCsvText] = useState(DEFAULT_CSV);
  const [tableName, setTableName] = useState('users');
  const [dialect, setDialect] = useState<'postgres' | 'mysql' | 'sqlite' | 'mssql'>('postgres');
  const [batchSize, setBatchSize] = useState(50);
  const [sqlOutput, setSqlOutput] = useState('');
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    try {
      if (!csvText.trim()) {
        setSqlOutput('');
        setError(null);
        return;
      }

      const parsed = Papa.parse(csvText.trim(), {
        header: true,
        skipEmptyLines: true,
      });

      if (parsed.errors.length > 0 && parsed.data.length === 0) {
        setError(parsed.errors[0].message);
        setSqlOutput('');
        return;
      }

      setError(null);
      const rows = parsed.data as Record<string, string>[];
      if (rows.length === 0) {
        setSqlOutput('-- No rows found in CSV');
        return;
      }

      const headers = Object.keys(rows[0]);
      const table = escapeIdentifier(tableName || 'table_name', dialect);
      const columnsList = headers.map((h) => escapeIdentifier(h, dialect)).join(', ');

      const statements: string[] = [];
      statements.push(`-- Generated by DevTransform CSV to SQL Converter`);
      statements.push(`-- Table: ${tableName} (${rows.length} rows, Dialect: ${dialect.toUpperCase()})\n`);

      for (let i = 0; i < rows.length; i += batchSize) {
        const chunk = rows.slice(i, i + batchSize);
        const valuesList = chunk.map((row) => {
          const vals = headers.map((col) => escapeSqlValue(row[col] ?? '', dialect));
          return `  (${vals.join(', ')})`;
        });

        statements.push(
          `INSERT INTO ${table} (${columnsList})\nVALUES\n${valuesList.join(',\n')};`
        );
      }

      setSqlOutput(statements.join('\n\n'));
    } catch (err: any) {
      setError(err.message || 'Failed to parse CSV');
      setSqlOutput('');
    }
  }, [csvText, tableName, dialect, batchSize]);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => {
      const text = event.target?.result as string;
      setCsvText(text);
      const cleanName = file.name.replace(/\.[^/.]+$/, '').replace(/[^a-zA-Z0-9_]/g, '_');
      if (cleanName) setTableName(cleanName);
    };
    reader.readAsText(file);
  };

  const downloadSql = () => {
    const blob = new Blob([sqlOutput], { type: 'text/sql;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${tableName || 'export'}.sql`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Config Bar */}
      <div className="p-4 rounded-2xl bg-zinc-900 border border-zinc-800 flex flex-wrap items-center justify-between gap-3 shadow-sm">
        <div className="flex items-center space-x-3">
          <Database className="w-5 h-5 text-brand-emerald" />
          <div className="flex items-center space-x-2">
            <span className="text-xs font-mono text-zinc-400">Table Name:</span>
            <input
              type="text"
              value={tableName}
              onChange={(e) => setTableName(e.target.value)}
              className="px-3 py-1 bg-black/50 border border-zinc-700 rounded-xl text-white font-mono text-xs focus:border-brand-emerald focus:outline-none"
              placeholder="users"
            />
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <span className="text-xs font-mono text-zinc-500">Dialect:</span>
          {(['postgres', 'mysql', 'sqlite', 'mssql'] as const).map((d) => (
            <button
              key={d}
              type="button"
              onClick={() => setDialect(d)}
              className={`px-2.5 py-1 rounded-lg text-xs font-mono transition-colors ${
                dialect === d
                  ? 'bg-brand-emerald text-black font-bold'
                  : 'bg-zinc-800 text-zinc-400 hover:text-white'
              }`}
            >
              {d.toUpperCase()}
            </button>
          ))}
        </div>
      </div>

      {/* Editors */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* CSV Input */}
        <div className="p-4 rounded-2xl bg-zinc-900 border border-zinc-800 space-y-3 flex flex-col">
          <div className="flex items-center justify-between">
            <span className="text-xs font-mono font-bold text-zinc-400 uppercase tracking-wider">
              Input CSV Data
            </span>
            <label className="flex items-center space-x-1.5 text-xs font-mono text-brand-emerald hover:underline cursor-pointer">
              <Upload className="w-3.5 h-3.5" />
              <span>Upload .csv</span>
              <input type="file" accept=".csv,text/csv" onChange={handleFileUpload} className="hidden" />
            </label>
          </div>
          <textarea
            value={csvText}
            onChange={(e) => setCsvText(e.target.value)}
            rows={15}
            placeholder="Paste CSV rows with headers here..."
            className="w-full flex-1 p-3 bg-black/60 border border-zinc-800 rounded-xl text-zinc-200 font-mono text-xs focus:border-brand-emerald focus:outline-none resize-none leading-relaxed"
          />
          {error && (
            <div className="p-2.5 rounded-lg bg-rose-950/40 border border-rose-800 text-rose-300 text-xs flex items-center gap-2">
              <AlertCircle className="w-3.5 h-3.5 flex-shrink-0" />
              <span>{error}</span>
            </div>
          )}
        </div>

        {/* SQL Output */}
        <div className="p-4 rounded-2xl bg-zinc-900 border border-zinc-800 space-y-3 flex flex-col">
          <div className="flex items-center justify-between">
            <span className="text-xs font-mono font-bold text-brand-emerald uppercase tracking-wider flex items-center gap-1.5">
              <Sparkles className="w-3.5 h-3.5" />
              Generated SQL Statements
            </span>
            <div className="flex items-center space-x-2">
              {sqlOutput && (
                <button
                  type="button"
                  onClick={downloadSql}
                  className="flex items-center space-x-1 px-2.5 py-1 bg-zinc-800 hover:bg-zinc-700 text-zinc-300 rounded-lg text-xs font-mono transition-colors"
                >
                  <Download className="w-3 h-3" />
                  <span>.sql</span>
                </button>
              )}
              {sqlOutput && <CopyButton text={sqlOutput} />}
            </div>
          </div>
          <textarea
            readOnly
            value={sqlOutput}
            rows={15}
            placeholder="SQL INSERT statements will appear here..."
            className="w-full flex-1 p-3 bg-black/60 border border-zinc-800 rounded-xl text-emerald-400 font-mono text-xs focus:outline-none resize-none leading-relaxed select-all"
          />
        </div>
      </div>
    </div>
  );
}
