'use client';

import React, { useState, useMemo } from 'react';
import {
  Shield,
  Copy,
  Check,
  Download,
  Plus,
  Trash2,
  Server,
  Zap,
  Lock,
  Globe,
  Sliders,
  Sparkles,
  ShieldCheck,
} from 'lucide-react';

interface RedirectRule {
  id: string;
  from: string;
  to: string;
  type: '301' | '302';
}

export function HtaccessRedirectGeneratorStudio() {
  const [forceHttps, setForceHttps] = useState<boolean>(true);
  const [domainRedirect, setDomainRedirect] = useState<'none' | 'non-www' | 'www'>('non-www');
  const [customDomain, setCustomDomain] = useState<string>('example.com');
  const [disableDirectoryListing, setDisableDirectoryListing] = useState<boolean>(true);
  const [blockSensitiveFiles, setBlockSensitiveFiles] = useState<boolean>(true);
  const [enableGzip, setEnableGzip] = useState<boolean>(true);
  const [enableSecurityHeaders, setEnableSecurityHeaders] = useState<boolean>(true);
  const [spaFallback, setSpaFallback] = useState<boolean>(false);
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  const [redirects, setRedirects] = useState<RedirectRule[]>([
    { id: '1', from: '/old-about-page', to: '/about', type: '301' },
    { id: '2', from: '/legacy-blog/(.*)', to: '/blog/$1', type: '301' },
  ]);

  const addRedirect = () => {
    setRedirects((prev) => [
      ...prev,
      {
        id: Math.random().toString(36).substring(2, 9),
        from: '',
        to: '',
        type: '301',
      },
    ]);
  };

  const updateRedirect = (id: string, field: keyof RedirectRule, val: string) => {
    setRedirects((prev) =>
      prev.map((r) => (r.id === id ? { ...r, [field]: val } : r))
    );
  };

  const removeRedirect = (id: string) => {
    setRedirects((prev) => prev.filter((r) => r.id !== id));
  };

  // Construct htaccess content
  const htaccessContent = useMemo(() => {
    const lines: string[] = [
      '# ----------------------------------------------------------------------',
      '# Apache .htaccess configuration generated by DevTransform Studio',
      '# Privacy-First & High-Performance Security Rules',
      '# ----------------------------------------------------------------------',
      '',
      '<IfModule mod_rewrite.c>',
      '  RewriteEngine On',
      '  RewriteBase /',
    ];

    // Force HTTPS
    if (forceHttps) {
      lines.push('');
      lines.push('  # Force HTTPS protocol');
      lines.push('  RewriteCond %{HTTPS} off [OR]');
      lines.push('  RewriteCond %{HTTP:X-Forwarded-Proto} !https');
      lines.push('  RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]');
    }

    // Force WWW or Non-WWW
    if (domainRedirect === 'non-www') {
      lines.push('');
      lines.push('  # Redirect www to non-www');
      lines.push(`  RewriteCond %{HTTP_HOST} ^www\\.(.*)$ [NC]`);
      lines.push(`  RewriteRule ^(.*)$ https://%1/$1 [R=301,L]`);
    } else if (domainRedirect === 'www') {
      lines.push('');
      lines.push('  # Redirect non-www to www');
      lines.push(`  RewriteCond %{HTTP_HOST} !^www\\. [NC]`);
      lines.push(`  RewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [R=301,L]`);
    }

    // Custom Path Redirects
    const validRedirects = redirects.filter((r) => r.from.trim() && r.to.trim());
    if (validRedirects.length > 0) {
      lines.push('');
      lines.push('  # Custom URL Redirects');
      validRedirects.forEach((r) => {
        const fromPath = r.from.startsWith('/') ? r.from.slice(1) : r.from;
        lines.push(`  RewriteRule ^${fromPath}$ ${r.to} [R=${r.type},L]`);
      });
    }

    // SPA Single Page Application fallback
    if (spaFallback) {
      lines.push('');
      lines.push('  # HTML5 Single Page App (SPA) rewrite fallback');
      lines.push('  RewriteCond %{REQUEST_FILENAME} !-f');
      lines.push('  RewriteCond %{REQUEST_FILENAME} !-d');
      lines.push('  RewriteRule . /index.html [L]');
    }

    lines.push('</IfModule>');

    // Directory Listing
    if (disableDirectoryListing) {
      lines.push('');
      lines.push('# Disable Directory Browsing');
      lines.push('Options -Indexes');
    }

    // Block sensitive files
    if (blockSensitiveFiles) {
      lines.push('');
      lines.push('# Block access to hidden and sensitive configuration files');
      lines.push('<FilesMatch "^(\\.(env|git|htaccess|htpasswd)|composer\\.(json|lock)|package\\.json)$">');
      lines.push('  <IfModule mod_authz_core.c>');
      lines.push('    Require all denied');
      lines.push('  </IfModule>');
      lines.push('  <IfModule !mod_authz_core.c>');
      lines.push('    Order deny,allow');
      lines.push('    Deny from all');
      lines.push('  </IfModule>');
      lines.push('</FilesMatch>');
    }

    // Security Headers
    if (enableSecurityHeaders) {
      lines.push('');
      lines.push('# Essential Security HTTP Headers');
      lines.push('<IfModule mod_headers.c>');
      lines.push('  Header always set X-Content-Type-Options "nosniff"');
      lines.push('  Header always set X-Frame-Options "SAMEORIGIN"');
      lines.push('  Header always set X-XSS-Protection "1; mode=block"');
      lines.push('  Header always set Referrer-Policy "strict-origin-when-cross-origin"');
      lines.push('</IfModule>');
    }

    // Gzip Compression
    if (enableGzip) {
      lines.push('');
      lines.push('# Enable Gzip / Brotli compression for text assets');
      lines.push('<IfModule mod_deflate.c>');
      lines.push('  AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript');
      lines.push('  AddOutputFilterByType DEFLATE application/javascript application/json application/xml image/svg+xml');
      lines.push('</IfModule>');
    }

    return lines.join('\n');
  }, [
    forceHttps,
    domainRedirect,
    disableDirectoryListing,
    blockSensitiveFiles,
    enableGzip,
    enableSecurityHeaders,
    spaFallback,
    redirects,
  ]);

  const copyToClipboard = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const downloadHtaccess = () => {
    const blob = new Blob([htaccessContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = '.htaccess';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Header Info */}
      <div className="rounded-xl border border-slate-200 dark:border-slate-800 bg-gradient-to-r from-orange-500/10 via-amber-500/10 to-yellow-500/10 p-5">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <Server className="w-5 h-5 text-orange-500" />
              Apache .htaccess Redirect & Security Rules Studio
            </h2>
            <p className="text-sm text-slate-600 dark:text-slate-400 mt-1">
              Generate battle-tested Apache rewrite directives: Force HTTPS, www/non-www redirects, 301 SEO redirects, security headers, and Gzip compression.
            </p>
          </div>
          <div className="flex items-center gap-2 text-xs font-medium text-emerald-600 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-950/40 px-3 py-1.5 rounded-full border border-emerald-200 dark:border-emerald-800">
            <ShieldCheck className="w-4 h-4" />
            100% Client-Side Privacy
          </div>
        </div>
      </div>

      {/* Main Settings Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left Column: Toggles & Redirects */}
        <div className="space-y-4">
          {/* Canonical & Protocol Controls */}
          <div className="p-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 space-y-3 shadow-sm">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 flex items-center gap-1.5">
              <Globe className="w-3.5 h-3.5 text-blue-500" />
              SSL & Domain Canonicalization
            </h3>

            <label className="flex items-center justify-between cursor-pointer p-2 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800/50">
              <div>
                <span className="text-sm font-semibold text-slate-800 dark:text-slate-200 block">
                  Force HTTPS (SSL)
                </span>
                <span className="text-xs text-slate-500">
                  Redirects all insecure HTTP requests to HTTPS
                </span>
              </div>
              <input
                type="checkbox"
                checked={forceHttps}
                onChange={(e) => setForceHttps(e.target.checked)}
                className="w-4 h-4 rounded text-orange-600 focus:ring-orange-500"
              />
            </label>

            <div className="border-t border-slate-100 dark:border-slate-800 pt-3">
              <label className="text-sm font-semibold text-slate-800 dark:text-slate-200 block mb-1">
                Domain Redirection (WWW vs Non-WWW)
              </label>
              <div className="grid grid-cols-3 gap-2">
                {(['none', 'non-www', 'www'] as const).map((mode) => (
                  <button
                    key={mode}
                    onClick={() => setDomainRedirect(mode)}
                    className={`px-3 py-1.5 text-xs font-semibold rounded-lg border transition-colors ${
                      domainRedirect === mode
                        ? 'bg-orange-50 dark:bg-orange-950/40 border-orange-500 text-orange-600 dark:text-orange-400'
                        : 'border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400 hover:border-slate-300'
                    }`}
                  >
                    {mode === 'none' ? 'No change' : mode === 'non-www' ? 'Force Non-WWW' : 'Force WWW'}
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Security & Performance Controls */}
          <div className="p-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 space-y-2.5 shadow-sm">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 flex items-center gap-1.5">
              <Lock className="w-3.5 h-3.5 text-emerald-500" />
              Security & Optimization
            </h3>

            <label className="flex items-center justify-between cursor-pointer p-2 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800/50">
              <span className="text-sm text-slate-800 dark:text-slate-200 font-medium">
                Disable Directory Browsing (<code className="text-xs font-mono">Options -Indexes</code>)
              </span>
              <input
                type="checkbox"
                checked={disableDirectoryListing}
                onChange={(e) => setDisableDirectoryListing(e.target.checked)}
                className="w-4 h-4 rounded text-orange-600 focus:ring-orange-500"
              />
            </label>

            <label className="flex items-center justify-between cursor-pointer p-2 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800/50">
              <span className="text-sm text-slate-800 dark:text-slate-200 font-medium">
                Block Sensitive Files (.env, .git, package.json)
              </span>
              <input
                type="checkbox"
                checked={blockSensitiveFiles}
                onChange={(e) => setBlockSensitiveFiles(e.target.checked)}
                className="w-4 h-4 rounded text-orange-600 focus:ring-orange-500"
              />
            </label>

            <label className="flex items-center justify-between cursor-pointer p-2 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800/50">
              <span className="text-sm text-slate-800 dark:text-slate-200 font-medium">
                Add Security Headers (nosniff, SAMEORIGIN, XSS)
              </span>
              <input
                type="checkbox"
                checked={enableSecurityHeaders}
                onChange={(e) => setEnableSecurityHeaders(e.target.checked)}
                className="w-4 h-4 rounded text-orange-600 focus:ring-orange-500"
              />
            </label>

            <label className="flex items-center justify-between cursor-pointer p-2 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800/50">
              <span className="text-sm text-slate-800 dark:text-slate-200 font-medium">
                Enable Gzip / Deflate Compression
              </span>
              <input
                type="checkbox"
                checked={enableGzip}
                onChange={(e) => setEnableGzip(e.target.checked)}
                className="w-4 h-4 rounded text-orange-600 focus:ring-orange-500"
              />
            </label>

            <label className="flex items-center justify-between cursor-pointer p-2 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800/50">
              <span className="text-sm text-slate-800 dark:text-slate-200 font-medium">
                Single Page App (SPA) Fallback Rewrite
              </span>
              <input
                type="checkbox"
                checked={spaFallback}
                onChange={(e) => setSpaFallback(e.target.checked)}
                className="w-4 h-4 rounded text-orange-600 focus:ring-orange-500"
              />
            </label>
          </div>

          {/* Custom 301 Redirect Rules */}
          <div className="p-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 space-y-3 shadow-sm">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 flex items-center gap-1.5">
                <Sliders className="w-3.5 h-3.5 text-orange-500" />
                Custom 301 / 302 Path Redirects
              </h3>
              <button
                onClick={addRedirect}
                className="inline-flex items-center gap-1 px-2.5 py-1 text-xs font-semibold rounded-lg bg-orange-50 hover:bg-orange-100 dark:bg-orange-950/40 text-orange-600 dark:text-orange-400"
              >
                <Plus className="w-3 h-3" />
                Add Row
              </button>
            </div>

            <div className="space-y-2">
              {redirects.map((rule) => (
                <div key={rule.id} className="flex items-center gap-2">
                  <select
                    value={rule.type}
                    onChange={(e) => updateRedirect(rule.id, 'type', e.target.value)}
                    className="text-xs font-semibold px-2 py-1.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-200"
                  >
                    <option value="301">301</option>
                    <option value="302">302</option>
                  </select>
                  <input
                    type="text"
                    value={rule.from}
                    onChange={(e) => updateRedirect(rule.id, 'from', e.target.value)}
                    placeholder="/old-path"
                    className="flex-1 font-mono text-xs px-2.5 py-1.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-200"
                  />
                  <span className="text-xs text-slate-400">&rarr;</span>
                  <input
                    type="text"
                    value={rule.to}
                    onChange={(e) => updateRedirect(rule.id, 'to', e.target.value)}
                    placeholder="/new-destination"
                    className="flex-1 font-mono text-xs px-2.5 py-1.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-200"
                  />
                  <button
                    onClick={() => removeRedirect(rule.id)}
                    className="p-1 text-slate-400 hover:text-red-500"
                    title="Remove redirect"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right Column: Generated .htaccess Output */}
        <div className="space-y-2 flex flex-col">
          <div className="flex items-center justify-between">
            <label className="text-sm font-semibold text-slate-700 dark:text-slate-300 flex items-center gap-1.5">
              <Server className="w-4 h-4 text-orange-500" />
              Generated .htaccess File:
            </label>
            <div className="flex items-center gap-2">
              <button
                onClick={() => copyToClipboard(htaccessContent, 'htaccess')}
                className="inline-flex items-center gap-1 px-3 py-1 rounded-lg bg-orange-600 hover:bg-orange-700 text-white text-xs font-semibold transition-colors shadow-sm"
              >
                {copiedKey === 'htaccess' ? (
                  <>
                    <Check className="w-3.5 h-3.5" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    Copy .htaccess
                  </>
                )}
              </button>
              <button
                onClick={downloadHtaccess}
                className="inline-flex items-center gap-1 px-3 py-1 rounded-lg bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 text-xs font-semibold transition-colors shadow-sm"
              >
                <Download className="w-3.5 h-3.5" />
                Download
              </button>
            </div>
          </div>

          <div className="flex-1 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-950 p-4 font-mono text-xs text-orange-300 overflow-x-auto min-h-[460px]">
            <pre>
              <code>{htaccessContent}</code>
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}
