export interface CronScheduleInfo {
  slug: string;
  expression: string;
  title: string;
  titleTr: string;
  description: string;
  descriptionTr: string;
  minute: string;
  hour: string;
  dayOfMonth: string;
  month: string;
  dayOfWeek: string;
  category: 'frequent' | 'hourly' | 'daily' | 'weekly' | 'monthly';
}

export const CRON_SCHEDULES: CronScheduleInfo[] = [
  // ----------------------------------------------------
  // FREQUENT (Minutes)
  // ----------------------------------------------------
  {
    slug: 'every-minute',
    expression: '* * * * *',
    title: 'Every Minute (* * * * *)',
    titleTr: 'Her Dakika Başı',
    description: 'Executes every single minute of every hour, every day.',
    descriptionTr: 'Günün her saatinde, her dakika başı sürekli olarak çalışır.',
    minute: 'Every minute (*)',
    hour: 'Every hour (*)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'frequent',
  },
  {
    slug: 'every-2-minutes',
    expression: '*/2 * * * *',
    title: 'Every 2 Minutes (*/2 * * * *)',
    titleTr: 'Her 2 Dakikada Bir',
    description: 'Executes every 2nd minute (at minutes 0, 2, 4, 6, 8, etc.).',
    descriptionTr: 'Her 2 dakikada bir düzenli aralıklarla çalışır.',
    minute: 'Every 2nd minute (*/2)',
    hour: 'Every hour (*)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'frequent',
  },
  {
    slug: 'every-3-minutes',
    expression: '*/3 * * * *',
    title: 'Every 3 Minutes (*/3 * * * *)',
    titleTr: 'Her 3 Dakikada Bir',
    description: 'Executes every 3rd minute (0, 3, 6, 9, 12, etc.).',
    descriptionTr: 'Her 3 dakikada bir çalışır.',
    minute: 'Every 3rd minute (*/3)',
    hour: 'Every hour (*)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'frequent',
  },
  {
    slug: 'every-5-minutes',
    expression: '*/5 * * * *',
    title: 'Every 5 Minutes (*/5 * * * *)',
    titleTr: 'Her 5 Dakikada Bir',
    description: 'Executes every 5th minute (0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55).',
    descriptionTr: 'Her 5 dakikada bir düzenli aralıklarla çalışır.',
    minute: 'Every 5th minute (*/5)',
    hour: 'Every hour (*)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'frequent',
  },
  {
    slug: 'every-10-minutes',
    expression: '*/10 * * * *',
    title: 'Every 10 Minutes (*/10 * * * *)',
    titleTr: 'Her 10 Dakikada Bir',
    description: 'Executes every 10 minutes at the top of the 10-minute mark.',
    descriptionTr: 'Her 10 dakikada bir otomatik olarak tetiklenir.',
    minute: 'Every 10th minute (*/10)',
    hour: 'Every hour (*)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'frequent',
  },
  {
    slug: 'every-15-minutes',
    expression: '*/15 * * * *',
    title: 'Every 15 Minutes (*/15 * * * *)',
    titleTr: 'Her 15 Dakikada Bir (Çeyrek Saatte Bir)',
    description: 'Executes every 15th minute (at minute 0, 15, 30, and 45).',
    descriptionTr: 'Her çeyrek saatte bir (0, 15, 30 ve 45. dakikalarda) çalışır.',
    minute: 'Every 15th minute (*/15)',
    hour: 'Every hour (*)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'frequent',
  },
  {
    slug: 'every-20-minutes',
    expression: '*/20 * * * *',
    title: 'Every 20 Minutes (*/20 * * * *)',
    titleTr: 'Her 20 Dakikada Bir',
    description: 'Executes every 20 minutes (at minute 0, 20, and 40).',
    descriptionTr: 'Her 20 dakikada bir (0, 20, 40. dakikalarda) çalışır.',
    minute: 'Every 20th minute (*/20)',
    hour: 'Every hour (*)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'frequent',
  },
  {
    slug: 'every-30-minutes',
    expression: '*/30 * * * *',
    title: 'Every 30 Minutes (*/30 * * * *)',
    titleTr: 'Her 30 Dakikada Bir (Yarım Saatte Bir)',
    description: 'Executes every half hour (at minute 0 and minute 30).',
    descriptionTr: 'Yarım saatte bir (saat başı ve buçukta) çalışır.',
    minute: 'Every 30th minute (*/30)',
    hour: 'Every hour (*)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'frequent',
  },
  {
    slug: 'every-45-minutes',
    expression: '*/45 * * * *',
    title: 'Every 45 Minutes (*/45 * * * *)',
    titleTr: 'Her 45 Dakikada Bir',
    description: 'Executes at minute 0 and 45 of each hour.',
    descriptionTr: 'Her 45 dakikada bir tetiklenir.',
    minute: 'At minute 0 and 45 (*/45)',
    hour: 'Every hour (*)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'frequent',
  },

  // ----------------------------------------------------
  // HOURLY
  // ----------------------------------------------------
  {
    slug: 'every-hour',
    expression: '0 * * * *',
    title: 'Every Hour (0 * * * *)',
    titleTr: 'Her Saat Başı',
    description: 'Executes at the beginning of every hour (minute 0).',
    descriptionTr: 'Günün her saatinde, tam saat başında (0. dakikada) çalışır.',
    minute: '0',
    hour: 'Every hour (*)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'hourly',
  },
  {
    slug: 'every-2-hours',
    expression: '0 */2 * * *',
    title: 'Every 2 Hours (0 */2 * * *)',
    titleTr: 'Her 2 Saatte Bir',
    description: 'Executes at minute 0 of every 2nd hour (00:00, 02:00, 04:00, etc.).',
    descriptionTr: 'Her iki saatte bir tam saat başında çalışır.',
    minute: '0',
    hour: 'Every 2nd hour (*/2)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'hourly',
  },
  {
    slug: 'every-3-hours',
    expression: '0 */3 * * *',
    title: 'Every 3 Hours (0 */3 * * *)',
    titleTr: 'Her 3 Saatte Bir',
    description: 'Executes every 3 hours (00:00, 03:00, 06:00, 09:00, 12:00, 15:00, 18:00, 21:00).',
    descriptionTr: 'Günde 8 kez, her 3 saatte bir çalışır.',
    minute: '0',
    hour: 'Every 3rd hour (*/3)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'hourly',
  },
  {
    slug: 'every-4-hours',
    expression: '0 */4 * * *',
    title: 'Every 4 Hours (0 */4 * * *)',
    titleTr: 'Her 4 Saatte Bir',
    description: 'Executes every 4 hours (00:00, 04:00, 08:00, 12:00, 16:00, 20:00).',
    descriptionTr: 'Günde 6 kez, her 4 saatte bir çalışır.',
    minute: '0',
    hour: 'Every 4th hour (*/4)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'hourly',
  },
  {
    slug: 'every-6-hours',
    expression: '0 */6 * * *',
    title: 'Every 6 Hours (0 */6 * * *)',
    titleTr: 'Her 6 Saatte Bir (Günde 4 Kez)',
    description: 'Executes 4 times a day at 00:00, 06:00, 12:00, and 18:00.',
    descriptionTr: 'Günde 4 defa, altışar saatlik aralıklarla çalışır.',
    minute: '0',
    hour: 'Every 6th hour (*/6)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'hourly',
  },
  {
    slug: 'every-8-hours',
    expression: '0 */8 * * *',
    title: 'Every 8 Hours (0 */8 * * *)',
    titleTr: 'Her 8 Saatte Bir (Günde 3 Kez)',
    description: 'Executes every 8 hours at 00:00, 08:00, and 16:00.',
    descriptionTr: 'Günde 3 kez, her 8 saatte bir tetiklenir.',
    minute: '0',
    hour: 'Every 8th hour (*/8)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'hourly',
  },
  {
    slug: 'every-12-hours',
    expression: '0 */12 * * *',
    title: 'Every 12 Hours (0 */12 * * *)',
    titleTr: 'Her 12 Saatte Bir (Günde İki Kez)',
    description: 'Executes twice a day at midnight (00:00) and noon (12:00).',
    descriptionTr: 'Günde iki defa, gece yarısı ve öğlen tam 12:00\'de çalışır.',
    minute: '0',
    hour: 'Every 12 hours (*/12)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day (*)',
    category: 'hourly',
  },
  {
    slug: 'hourly-at-15-past',
    expression: '15 * * * *',
    title: 'Hourly at 15 Minutes Past (15 * * * *)',
    titleTr: 'Her Saati 15 Geçe',
    description: 'Executes at minute 15 of every hour.',
    descriptionTr: 'Her saat başından 15 dakika sonra çalışır.',
    minute: '15',
    hour: 'Every hour (*)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day (*)',
    category: 'hourly',
  },
  {
    slug: 'hourly-at-30-past',
    expression: '30 * * * *',
    title: 'Hourly at Half Past (30 * * * *)',
    titleTr: 'Her Saati Buçuk Geçe',
    description: 'Executes at minute 30 of every single hour.',
    descriptionTr: 'Her saatin 30. dakikasında tetiklenir.',
    minute: '30',
    hour: 'Every hour (*)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day (*)',
    category: 'hourly',
  },
  {
    slug: 'hourly-at-45-past',
    expression: '45 * * * *',
    title: 'Hourly at 45 Minutes Past (45 * * * *)',
    titleTr: 'Her Saati 45 Geçe',
    description: 'Executes at minute 45 of every hour.',
    descriptionTr: 'Her saatin 45. dakikasında çalışır.',
    minute: '45',
    hour: 'Every hour (*)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day (*)',
    category: 'hourly',
  },

  // ----------------------------------------------------
  // DAILY (All 24 hours of the day)
  // ----------------------------------------------------
  {
    slug: 'every-day-at-midnight',
    expression: '0 0 * * *',
    title: 'Every Day at Midnight (0 0 * * *)',
    titleTr: 'Her Gün Gece Yarısı (00:00)',
    description: 'Executes daily at 00:00 midnight. The standard for daily database backups and log rotations.',
    descriptionTr: 'Her gün gece yarısı tam 00:00\'da çalışır. Günlük yedekler ve log temizliği için standarttır.',
    minute: '0',
    hour: '0 (Midnight)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-1am',
    expression: '0 1 * * *',
    title: 'Every Day at 1:00 AM (0 1 * * *)',
    titleTr: 'Her Gün Gece 01:00',
    description: 'Executes once a day at 01:00 AM during low-traffic server hours.',
    descriptionTr: 'Her gün gece 01:00\'de sunucu trafiğinin düşük olduğu saatlerde çalışır.',
    minute: '0',
    hour: '1',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-2am',
    expression: '0 2 * * *',
    title: 'Every Day at 2:00 AM (0 2 * * *)',
    titleTr: 'Her Gün Gece 02:00',
    description: 'Executes once a day at 02:00 AM. Ideal for heavy database vacuuming and data warehouse syncs.',
    descriptionTr: 'Her gün gece 02:00\'de çalışır. Ağır veritabanı indeksleme işlemleri için uygundur.',
    minute: '0',
    hour: '2',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-3am',
    expression: '0 3 * * *',
    title: 'Every Day at 3:00 AM (0 3 * * *)',
    titleTr: 'Her Gün Gece 03:00',
    description: 'Executes daily at 03:00 AM. Highly recommended for system maintenance tasks.',
    descriptionTr: 'Her gün sabah karşı 03:00\'te çalışır.',
    minute: '0',
    hour: '3',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-4am',
    expression: '0 4 * * *',
    title: 'Every Day at 4:00 AM (0 4 * * *)',
    titleTr: 'Her Gün Sabah Karşı 04:00',
    description: 'Executes daily at 04:00 AM.',
    descriptionTr: 'Her gün sabah karşı 04:00\'te tetiklenir.',
    minute: '0',
    hour: '4',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-5am',
    expression: '0 5 * * *',
    title: 'Every Day at 5:00 AM (0 5 * * *)',
    titleTr: 'Her Gün Sabah 05:00',
    description: 'Executes daily at 05:00 AM before the morning business rush.',
    descriptionTr: 'Her sabah saat 05:00\'te iş saatleri başlamadan hemen önce çalışır.',
    minute: '0',
    hour: '5',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-6am',
    expression: '0 6 * * *',
    title: 'Every Day at 6:00 AM (0 6 * * *)',
    titleTr: 'Her Gün Sabah 06:00',
    description: 'Executes daily at 06:00 AM.',
    descriptionTr: 'Her sabah saat 06:00\'da çalışır.',
    minute: '0',
    hour: '6',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-7am',
    expression: '0 7 * * *',
    title: 'Every Day at 7:00 AM (0 7 * * *)',
    titleTr: 'Her Gün Sabah 07:00',
    description: 'Executes daily at 07:00 AM. Perfect for compiling morning digest emails.',
    descriptionTr: 'Her sabah saat 07:00\'de sabah bültenleri için tetiklenir.',
    minute: '0',
    hour: '7',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-8am',
    expression: '0 8 * * *',
    title: 'Every Day at 8:00 AM (0 8 * * *)',
    titleTr: 'Her Gün Sabah 08:00',
    description: 'Executes daily at 08:00 AM.',
    descriptionTr: 'Her sabah saat 08:00\'de çalışır.',
    minute: '0',
    hour: '8',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-9am',
    expression: '0 9 * * *',
    title: 'Every Day at 9:00 AM (0 9 * * *)',
    titleTr: 'Her Gün Sabah 09:00',
    description: 'Executes daily at 09:00 AM at the start of normal business hours.',
    descriptionTr: 'Her sabah saat 09:00\'da mesai başlangıcında tetiklenir.',
    minute: '0',
    hour: '9',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-10am',
    expression: '0 10 * * *',
    title: 'Every Day at 10:00 AM (0 10 * * *)',
    titleTr: 'Her Gün Sabah 10:00',
    description: 'Executes daily at 10:00 AM.',
    descriptionTr: 'Her gün sabah 10:00\'da çalışır.',
    minute: '0',
    hour: '10',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-11am',
    expression: '0 11 * * *',
    title: 'Every Day at 11:00 AM (0 11 * * *)',
    titleTr: 'Her Gün 11:00',
    description: 'Executes daily at 11:00 AM.',
    descriptionTr: 'Her gün 11:00\'de çalışır.',
    minute: '0',
    hour: '11',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-noon',
    expression: '0 12 * * *',
    title: 'Every Day at Noon (0 12 * * *)',
    titleTr: 'Her Gün Öğlen 12:00',
    description: 'Executes daily at 12:00 PM midday.',
    descriptionTr: 'Her gün öğlen tam 12:00\'de çalışır.',
    minute: '0',
    hour: '12 (Noon)',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-1pm',
    expression: '0 13 * * *',
    title: 'Every Day at 1:00 PM (0 13 * * *)',
    titleTr: 'Her Gün Öğleden Sonra 13:00',
    description: 'Executes daily at 13:00 (1:00 PM).',
    descriptionTr: 'Her gün saat 13:00\'te çalışır.',
    minute: '0',
    hour: '13',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-2pm',
    expression: '0 14 * * *',
    title: 'Every Day at 2:00 PM (0 14 * * *)',
    titleTr: 'Her Gün 14:00',
    description: 'Executes daily at 14:00 (2:00 PM).',
    descriptionTr: 'Her gün saat 14:00\'te çalışır.',
    minute: '0',
    hour: '14',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-3pm',
    expression: '0 15 * * *',
    title: 'Every Day at 3:00 PM (0 15 * * *)',
    titleTr: 'Her Gün 15:00',
    description: 'Executes daily at 15:00 (3:00 PM).',
    descriptionTr: 'Her gün saat 15:00\'te çalışır.',
    minute: '0',
    hour: '15',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-4pm',
    expression: '0 16 * * *',
    title: 'Every Day at 4:00 PM (0 16 * * *)',
    titleTr: 'Her Gün 16:00',
    description: 'Executes daily at 16:00 (4:00 PM).',
    descriptionTr: 'Her gün saat 16:00\'da çalışır.',
    minute: '0',
    hour: '16',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-5pm',
    expression: '0 17 * * *',
    title: 'Every Day at 5:00 PM (0 17 * * *)',
    titleTr: 'Her Gün 17:00',
    description: 'Executes daily at 17:00 (5:00 PM) at the end of traditional working hours.',
    descriptionTr: 'Her gün saat 17:00\'de mesai bitiminde çalışır.',
    minute: '0',
    hour: '17',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-6pm',
    expression: '0 18 * * *',
    title: 'Every Day at 6:00 PM (0 18 * * *)',
    titleTr: 'Her Gün Akşam 18:00',
    description: 'Executes daily at 18:00 (6:00 PM).',
    descriptionTr: 'Her akşam saat 18:00\'de çalışır.',
    minute: '0',
    hour: '18',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-7pm',
    expression: '0 19 * * *',
    title: 'Every Day at 7:00 PM (0 19 * * *)',
    titleTr: 'Her Gün Akşam 19:00',
    description: 'Executes daily at 19:00 (7:00 PM).',
    descriptionTr: 'Her akşam saat 19:00\'da çalışır.',
    minute: '0',
    hour: '19',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-8pm',
    expression: '0 20 * * *',
    title: 'Every Day at 8:00 PM (0 20 * * *)',
    titleTr: 'Her Gün Akşam 20:00',
    description: 'Executes daily at 20:00 (8:00 PM).',
    descriptionTr: 'Her akşam saat 20:00\'de çalışır.',
    minute: '0',
    hour: '20',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-9pm',
    expression: '0 21 * * *',
    title: 'Every Day at 9:00 PM (0 21 * * *)',
    titleTr: 'Her Gün Gece 21:00',
    description: 'Executes daily at 21:00 (9:00 PM).',
    descriptionTr: 'Her akşam saat 21:00\'de tetiklenir.',
    minute: '0',
    hour: '21',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-10pm',
    expression: '0 22 * * *',
    title: 'Every Day at 10:00 PM (0 22 * * *)',
    titleTr: 'Her Gün Gece 22:00',
    description: 'Executes daily at 22:00 (10:00 PM).',
    descriptionTr: 'Her gece saat 22:00\'de çalışır.',
    minute: '0',
    hour: '22',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-11pm',
    expression: '0 23 * * *',
    title: 'Every Day at 11:00 PM (0 23 * * *)',
    titleTr: 'Her Gün Gece 23:00',
    description: 'Executes daily at 23:00 (11:00 PM) before the midnight rollover.',
    descriptionTr: 'Her gece saat 23:00\'te çalışır.',
    minute: '0',
    hour: '23',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-3-30am',
    expression: '30 3 * * *',
    title: 'Every Day at 3:30 AM (30 3 * * *)',
    titleTr: 'Her Gün Sabah Karşı 03:30',
    description: 'Executes daily at 03:30 AM.',
    descriptionTr: 'Her gün sabah karşı 03:30\'da çalışır.',
    minute: '30',
    hour: '3',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },
  {
    slug: 'every-day-at-4-30am',
    expression: '30 4 * * *',
    title: 'Every Day at 4:30 AM (30 4 * * *)',
    titleTr: 'Her Gün Sabah Karşı 04:30',
    description: 'Executes daily at 04:30 AM.',
    descriptionTr: 'Her gün sabah karşı 04:30\'da çalışır.',
    minute: '30',
    hour: '4',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day of week (*)',
    category: 'daily',
  },

  // ----------------------------------------------------
  // WEEKDAYS & WEEKENDS
  // ----------------------------------------------------
  {
    slug: 'every-weekday-at-midnight',
    expression: '0 0 * * 1-5',
    title: 'Every Weekday at Midnight (0 0 * * 1-5)',
    titleTr: 'Hafta İçi Her Gece Yarısı',
    description: 'Executes Monday through Friday at 00:00 midnight.',
    descriptionTr: 'Pazartesi\'den Cuma\'ya hafta içi her gece yarısı çalışır.',
    minute: '0',
    hour: '0',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Monday to Friday (1-5)',
    category: 'weekly',
  },
  {
    slug: 'every-weekday-at-6am',
    expression: '0 6 * * 1-5',
    title: 'Every Weekday at 6:00 AM (0 6 * * 1-5)',
    titleTr: 'Hafta İçi Her Sabah 06:00',
    description: 'Executes Monday through Friday at 06:00 AM.',
    descriptionTr: 'Hafta içi Pazartesi-Cuma sabah 06:00\'da tetiklenir.',
    minute: '0',
    hour: '6',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Monday to Friday (1-5)',
    category: 'weekly',
  },
  {
    slug: 'every-weekday-at-8am',
    expression: '0 8 * * 1-5',
    title: 'Every Weekday at 8:00 AM (0 8 * * 1-5)',
    titleTr: 'Hafta İçi Her Sabah 08:00',
    description: 'Executes Monday through Friday at 08:00 AM.',
    descriptionTr: 'Hafta içi mesai öncesi sabah 08:00\'de çalışır.',
    minute: '0',
    hour: '8',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Monday to Friday (1-5)',
    category: 'weekly',
  },
  {
    slug: 'every-weekday-at-9am',
    expression: '0 9 * * 1-5',
    title: 'Every Weekday at 9:00 AM (0 9 * * 1-5)',
    titleTr: 'Hafta İçi Her Sabah 09:00',
    description: 'Executes Monday through Friday at 09:00 AM (ideal for daily standup reminders and morning reports).',
    descriptionTr: 'Hafta içi Pazartesi - Cuma günleri sabah 09:00\'da tetiklenir.',
    minute: '0',
    hour: '9',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Monday to Friday (1-5)',
    category: 'weekly',
  },
  {
    slug: 'every-weekday-at-noon',
    expression: '0 12 * * 1-5',
    title: 'Every Weekday at Noon (0 12 * * 1-5)',
    titleTr: 'Hafta İçi Her Öğlen 12:00',
    description: 'Executes Monday through Friday at 12:00 PM.',
    descriptionTr: 'Hafta içi öğlen 12:00\'de tetiklenir.',
    minute: '0',
    hour: '12',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Monday to Friday (1-5)',
    category: 'weekly',
  },
  {
    slug: 'every-weekday-at-5pm',
    expression: '0 17 * * 1-5',
    title: 'Every Weekday at 5:00 PM (0 17 * * 1-5)',
    titleTr: 'Hafta İçi Her Akşam 17:00',
    description: 'Executes Monday through Friday at 17:00 (5:00 PM) for end-of-day reports.',
    descriptionTr: 'Hafta içi her akşam 17:00\'de gün sonu raporlamaları için çalışır.',
    minute: '0',
    hour: '17',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Monday to Friday (1-5)',
    category: 'weekly',
  },
  {
    slug: 'every-weekend-at-midnight',
    expression: '0 0 * * 6,0',
    title: 'Every Weekend at Midnight (0 0 * * 6,0)',
    titleTr: 'Hafta Sonu Her Gece Yarısı',
    description: 'Executes Saturday and Sunday at 00:00 midnight.',
    descriptionTr: 'Cumartesi ve Pazar günleri gece yarısı çalışır.',
    minute: '0',
    hour: '0',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Saturday and Sunday (6,0)',
    category: 'weekly',
  },
  {
    slug: 'every-weekend-at-noon',
    expression: '0 12 * * 6,0',
    title: 'Every Weekend at Noon (0 12 * * 6,0)',
    titleTr: 'Hafta Sonu Her Öğlen 12:00',
    description: 'Executes Saturday and Sunday at 12:00 PM.',
    descriptionTr: 'Hafta sonu Cumartesi ve Pazar öğlen 12:00\'de çalışır.',
    minute: '0',
    hour: '12',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Saturday and Sunday (6,0)',
    category: 'weekly',
  },

  // ----------------------------------------------------
  // DAYS OF WEEK (Monday through Sunday)
  // ----------------------------------------------------
  {
    slug: 'every-sunday-at-midnight',
    expression: '0 0 * * 0',
    title: 'Every Sunday at Midnight (0 0 * * 0)',
    titleTr: 'Her Pazar Gece Yarısı',
    description: 'Executes once a week on Sunday at 00:00 midnight. Prime slot for weekly backups.',
    descriptionTr: 'Her Pazar gecesi tam 00:00\'da haftalık yedeklemeler için çalışır.',
    minute: '0',
    hour: '0',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Sunday (0)',
    category: 'weekly',
  },
  {
    slug: 'every-monday-at-midnight',
    expression: '0 0 * * 1',
    title: 'Every Monday at Midnight (0 0 * * 1)',
    titleTr: 'Her Pazartesi Gece Yarısı',
    description: 'Executes every Monday at 00:00 at the very start of the work week.',
    descriptionTr: 'Her Pazartesi gece yarısı tam 00:00\'da haftanın başlangıcında çalışır.',
    minute: '0',
    hour: '0',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Monday (1)',
    category: 'weekly',
  },
  {
    slug: 'every-monday-at-9am',
    expression: '0 9 * * 1',
    title: 'Every Monday at 9:00 AM (0 9 * * 1)',
    titleTr: 'Her Pazartesi Sabah 09:00',
    description: 'Executes every Monday morning at 09:00 AM for weekly planning and kickoff summaries.',
    descriptionTr: 'Her Pazartesi sabah 09:00\'da haftalık planlama ve toplantı bildirimleri için çalışır.',
    minute: '0',
    hour: '9',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Monday (1)',
    category: 'weekly',
  },
  {
    slug: 'every-tuesday-at-midnight',
    expression: '0 0 * * 2',
    title: 'Every Tuesday at Midnight (0 0 * * 2)',
    titleTr: 'Her Salı Gece Yarısı',
    description: 'Executes every Tuesday at 00:00 midnight.',
    descriptionTr: 'Her Salı gecesi tam 00:00\'da çalışır.',
    minute: '0',
    hour: '0',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Tuesday (2)',
    category: 'weekly',
  },
  {
    slug: 'every-wednesday-at-midnight',
    expression: '0 0 * * 3',
    title: 'Every Wednesday at Midnight (0 0 * * 3)',
    titleTr: 'Her Çarşamba Gece Yarısı',
    description: 'Executes every Wednesday at 00:00 midnight (mid-week jobs).',
    descriptionTr: 'Her Çarşamba gecesi tam 00:00\'da çalışır.',
    minute: '0',
    hour: '0',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Wednesday (3)',
    category: 'weekly',
  },
  {
    slug: 'every-thursday-at-midnight',
    expression: '0 0 * * 4',
    title: 'Every Thursday at Midnight (0 0 * * 4)',
    titleTr: 'Her Perşembe Gece Yarısı',
    description: 'Executes every Thursday at 00:00 midnight.',
    descriptionTr: 'Her Perşembe gecesi tam 00:00\'da çalışır.',
    minute: '0',
    hour: '0',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Thursday (4)',
    category: 'weekly',
  },
  {
    slug: 'every-friday-at-midnight',
    expression: '0 0 * * 5',
    title: 'Every Friday at Midnight (0 0 * * 5)',
    titleTr: 'Her Cuma Gece Yarısı',
    description: 'Executes every Friday at 00:00 midnight.',
    descriptionTr: 'Her Cuma gecesi tam 00:00\'da çalışır.',
    minute: '0',
    hour: '0',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Friday (5)',
    category: 'weekly',
  },
  {
    slug: 'every-friday-at-5pm',
    expression: '0 17 * * 5',
    title: 'Every Friday at 5:00 PM (0 17 * * 5)',
    titleTr: 'Her Cuma Akşam 17:00',
    description: 'Executes every Friday at 17:00 (5:00 PM) for weekly timesheet and sprint retrospective digests.',
    descriptionTr: 'Her Cuma akşamı 17:00\'de haftalık çalışma özeti ve raporlar için çalışır.',
    minute: '0',
    hour: '17',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Friday (5)',
    category: 'weekly',
  },
  {
    slug: 'every-saturday-at-midnight',
    expression: '0 0 * * 6',
    title: 'Every Saturday at Midnight (0 0 * * 6)',
    titleTr: 'Her Cumartesi Gece Yarısı',
    description: 'Executes at 00:00 every Saturday night (ideal for heavy maintenance, DB compaction, and file archiving).',
    descriptionTr: 'Her Cumartesi gecesi tam 00:00\'da haftalık bakım için çalışır.',
    minute: '0',
    hour: '0',
    dayOfMonth: 'Every day (*)',
    month: 'Every month (*)',
    dayOfWeek: 'Saturday (6)',
    category: 'weekly',
  },

  // ----------------------------------------------------
  // MONTHLY, QUARTERLY & YEARLY
  // ----------------------------------------------------
  {
    slug: 'first-day-of-every-month',
    expression: '0 0 1 * *',
    title: '1st Day of Every Month at Midnight (0 0 1 * *)',
    titleTr: 'Her Ayın 1. Günü Gece Yarısı',
    description: 'Executes at 00:00 on day 1 of every month. Standard for monthly invoicing and subscription renewals.',
    descriptionTr: 'Her ayın ilk günü gece yarısı çalışır. Fatura kesimi ve abonelik yenilemeleri için standarttır.',
    minute: '0',
    hour: '0',
    dayOfMonth: '1st (1)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day (*)',
    category: 'monthly',
  },
  {
    slug: 'first-day-of-every-month-at-noon',
    expression: '0 12 1 * *',
    title: '1st Day of Every Month at Noon (0 12 1 * *)',
    titleTr: 'Her Ayın 1. Günü Öğlen 12:00',
    description: 'Executes at 12:00 PM on the 1st of every month.',
    descriptionTr: 'Her ayın 1. günü öğlen 12:00\'de çalışır.',
    minute: '0',
    hour: '12',
    dayOfMonth: '1st (1)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day (*)',
    category: 'monthly',
  },
  {
    slug: '15th-day-of-every-month',
    expression: '0 0 15 * *',
    title: '15th Day of Every Month (0 0 15 * *)',
    titleTr: 'Her Ayın 15. Günü Gece Yarısı',
    description: 'Executes at midnight on the 15th of each month (mid-month payroll and billing audits).',
    descriptionTr: 'Her ayın 15. günü gece yarısı çalışır. Ay ortası maaş ve bütçe kontrolleri için idealdir.',
    minute: '0',
    hour: '0',
    dayOfMonth: '15th (15)',
    month: 'Every month (*)',
    dayOfWeek: 'Every day (*)',
    category: 'monthly',
  },
  {
    slug: 'first-monday-of-every-month',
    expression: '0 0 1-7 * 1',
    title: 'First Monday of Every Month (0 0 1-7 * 1)',
    titleTr: 'Her Ayın İlk Pazartesi Günü',
    description: 'Executes on the first Monday of each month (between days 1-7 when the day of week is Monday).',
    descriptionTr: 'Her ayın ilk Pazartesi gününde gece yarısı 00:00\'da çalışır.',
    minute: '0',
    hour: '0',
    dayOfMonth: '1-7 (First week)',
    month: 'Every month (*)',
    dayOfWeek: 'Monday (1)',
    category: 'monthly',
  },
  {
    slug: 'every-quarter-at-midnight',
    expression: '0 0 1 1,4,7,10 *',
    title: 'Every Quarter at Midnight (0 0 1 1,4,7,10 *)',
    titleTr: 'Her Çeyrek Yıl Başında (Q1, Q2, Q3, Q4)',
    description: 'Executes at midnight on the first day of January, April, July, and October (quarterly business reviews).',
    descriptionTr: 'Ocak, Nisan, Temmuz ve Ekim aylarının ilk günü gece yarısı çeyrek dönem raporları için çalışır.',
    minute: '0',
    hour: '0',
    dayOfMonth: '1st (1)',
    month: 'Jan, Apr, Jul, Oct (1,4,7,10)',
    dayOfWeek: 'Every day (*)',
    category: 'monthly',
  },
  {
    slug: 'every-6-months',
    expression: '0 0 1 1,7 *',
    title: 'Every 6 Months (0 0 1 1,7 *)',
    titleTr: 'Her 6 Ayda Bir (Yılda İki Kez)',
    description: 'Executes semi-annually on January 1st and July 1st at 00:00 midnight.',
    descriptionTr: 'Yılda iki defa, 1 Ocak ve 1 Temmuz tarihlerinde gece yarısı çalışır.',
    minute: '0',
    hour: '0',
    dayOfMonth: '1st (1)',
    month: 'January and July (1,7)',
    dayOfWeek: 'Every day (*)',
    category: 'monthly',
  },
  {
    slug: 'first-day-of-every-year',
    expression: '0 0 1 1 *',
    title: 'Once a Year on Jan 1st at Midnight (0 0 1 1 *)',
    titleTr: 'Yılda Bir Kez (1 Ocak Gece Yarısı)',
    description: 'Executes annually at midnight on January 1st (annual fiscal year rollover and compliance audits).',
    descriptionTr: 'Her yıl 1 Ocak gece yarısı 00:00\'da yıllık bakım veya mali yıl yenilemesi için çalışır.',
    minute: '0',
    hour: '0',
    dayOfMonth: '1st (1)',
    month: 'January (1)',
    dayOfWeek: 'Every day (*)',
    category: 'monthly',
  },
];

export function getAllCronSchedules(): CronScheduleInfo[] {
  return CRON_SCHEDULES;
}

export function getCronScheduleBySlug(slug: string): CronScheduleInfo | undefined {
  return CRON_SCHEDULES.find((s) => s.slug === slug);
}
