export interface DnsRecordData {
  type: string;
  slug: string;
  name: string;
  rfc: string;
  category: 'Routing & Resolution' | 'Email & Authentication' | 'Security & Certificates' | 'Infrastructure & Zone';
  summary: string;
  description: string;
  zoneExample: string;
  defaultTtl: string;
  terminalDig: string;
  terminalNslookup: string;
  powershellCommand: string;
  commonUseCases: string[];
  configurationAdvice: string;
  commonMistakes: string;
}

export const DNS_RECORDS_DATA: DnsRecordData[] = [
  // --- Routing & Resolution ---
  {
    type: 'A',
    slug: 'a-record',
    name: 'A Record (IPv4 Address)',
    rfc: 'RFC 1035',
    category: 'Routing & Resolution',
    summary: 'Maps a human-readable domain name directly to a 32-bit IPv4 address (e.g. 192.0.2.1).',
    description: 'The A (Address) record is the most fundamental DNS record on the internet. When a browser queries your website domain, the resolver looks up the A record to locate the web server or load balancer IPv4 address.',
    zoneExample: 'example.com.    3600    IN    A    76.76.21.21',
    defaultTtl: '3600 seconds (1 hour)',
    terminalDig: 'dig +short A example.com',
    terminalNslookup: 'nslookup -type=A example.com',
    powershellCommand: 'Resolve-DnsName -Name example.com -Type A',
    commonUseCases: [
      'Pointing an apex root domain (`example.com`) to a web host or static IP',
      'Configuring server IP addresses for VPS, dedicated servers, or load balancers',
      'Pointing subdomains (`api.example.com`) to backend clusters',
    ],
    configurationAdvice: 'For zero-downtime server migrations, reduce the A record TTL to 300 seconds (5 minutes) at least 24 hours prior to changing the IP address.',
    commonMistakes: 'Pointing an A record to a domain name instead of an IP address (use CNAME instead for domain aliases).',
  },
  {
    type: 'AAAA',
    slug: 'aaaa-record',
    name: 'AAAA Record (IPv6 Address / Quad-A)',
    rfc: 'RFC 3596',
    category: 'Routing & Resolution',
    summary: 'Maps a domain name to a 128-bit IPv6 address (e.g. 2001:0db8:85a3:0000:0000:8a2e:0370:7334).',
    description: 'The AAAA (Quad-A) record operates identically to an A record, but handles modern 128-bit IPv6 addresses. Dual-stack servers publish both A and AAAA records, allowing IPv6-capable clients to connect with lower routing latency.',
    zoneExample: 'example.com.    3600    IN    AAAA    2606:4700:4700::1111',
    defaultTtl: '3600 seconds (1 hour)',
    terminalDig: 'dig +short AAAA example.com',
    terminalNslookup: 'nslookup -type=AAAA example.com',
    powershellCommand: 'Resolve-DnsName -Name example.com -Type AAAA',
    commonUseCases: [
      'Enabling modern IPv6 traffic for Cloudflare, AWS CloudFront, or Vercel edge networks',
      'Complying with Apple App Store IPv6-only network requirements',
    ],
    configurationAdvice: 'Ensure your web server and firewall actually accept and route IPv6 traffic before adding an AAAA record, otherwise IPv6 visitors may experience connection timeouts.',
    commonMistakes: 'Formatting IPv6 addresses with port numbers or surrounding brackets in DNS zone files.',
  },
  {
    type: 'CNAME',
    slug: 'cname-record',
    name: 'CNAME Record (Canonical Name / Alias)',
    rfc: 'RFC 1035',
    category: 'Routing & Resolution',
    summary: 'Creates an alias pointing one domain or subdomain to another domain name.',
    description: 'The CNAME (Canonical Name) record instructs DNS resolvers to restart the query using the target domain name. It is the standard method for mapping subdomains (`www.example.com` or `shop.example.com`) to SaaS providers (Vercel, Shopify, Netlify, GitHub Pages).',
    zoneExample: 'www.example.com.    3600    IN    CNAME    cname.vercel-dns.com.',
    defaultTtl: '3600 seconds (1 hour)',
    terminalDig: 'dig +short CNAME www.example.com',
    terminalNslookup: 'nslookup -type=CNAME www.example.com',
    powershellCommand: 'Resolve-DnsName -Name www.example.com -Type CNAME',
    commonUseCases: [
      'Aliasing `www` to your root domain or edge host (`cname.vercel-dns.com`)',
      'Configuring custom subdomains for SaaS tools (`status.example.com` -> `statuspage.io`)',
      'Automated SSL certificate validation (ACM, Let\'s Encrypt DNS challenges)',
    ],
    configurationAdvice: 'According to RFC 1035, you CANNOT place a CNAME record at the zone apex (`example.com`) if MX or NS records exist. Use CNAME Flattening or ALIAS records for root domains.',
    commonMistakes: 'Attempting to create a CNAME record on the root domain `example.com` on providers that do not support CNAME flattening, breaking email delivery.',
  },
  {
    type: 'ALIAS',
    slug: 'alias-record',
    name: 'ALIAS / ANAME Record (Virtual Apex CNAME)',
    rfc: 'Provider-specific (RFC Draft)',
    category: 'Routing & Resolution',
    summary: 'A virtual DNS record that allows CNAME-like behavior at the root domain apex without violating RFC 1035.',
    description: 'ALIAS (or ANAME) is implemented at the authoritative DNS provider level (Cloudflare, AWS Route 53, DNSimple). When queried, the DNS server resolves the target hostname and dynamically returns the IP address as an A or AAAA record.',
    zoneExample: 'example.com.    300    IN    ALIAS    my-app.vercel.app.',
    defaultTtl: '300 seconds (5 minutes)',
    terminalDig: 'dig +short A example.com # Resolves dynamically to target IP',
    terminalNslookup: 'nslookup -type=A example.com',
    powershellCommand: 'Resolve-DnsName -Name example.com -Type A',
    commonUseCases: [
      'Pointing an apex domain (`example.com`) to AWS Elastic Load Balancers, Vercel, or Heroku without breaking MX records',
      'Automatic IP tracking for cloud services that do not provide static IP addresses',
    ],
    configurationAdvice: 'Use ALIAS or CNAME Flattening whenever hosting an apex domain on modern cloud serverless platforms.',
    commonMistakes: 'Looking for an "ALIAS" query type in dig; ALIAS records are synthesized by nameservers and always respond as A or AAAA.',
  },

  // --- Email & Authentication ---
  {
    type: 'MX',
    slug: 'mx-record',
    name: 'MX Record (Mail Exchange)',
    rfc: 'RFC 5321',
    category: 'Email & Authentication',
    summary: 'Specifies the mail servers responsible for accepting incoming email messages on behalf of the domain.',
    description: 'MX (Mail Exchange) records route incoming emails to mail providers like Google Workspace, Microsoft 365, Fastmail, or ProtonMail. Each MX record includes a priority preference number; sending MTAs attempt the lowest priority number first.',
    zoneExample: 'example.com.    3600    IN    MX    1    aspmx.l.google.com.\nexample.com.    3600    IN    MX    5    alt1.aspmx.l.google.com.',
    defaultTtl: '3600 seconds (1 hour)',
    terminalDig: 'dig +short MX example.com',
    terminalNslookup: 'nslookup -type=MX example.com',
    powershellCommand: 'Resolve-DnsName -Name example.com -Type MX',
    commonUseCases: [
      'Connecting domains to Google Workspace / Gmail for business',
      'Configuring Microsoft Exchange / Office 365 mail routing',
      'Setting up backup fallback mail servers with higher priority numbers',
    ],
    configurationAdvice: 'Always point MX records to hostnames, NEVER directly to IP addresses. The target hostnames must themselves resolve to A/AAAA records.',
    commonMistakes: 'Forgetting trailing dots in BIND zone files, causing hostnames to become `aspmx.l.google.com.example.com`.',
  },
  {
    type: 'TXT',
    slug: 'txt-record',
    name: 'TXT Record (Text / Arbitrary Data)',
    rfc: 'RFC 1035',
    category: 'Email & Authentication',
    summary: 'Carries arbitrary machine-readable or human-readable text associated with a domain.',
    description: 'TXT (Text) records are universally employed for domain ownership verification (Google Search Console, GitHub, Vercel, Atlassian) and email security frameworks (SPF, DKIM, DMARC).',
    zoneExample: 'example.com.    3600    IN    TXT    "google-site-verification=s4kiAyjXGpZ7gq-DdsQY38jMii9EaQbfaQvRq5DQaJY"',
    defaultTtl: '3600 seconds (1 hour)',
    terminalDig: 'dig +short TXT example.com',
    terminalNslookup: 'nslookup -type=TXT example.com',
    powershellCommand: 'Resolve-DnsName -Name example.com -Type TXT',
    commonUseCases: [
      'Domain ownership verification (Google Search Console, Vercel, Apple)',
      'Email authentication policies (SPF, DMARC, BIMI)',
      'Cryptographic public key publication (DKIM)',
    ],
    configurationAdvice: 'If a TXT string exceeds 255 characters, split it into multiple quoted strings within the same record as mandated by RFC 4408.',
    commonMistakes: 'Wrapping TXT record values in double quotes twice or omitting quotes in raw zone files.',
  },
  {
    type: 'SPF',
    slug: 'spf-record',
    name: 'SPF Record (Sender Policy Framework TXT)',
    rfc: 'RFC 7208',
    category: 'Email & Authentication',
    summary: 'A TXT record that defines which mail servers and IP addresses are authorized to send email on behalf of your domain.',
    description: 'SPF (Sender Policy Framework) prevents spammers from forging "From:" addresses using your domain. Receiving mail servers check SPF during SMTP handshake; messages sent from unauthorized IPs are marked as spam or rejected.',
    zoneExample: 'example.com.    3600    IN    TXT    "v=spf1 include:_spf.google.com include:sendgrid.net ~all"',
    defaultTtl: '3600 seconds (1 hour)',
    terminalDig: 'dig +short TXT example.com | grep "v=spf1"',
    terminalNslookup: 'nslookup -type=TXT example.com',
    powershellCommand: '(Resolve-DnsName -Name example.com -Type TXT).Strings | Select-String "v=spf1"',
    commonUseCases: [
      'Authorizing Google Workspace, SendGrid, Mailgun, or Postmark to send transactional emails',
      'Preventing domain spoofing and phishing attacks',
      'Ensuring compliance with Gmail & Yahoo 2024 bulk sender deliverability rules',
    ],
    configurationAdvice: 'NEVER publish more than one SPF record for a single domain (combine all `include:` mechanisms into one record). RFC 7208 limits SPF lookups to a maximum of 10 DNS queries.',
    commonMistakes: 'Publishing multiple SPF TXT records, causing receivers to evaluate SPF as PermError and route all emails to spam.',
  },
  {
    type: 'DKIM',
    slug: 'dkim-record',
    name: 'DKIM Record (DomainKeys Identified Mail TXT)',
    rfc: 'RFC 6376',
    category: 'Email & Authentication',
    summary: 'Publishes a cryptographic public key in DNS used to verify that an email message was signed by the domain and not tampered with in transit.',
    description: 'DKIM (DomainKeys Identified Mail) attaches a cryptographic signature to the header of outgoing emails. Receiving servers fetch the public key published at `selector._domainkey.example.com` to cryptographically verify signature integrity.',
    zoneExample: 'google._domainkey.example.com.    3600    IN    TXT    "v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC..."',
    defaultTtl: '3600 seconds (1 hour)',
    terminalDig: 'dig +short TXT google._domainkey.example.com',
    terminalNslookup: 'nslookup -type=TXT google._domainkey.example.com',
    powershellCommand: 'Resolve-DnsName -Name google._domainkey.example.com -Type TXT',
    commonUseCases: [
      'Authenticating emails sent from Google Workspace, SendGrid, Amazon SES, or Mailchimp',
      'Eliminating "via sendgrid.info" warnings in email clients',
      'Meeting mandatory Gmail & Yahoo deliverability standards',
    ],
    configurationAdvice: 'Use 2048-bit RSA keys for DKIM (1024-bit is considered cryptographically weak by modern security audits).',
    commonMistakes: 'Accidentally copying whitespace or truncating long 2048-bit keys when pasting into domain registrars.',
  },
  {
    type: 'DMARC',
    slug: 'dmarc-record',
    name: 'DMARC Record (Domain-based Message Authentication TXT)',
    rfc: 'RFC 7489',
    category: 'Email & Authentication',
    summary: 'Instructs receiving mail servers what action to take (none, quarantine, or reject) if an email fails both SPF and DKIM checks.',
    description: 'DMARC unites SPF and DKIM by establishing an enforcement policy (`p=none`, `p=quarantine`, `p=reject`) and providing automated aggregate reporting (`rua=mailto:...`) so domain owners can audit legitimate versus spoofed email traffic.',
    zoneExample: '_dmarc.example.com.    3600    IN    TXT    "v=DMARC1; p=reject; rua=mailto:dmarc-reports@example.com; pct=100"',
    defaultTtl: '3600 seconds (1 hour)',
    terminalDig: 'dig +short TXT _dmarc.example.com',
    terminalNslookup: 'nslookup -type=TXT _dmarc.example.com',
    powershellCommand: 'Resolve-DnsName -Name _dmarc.example.com -Type TXT',
    commonUseCases: [
      'Preventing attackers from impersonating your executive staff or brand via email spoofing',
      'Unlocking BIMI brand logos in Gmail and Apple Mail inbox interfaces',
      'Receiving daily XML delivery reports to detect unauthorized outbound servers',
    ],
    configurationAdvice: 'Begin with `p=none` for 2–4 weeks to monitor reports without impacting email deliverability. Once all legitimate senders align with SPF/DKIM, upgrade to `p=quarantine` and finally `p=reject`.',
    commonMistakes: 'Jumping straight to `p=reject` without checking third-party CRM or marketing tools, causing critical business emails to bounce.',
  },

  // --- Security & Certificates ---
  {
    type: 'CAA',
    slug: 'caa-record',
    name: 'CAA Record (Certification Authority Authorization)',
    rfc: 'RFC 8659',
    category: 'Security & Certificates',
    summary: 'Specifies which Certificate Authorities (CAs) are permitted to issue TLS/SSL certificates for your domain.',
    description: 'CAA (Certification Authority Authorization) prevents rogue or compromised Certificate Authorities from issuing fraudulent SSL certificates for your domain. CAs are legally mandated by the CA/Browser Forum to check CAA records before certificate issuance.',
    zoneExample: 'example.com.    3600    IN    CAA    0 issue "letsencrypt.org"\nexample.com.    3600    IN    CAA    0 issuewild ";" # Prohibits wildcards',
    defaultTtl: '3600 seconds (1 hour)',
    terminalDig: 'dig +short CAA example.com',
    terminalNslookup: 'nslookup -type=CAA example.com',
    powershellCommand: 'Resolve-DnsName -Name example.com -Type CAA',
    commonUseCases: [
      'Restricting SSL issuance strictly to Let\'s Encrypt (`letsencrypt.org`) or DigiCert',
      'Forbidding wildcard certificate creation (`issuewild ";"`) to mitigate subdomain hijacking',
      'Receiving automated security notifications (`iodef "mailto:security@example.com"`) if unauthorized issuance is attempted',
    ],
    configurationAdvice: 'If using Vercel, AWS CloudFront, or Cloudflare, ensure you authorize their respective CAs (e.g. `letsencrypt.org`, `digicert.com`, `amazontrust.com`) to prevent SSL renewal failures.',
    commonMistakes: 'Adding a CAA record that excludes your hosting provider\'s automated SSL issuer, causing HTTPS renewal to fail and triggering browser security warnings.',
  },
  {
    type: 'PTR',
    slug: 'ptr-record',
    name: 'PTR Record (Pointer / Reverse DNS)',
    rfc: 'RFC 1035',
    category: 'Infrastructure & Zone',
    summary: 'Resolves an IP address back to its canonical domain name (Reverse DNS / rDNS lookup).',
    description: 'PTR (Pointer) records perform the exact inverse of an A record. PTR records are configured within special reverse lookup zones (`in-addr.arpa` for IPv4 and `ip6.arpa` for IPv6). Mail servers strictly verify PTR records (FCrDNS) to combat spam.',
    zoneExample: '4.3.2.1.in-addr.arpa.    3600    IN    PTR    mail.example.com.',
    defaultTtl: '3600 seconds (1 hour)',
    terminalDig: 'dig +short -x 192.0.2.1',
    terminalNslookup: 'nslookup 192.0.2.1',
    powershellCommand: 'Resolve-DnsName -Name 192.0.2.1 -Type PTR',
    commonUseCases: [
      'Configuring Forward-Confirmed Reverse DNS (FCrDNS) for outbound SMTP mail servers',
      'Network diagnostics, traceroute hostname resolution, and server authentication',
    ],
    configurationAdvice: 'PTR records must be requested through your IP provider or hosting company (AWS, DigitalOcean, Hetzner, Linode), not your domain registrar.',
    commonMistakes: 'Attempting to create a PTR record in Cloudflare or GoDaddy for a domain; PTR records belong to the owner of the IP block.',
  },
  {
    type: 'NS',
    slug: 'ns-record',
    name: 'NS Record (Name Server)',
    rfc: 'RFC 1035',
    category: 'Infrastructure & Zone',
    summary: 'Delegates a DNS zone to use specific authoritative nameservers.',
    description: 'NS (Name Server) records indicate which authoritative servers hold the official DNS records for a domain. When you register a domain, your registrar delegates resolution by setting NS records pointing to your DNS host (Cloudflare, Route 53, Vercel).',
    zoneExample: 'example.com.    86400    IN    NS    ns1.cloudflare.com.\nexample.com.    86400    IN    NS    ns2.cloudflare.com.',
    defaultTtl: '86400 seconds (24 hours)',
    terminalDig: 'dig +short NS example.com',
    terminalNslookup: 'nslookup -type=NS example.com',
    powershellCommand: 'Resolve-DnsName -Name example.com -Type NS',
    commonUseCases: [
      'Delegating domain DNS management to Cloudflare, AWS Route 53, or Azure DNS',
      'Creating isolated sub-zones for team engineering clusters (`dev.example.com`)',
    ],
    configurationAdvice: 'Always configure at least two geographically separated nameservers for redundancy. Changes to NS records can take 24–48 hours to fully propagate worldwide.',
    commonMistakes: 'Deleting NS records in your DNS zone file, which can cause entire domain resolution to break.',
  },
  {
    type: 'SRV',
    slug: 'srv-record',
    name: 'SRV Record (Service Locator)',
    rfc: 'RFC 2782',
    category: 'Infrastructure & Zone',
    summary: 'Defines the location (hostname and port number) of servers for specific protocols like SIP, XMPP, or LDAP.',
    description: 'SRV (Service) records eliminate hardcoded port numbers by defining the service name, protocol, priority, weight, port, and target hostname directly within DNS.',
    zoneExample: '_sip._tcp.example.com.    3600    IN    SRV    10 60 5060 bigbox.example.com.',
    defaultTtl: '3600 seconds (1 hour)',
    terminalDig: 'dig +short SRV _sip._tcp.example.com',
    terminalNslookup: 'nslookup -type=SRV _sip._tcp.example.com',
    powershellCommand: 'Resolve-DnsName -Name _sip._tcp.example.com -Type SRV',
    commonUseCases: [
      'VoIP and SIP telephone communication systems',
      'Minecraft gaming servers (`_minecraft._tcp.mc.example.com`)',
      'Active Directory domain controller discovery and Kerberos authentication',
    ],
    configurationAdvice: 'Follow the strict naming convention: `_service._protocol.domain.com` (e.g. `_xmpp-client._tcp.example.com`).',
    commonMistakes: 'Pointing an SRV target to an IP address instead of a resolvable hostname.',
  },
  {
    type: 'SOA',
    slug: 'soa-record',
    name: 'SOA Record (Start of Authority)',
    rfc: 'RFC 1035',
    category: 'Infrastructure & Zone',
    summary: 'Specifies authoritative core parameters for the DNS zone including serial number, primary nameserver, and administrator email.',
    description: 'The SOA (Start of Authority) record marks the beginning of a DNS zone file. It contains the zone serial number (incremented on updates to trigger secondary nameserver replication), refresh, retry, expire, and minimum TTL intervals.',
    zoneExample: 'example.com.    86400    IN    SOA    ns1.cloudflare.com. dns.cloudflare.com. (\n        2026090601 ; serial\n        10000      ; refresh\n        2400       ; retry\n        604800     ; expire\n        1800       ; minimum TTL\n)',
    defaultTtl: '86400 seconds (24 hours)',
    terminalDig: 'dig +short SOA example.com',
    terminalNslookup: 'nslookup -type=SOA example.com',
    powershellCommand: 'Resolve-DnsName -Name example.com -Type SOA',
    commonUseCases: [
      'Controlling zone transfer replication timing between master and slave nameservers',
      'Setting negative caching TTL for non-existent domains (NXDOMAIN)',
    ],
    configurationAdvice: 'Always follow the `YYYYMMDDNN` serial format (e.g. `2026090601`) so automated scripts and secondary nameservers can determine when zones have been modified.',
    commonMistakes: 'Forgetting to increment the SOA serial number after making manual zone file changes, preventing secondary nameservers from updating.',
  },
];

export function getAllDnsRecords(): DnsRecordData[] {
  return DNS_RECORDS_DATA;
}

export function getDnsRecordBySlug(slug: string): DnsRecordData | undefined {
  return DNS_RECORDS_DATA.find((r) => r.slug === slug);
}
