export interface GitignoreTemplate {
  slug: string;
  name: string;
  shortName: string;
  category: 'Languages & Frameworks' | 'Operating Systems' | 'IDEs & Editors' | 'DevOps & Cloud';
  description: string;
  summary: string;
  content: string;
  highlightedRules: { pattern: string; explanation: string }[];
  faqs: { question: string; answer: string }[];
}

export const GITIGNORE_TEMPLATES: GitignoreTemplate[] = [
  {
    slug: 'node-gitignore-template',
    name: 'Node.js .gitignore Template',
    shortName: 'Node.js',
    category: 'Languages & Frameworks',
    summary: 'Standard .gitignore for Node.js, npm, yarn, and pnpm projects. Ignores dependencies, runtime logs, build output, and local environment files.',
    description: 'When initializing a Node.js application, committing node_modules or secret environment files to version control causes repository bloat and severe security vulnerabilities. This template isolates all ephemeral cache, dependencies, and environment credentials.',
    content: `# Dependencies
node_modules/
jspm_packages/

# Logs
logs/
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Runtime data
pids/
*.pid
*.seed
*.pid.lock

# Build & compiled output
lib-cov/
coverage/
*.lcov
.nyc_output/
build/Release/
dist/
build/
.dist/

# Environment files
.env
.env.local
.env.development.local
.env.test.local
.env.production.local
*.env

# Framework caches
.next/
out/
.nuxt/
.vuepress/dist/
.serverless/
.fusebox/
.dynamodb/
.tern-port`,
    highlightedRules: [
      { pattern: 'node_modules/', explanation: 'Excludes thousands of downloaded npm dependency files from version control.' },
      { pattern: '.env*.local', explanation: 'Prevents accidentally pushing private API keys, database URLs, and secrets to GitHub.' },
      { pattern: 'dist/ and build/', explanation: 'Transpiled/bundled production assets that are generated dynamically during build steps.' },
      { pattern: '*.log', explanation: 'Ephemeral runtime error logs that change constantly on developer machines.' },
    ],
    faqs: [
      {
        question: 'Should I commit package-lock.json or yarn.lock to git?',
        answer: 'Yes! Always commit package-lock.json, yarn.lock, or pnpm-lock.yaml. They guarantee identical dependency resolution across all team members and CI/CD environments.'
      },
      {
        question: 'How do I ignore an already committed .env file?',
        answer: 'Run: `git rm --cached .env` followed by `git commit -m "Untrack .env"` to remove it from git tracking without deleting your local file.'
      }
    ]
  },
  {
    slug: 'python-gitignore-template',
    name: 'Python .gitignore Template',
    shortName: 'Python',
    category: 'Languages & Frameworks',
    summary: 'Comprehensive Python .gitignore ignoring bytecode (__pycache__), virtual environments (venv, .venv), distribution builds, and test artifacts.',
    description: 'Python generates compiled bytecode files (*.pyc) and ephemeral virtual environment folders. This template keeps your Python repository clean across pip, poetry, conda, pytest, and mypy.',
    content: `# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
venv/
.venv/
env/
ENV/
env.bak/
venv.bak/

# Testing & Coverage
htmlcov/
.tox/
.nox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
*.py,cover
.hypothesis/
.pytest_cache/

# Type checking
.mypy_cache/
.dmypy.json
dmypy.json
.pyre/
.pytype/

# Environment variables
.env
.env.*
!.env.example`,
    highlightedRules: [
      { pattern: '__pycache__/ & *.pyc', explanation: 'Compiled Python bytecode files automatically generated by the CPython interpreter.' },
      { pattern: 'venv/ & .venv/', explanation: 'Local virtual environment containing downloaded pip wheels and packages.' },
      { pattern: '*.egg-info/ & dist/', explanation: 'Packaging build outputs generated by setuptools, flit, or poetry.' },
      { pattern: '.pytest_cache/', explanation: 'Intermediate test cache generated by running pytest.' },
    ],
    faqs: [
      {
        question: 'Should I ever commit the virtualenv directory?',
        answer: 'Never. Virtual environments contain platform-specific compiled binaries that will not work on other operating systems or CI servers. Instead, commit `requirements.txt` or `pyproject.toml`.'
      }
    ]
  },
  {
    slug: 'react-nextjs-gitignore-template',
    name: 'React & Next.js .gitignore Template',
    shortName: 'Next.js & React',
    category: 'Languages & Frameworks',
    summary: 'Tailored .gitignore for Next.js and React web apps. Ignores .next build caches, static exports, Vercel deployments, and local env variables.',
    description: 'Next.js generates a massive `.next` compilation directory, incremental cache chunks, and preview artifacts. This template is optimized for modern Next.js 13/14/15 App Router and Pages Router projects.',
    content: `# Dependencies
/node_modules
/.pnp
.pnp.js

# Testing
/coverage

# Next.js build output
/.next/
/out/

# Production build
/build

# Debug logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Local environment secret files
.env*.local
.env

# Vercel deployment artifacts
.vercel

# TypeScript build info cache
*.tsbuildinfo
next-env.d.ts`,
    highlightedRules: [
      { pattern: '/.next/', explanation: 'Internal compilation cache, server bundles, and route manifests created by Next.js.' },
      { pattern: '.vercel', explanation: 'Local CLI deployment cache containing project IDs and team metadata.' },
      { pattern: '.env*.local', explanation: 'Local overrides for environment secrets.' },
    ],
    faqs: [
      {
        question: 'Should I commit next-env.d.ts?',
        answer: 'Next.js officially advises ignoring or committing `next-env.d.ts`. If ignored, Next.js will regenerate it automatically on `npm run dev` or `npm run build`.'
      }
    ]
  },
  {
    slug: 'golang-gitignore-template',
    name: 'Go (Golang) .gitignore Template',
    shortName: 'Go',
    category: 'Languages & Frameworks',
    summary: 'Clean .gitignore for Go projects ignoring compiled architecture binaries, coverage profiles, and local vendor folders.',
    description: 'Go compiles into standalone native binaries. This template ensures compiled executables (*.exe, *.dll, *.so), test output profiles, and local environment files remain untracked.',
    content: `# Compiled binaries
bin/
pkg/
dist/

# Executables
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binaries & coverage
*.test
*.out
cover.out
coverage.txt

# Go workspace file (if not shared)
go.work

# Vendor folder (omit if using Go modules vendoring)
# vendor/

# Environment files
.env`,
    highlightedRules: [
      { pattern: 'bin/ & *.exe', explanation: 'OS-specific compiled binaries generated by `go build`.' },
      { pattern: '*.test & *.out', explanation: 'Test binary executables and coverage profile outputs from `go test -cover`.' },
    ],
    faqs: [
      {
        question: 'Should I commit the vendor/ directory in Go?',
        answer: 'Since Go 1.14+, `go.mod` and `go.sum` are standard and the `vendor/` directory is usually omitted unless building in an air-gapped network environment.'
      }
    ]
  },
  {
    slug: 'rust-cargo-gitignore-template',
    name: 'Rust & Cargo .gitignore Template',
    shortName: 'Rust',
    category: 'Languages & Frameworks',
    summary: 'Standard .gitignore for Rust projects ignoring the entire /target directory and debug symbol files.',
    description: 'The Rust compiler and Cargo generate gigabytes of intermediate build artifacts, LLVM bitcode, and incremental caches inside the `target/` folder. This template ensures pristine repo size.',
    content: `# Generated by Cargo
/target/

# Local backup files
**/*.rs.bk

# MSVC Windows debug files
*.pdb

# Local environment
.env`,
    highlightedRules: [
      { pattern: '/target/', explanation: 'All intermediate build files, object archives, and release binaries generated by `cargo build`.' },
      { pattern: '*.pdb', explanation: 'Windows program database debug symbol files.' },
    ],
    faqs: [
      {
        question: 'Should I commit Cargo.lock for Rust libraries or binaries?',
        answer: 'Commit `Cargo.lock` for executable applications (binaries/services) to ensure reproducible builds. For shared libraries (crates), omit `Cargo.lock` so consumers get the latest compatible dependency semver.'
      }
    ]
  },
  {
    slug: 'java-maven-gradle-gitignore-template',
    name: 'Java (Maven & Gradle) .gitignore Template',
    shortName: 'Java',
    category: 'Languages & Frameworks',
    summary: 'Standard .gitignore for Java applications built with Apache Maven or Gradle, ignoring target and build directories.',
    description: 'Java builds generate class files (*.class), packed archives (*.jar, *.war), and local build tool caches. This template supports Maven, Gradle, Eclipse, and IntelliJ IDEA.',
    content: `# Compiled class files
*.class

# Log files
*.log

# Package files
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# Virtual machine crash logs
hs_err_pid*
replay_pid*

# Maven target directory
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties

# Gradle build directory
.gradle/
build/
!gradle/wrapper/gradle-wrapper.jar

# IDE files
.idea/
*.iml
.project
.classpath
.settings/`,
    highlightedRules: [
      { pattern: 'target/ & build/', explanation: 'Maven (`target/`) and Gradle (`build/`) compiled output directories.' },
      { pattern: '!gradle/wrapper/gradle-wrapper.jar', explanation: 'Important: Keeps the Gradle wrapper JAR tracked so developers can run `./gradlew` without installing Gradle.' },
    ],
    faqs: [
      {
        question: 'Why should I track gradle-wrapper.jar?',
        answer: 'The Gradle wrapper allows developers and CI/CD pipelines to build the project immediately using `./gradlew` without needing a pre-installed Gradle binary on the host.'
      }
    ]
  },
  {
    slug: 'macos-ds-store-gitignore-template',
    name: 'macOS System Files (.DS_Store) .gitignore Template',
    shortName: 'macOS System',
    category: 'Operating Systems',
    summary: 'Global .gitignore rules for Apple macOS files including .DS_Store, AppleDouble, Spotlight indexing, and icon metadata.',
    description: 'macOS Finder creates invisible `.DS_Store` metadata files in almost every folder you open. Committing these pollutes repositories and generates useless merge conflicts across teams.',
    content: `# General macOS files
.DS_Store
.AppleDouble
.LSOverride

# Icon metadata
Icon\r\r

# Thumbnails and Spotlight
._*
.Spotlight-V100
.Trashes

# Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.TemporaryItems
.VolumeIcon.icns
.com.apple.timemachine.donotpresent`,
    highlightedRules: [
      { pattern: '.DS_Store', explanation: 'Desktop Services Store file containing Finder view settings, icon positions, and window dimensions.' },
      { pattern: '._*', explanation: 'AppleDouble companion file created on non-HFS/APFS filesystems (USB drives, network shares).' },
    ],
    faqs: [
      {
        question: 'Should I put .DS_Store in my project .gitignore or a global gitignore?',
        answer: 'It is best practice to add `.DS_Store` to your global gitignore (`git config --global core.excludesfile ~/.gitignore_global`), but adding it to project gitignores protects Windows and Linux teammates.'
      }
    ]
  },
  {
    slug: 'vscode-jetbrains-ide-gitignore-template',
    name: 'Visual Studio Code & JetBrains IDE .gitignore Template',
    shortName: 'IDEs (VS Code & JetBrains)',
    category: 'IDEs & Editors',
    summary: 'Rules for editor configurations: ignores personal window state and workspace caches while allowing shared team settings.',
    description: 'Developers on a team use different editors (VS Code, Cursor, IntelliJ, WebStorm, PyCharm). This template ignores personal workspace files while optionally keeping shared launch and task configurations.',
    content: `# Visual Studio Code
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
*.code-workspace

# JetBrains (IntelliJ, WebStorm, PyCharm, PhpStorm)
.idea/
*.iws
*.iml
*.ipr
out/

# Sublime Text
*.sublime-workspace
*.sublime-project

# Eclipse
.project
.classpath
.settings/`,
    highlightedRules: [
      { pattern: '!.vscode/settings.json', explanation: 'Whitelists team-shared formatter settings (e.g. Prettier/ESLint on save) while ignoring personal user state.' },
      { pattern: '.idea/', explanation: 'JetBrains editor workspace cache and local indexing files.' },
    ],
    faqs: [
      {
        question: 'Should I commit .vscode/launch.json?',
        answer: 'Yes, if your project provides pre-configured debugging setups (e.g. Node inspect, Python debug, or Docker attach) for the team.'
      }
    ]
  },
  {
    slug: 'terraform-hcl-gitignore-template',
    name: 'Terraform .gitignore Template',
    shortName: 'Terraform',
    category: 'DevOps & Cloud',
    summary: 'Critical .gitignore for HashiCorp Terraform preventing cloud credential leaks (.tfstate, .tfvars) and ignoring provider cache.',
    description: 'Terraform state files (`*.tfstate`) contain sensitive unencrypted secrets (passwords, TLS private keys, IAM tokens). Leaking tfstate files is one of the leading causes of cloud security breaches.',
    content: `# Local .terraform directory (provider plugins & modules)
**/.terraform/*

# .tfstate files contain raw unencrypted secrets!
*.tfstate
*.tfstate.*

# Crash log files
crash.log
crash.*.log

# Exclude all variable files with potential secrets
*.tfvars
*.tfvars.json

# Ignore override files
override.tf
override.tf.json
*_override.tf
*_override.tf.json

# Include fake test vars if desired
!example.tfvars

# CLI configuration files
.terraformrc
terraform.rc`,
    highlightedRules: [
      { pattern: '*.tfstate & *.tfstate.*', explanation: 'CRITICAL SECURITY: Unencrypted state files containing cloud passwords, private keys, and resource IDs.' },
      { pattern: '**/.terraform/*', explanation: 'Downloaded cloud provider plugins (AWS, Azure, GCP) taking up hundreds of megabytes.' },
      { pattern: '*.tfvars', explanation: 'Variable definition files often containing production API keys and database credentials.' },
    ],
    faqs: [
      {
        question: 'Where should Terraform state be stored if not in Git?',
        answer: 'Store state in a secure remote backend with encryption at rest and locking, such as an AWS S3 bucket with DynamoDB locking, Terraform Cloud, or Google Cloud Storage.'
      }
    ]
  },
  {
    slug: 'dockerignore-template',
    name: 'Docker (.dockerignore) Template',
    shortName: 'Docker (.dockerignore)',
    category: 'DevOps & Cloud',
    summary: 'Essential .dockerignore template to speed up docker build context, reduce image size, and prevent leaking .git and .env into container images.',
    description: 'When running `docker build`, the entire directory is sent as build context to the Docker daemon. A proper `.dockerignore` file prevents sending gigabytes of local node_modules or secret credentials into your Docker image layers.',
    content: `# Version control
.git
.gitignore

# Dependencies (install cleanly inside Dockerfile)
node_modules
npm-debug.log

# Secret and local environment files
.env
.env.*
!.env.example

# Build and test outputs
dist
build
coverage
.next
.nuxt

# Docker files
Dockerfile*
docker-compose*
.dockerignore

# IDEs and OS files
.vscode
.idea
.DS_Store
*.log
README.md`,
    highlightedRules: [
      { pattern: '.git', explanation: 'Drastically reduces build context transfer time and prevents exposing commit history inside production images.' },
      { pattern: 'node_modules', explanation: 'Forces `npm ci` to run inside the container for architecture-matching native binary builds (e.g. Linux x86/ARM).' },
      { pattern: '.env*', explanation: 'Prevents accidentally baking production passwords directly into immutable Docker image layers.' },
    ],
    faqs: [
      {
        question: 'What happens if I do not use a .dockerignore file?',
        answer: 'Docker will transfer your entire project directory (including node_modules and .git) over the socket to the build daemon, causing sluggish builds and potentially leaking credentials into public image registries.'
      }
    ]
  }
];

export function getAllGitignoreTemplates(): GitignoreTemplate[] {
  return GITIGNORE_TEMPLATES;
}

export function getGitignoreTemplateBySlug(slug: string): GitignoreTemplate | undefined {
  return GITIGNORE_TEMPLATES.find((t) => t.slug === slug);
}
