export interface HtmlEntityData {
  char: string;
  slug: string;
  name: string;
  namedEntity: string;
  decimalCode: string;
  hexCode: string;
  cssContent: string;
  jsUnicode: string;
  urlEncoded: string;
  category: 'Typography & Punctuation' | 'Currency' | 'Arrows & Pointers' | 'Math & Science' | 'HTML Special Chars' | 'Symbols & Shapes';
  description: string;
}

export const HTML_ENTITIES_DATA: HtmlEntityData[] = [
  // --- HTML Special & Essential Markup ---
  {
    char: '&',
    slug: 'ampersand',
    name: 'Ampersand',
    namedEntity: '&amp;',
    decimalCode: '&#38;',
    hexCode: '&#x26;',
    cssContent: '\\0026',
    jsUnicode: '\\u0026',
    urlEncoded: '%26',
    category: 'HTML Special Chars',
    description: 'The ampersand is the reserved escape character in HTML. Any bare "&" in an HTML document must be written as &amp; to prevent parser errors and XSS vulnerabilities.',
  },
  {
    char: '<',
    slug: 'less-than',
    name: 'Less-Than Sign',
    namedEntity: '&lt;',
    decimalCode: '&#60;',
    hexCode: '&#x3C;',
    cssContent: '\\003C',
    jsUnicode: '\\u003C',
    urlEncoded: '%3C',
    category: 'HTML Special Chars',
    description: 'The less-than sign is reserved in HTML for opening markup tags. In raw text, always use &lt; to ensure browsers do not interpret user input as an HTML element.',
  },
  {
    char: '>',
    slug: 'greater-than',
    name: 'Greater-Than Sign',
    namedEntity: '&gt;',
    decimalCode: '&#62;',
    hexCode: '&#x3E;',
    cssContent: '\\003E',
    jsUnicode: '\\u003E',
    urlEncoded: '%3E',
    category: 'HTML Special Chars',
    description: 'The greater-than sign closes HTML tags. Use &gt; when displaying literal comparison operators in technical content or documentation.',
  },
  {
    char: '"',
    slug: 'double-quote',
    name: 'Double Quotation Mark',
    namedEntity: '&quot;',
    decimalCode: '&#34;',
    hexCode: '&#x22;',
    cssContent: '\\0022',
    jsUnicode: '\\u0022',
    urlEncoded: '%22',
    category: 'HTML Special Chars',
    description: 'Used to enclose HTML attribute values. In HTML attributes (e.g. title="..."), nested double quotes must be escaped with &quot;.',
  },
  {
    char: "'",
    slug: 'single-quote',
    name: 'Single Quotation Mark / Apostrophe',
    namedEntity: '&apos;',
    decimalCode: '&#39;',
    hexCode: '&#x27;',
    cssContent: '\\0027',
    jsUnicode: '\\u0027',
    urlEncoded: '%27',
    category: 'HTML Special Chars',
    description: 'Apostrophe or single quote character. In XML and modern HTML5, &apos; is the standard named entity.',
  },
  {
    char: ' ',
    slug: 'non-breaking-space',
    name: 'Non-Breaking Space (NBSP)',
    namedEntity: '&nbsp;',
    decimalCode: '&#160;',
    hexCode: '&#xA0;',
    cssContent: '\\00A0',
    jsUnicode: '\\u00A0',
    urlEncoded: '%C2%A0',
    category: 'Typography & Punctuation',
    description: 'A space character that prevents automatic line breaks across adjacent words (e.g. between numbers and units like "100 km"). Unlike regular whitespace, multiple &nbsp; entities are not collapsed by browser rendering engines.',
  },

  // --- Legal, Business & Intellectual Property ---
  {
    char: '©',
    slug: 'copyright-symbol',
    name: 'Copyright Symbol',
    namedEntity: '&copy;',
    decimalCode: '&#169;',
    hexCode: '&#xA9;',
    cssContent: '\\00A9',
    jsUnicode: '\\u00A9',
    urlEncoded: '%C2%A9',
    category: 'Symbols & Shapes',
    description: 'The copyright sign (C in a circle) used in copyright notices across web footers and legal terms to declare authorship rights.',
  },
  {
    char: '®',
    slug: 'registered-trademark-symbol',
    name: 'Registered Trademark Symbol',
    namedEntity: '&reg;',
    decimalCode: '&#174;',
    hexCode: '&#xAE;',
    cssContent: '\\00AE',
    jsUnicode: '\\u00AE',
    urlEncoded: '%C2%AE',
    category: 'Symbols & Shapes',
    description: 'The registered trademark symbol provides notice that the preceding mark has been officially registered with a national trademark office.',
  },
  {
    char: '™',
    slug: 'trademark-symbol',
    name: 'Trademark Symbol',
    namedEntity: '&trade;',
    decimalCode: '&#8482;',
    hexCode: '&#x2122;',
    cssContent: '\\2122',
    jsUnicode: '\\u2122',
    urlEncoded: '%E2%84%A2',
    category: 'Symbols & Shapes',
    description: 'The trademark symbol (superscript TM) denotes an unregistered trademark or common law trademark claim.',
  },

  // --- Currencies ---
  {
    char: '$',
    slug: 'dollar-sign',
    name: 'Dollar Sign',
    namedEntity: '&#36;',
    decimalCode: '&#36;',
    hexCode: '&#x24;',
    cssContent: '\\0024',
    jsUnicode: '\\u0024',
    urlEncoded: '%24',
    category: 'Currency',
    description: 'The standard dollar currency symbol used for United States Dollar (USD), Canadian Dollar (CAD), Australian Dollar (AUD), and other currencies.',
  },
  {
    char: '€',
    slug: 'euro-sign',
    name: 'Euro Sign',
    namedEntity: '&euro;',
    decimalCode: '&#8364;',
    hexCode: '&#x20AC;',
    cssContent: '\\20AC',
    jsUnicode: '\\u20AC',
    urlEncoded: '%E2%82%AC',
    category: 'Currency',
    description: 'The official currency symbol for the Eurozone (€). Standardized in Unicode at U+20AC.',
  },
  {
    char: '£',
    slug: 'pound-sterling-sign',
    name: 'Pound Sterling Sign',
    namedEntity: '&pound;',
    decimalCode: '&#163;',
    hexCode: '&#xA3;',
    cssContent: '\\00A3',
    jsUnicode: '\\u00A3',
    urlEncoded: '%C2%A3',
    category: 'Currency',
    description: 'Currency symbol for the British Pound Sterling (GBP).',
  },
  {
    char: '¥',
    slug: 'yen-yuan-sign',
    name: 'Yen / Yuan Sign',
    namedEntity: '&yen;',
    decimalCode: '&#165;',
    hexCode: '&#xA5;',
    cssContent: '\\00A5',
    jsUnicode: '\\u00A5',
    urlEncoded: '%C2%A5',
    category: 'Currency',
    description: 'Currency symbol for the Japanese Yen (JPY) and Chinese Yuan (CNY).',
  },
  {
    char: '¢',
    slug: 'cent-sign',
    name: 'Cent Sign',
    namedEntity: '&cent;',
    decimalCode: '&#162;',
    hexCode: '&#xA2;',
    cssContent: '\\00A2',
    jsUnicode: '\\u00A2',
    urlEncoded: '%C2%A2',
    category: 'Currency',
    description: 'Fractional currency symbol representing one one-hundredth of a dollar or peso.',
  },

  // --- Typography & Punctuation ---
  {
    char: '—',
    slug: 'em-dash',
    name: 'Em Dash',
    namedEntity: '&mdash;',
    decimalCode: '&#8212;',
    hexCode: '&#x2014;',
    cssContent: '\\2014',
    jsUnicode: '\\u2014',
    urlEncoded: '%E2%80%94',
    category: 'Typography & Punctuation',
    description: 'The em dash is a long typographical horizontal bar equal to the width of the letter "M". Used to create a strong pause, parenthetical statement, or abrupt change of thought.',
  },
  {
    char: '–',
    slug: 'en-dash',
    name: 'En Dash',
    namedEntity: '&ndash;',
    decimalCode: '&#8211;',
    hexCode: '&#x2013;',
    cssContent: '\\2013',
    jsUnicode: '\\u2013',
    urlEncoded: '%E2%80%93',
    category: 'Typography & Punctuation',
    description: 'The en dash is equal to the width of the letter "N", half the width of an em dash. Typographically standard for numeric and date ranges (e.g. 2020–2026, pp. 14–28).',
  },
  {
    char: '•',
    slug: 'bullet-point',
    name: 'Bullet Point',
    namedEntity: '&bull;',
    decimalCode: '&#8226;',
    hexCode: '&#x2022;',
    cssContent: '\\2022',
    jsUnicode: '\\u2022',
    urlEncoded: '%E2%80%A2',
    category: 'Typography & Punctuation',
    description: 'Standard centered black circular dot used for unordered lists, breadcrumbs, and separator badges in web design.',
  },
  {
    char: '…',
    slug: 'horizontal-ellipsis',
    name: 'Horizontal Ellipsis',
    namedEntity: '&hellip;',
    decimalCode: '&#8230;',
    hexCode: '&#x2026;',
    cssContent: '\\2026',
    jsUnicode: '\\u2026',
    urlEncoded: '%E2%80%A6',
    category: 'Typography & Punctuation',
    description: 'A single typographical glyph containing three evenly spaced dots, preferred over three consecutive periods (...) for optimal kerning.',
  },
  {
    char: '§',
    slug: 'section-sign',
    name: 'Section Sign',
    namedEntity: '&sect;',
    decimalCode: '&#167;',
    hexCode: '&#xA7;',
    cssContent: '\\00A7',
    jsUnicode: '\\u00A7',
    urlEncoded: '%C2%A7',
    category: 'Typography & Punctuation',
    description: 'Typographical glyph used to reference numbered sections in legal documents, statute codes, and bylaws (e.g. § 104(a)).',
  },
  {
    char: '¶',
    slug: 'pilcrow-paragraph-sign',
    name: 'Pilcrow / Paragraph Sign',
    namedEntity: '&para;',
    decimalCode: '&#182;',
    hexCode: '&#xB6;',
    cssContent: '\\00B6',
    jsUnicode: '\\u00B6',
    urlEncoded: '%C2%B6',
    category: 'Typography & Punctuation',
    description: 'The pilcrow mark denotes a paragraph boundary or section break in editorial proofreading and typography.',
  },

  // --- Arrows & Directions ---
  {
    char: '→',
    slug: 'rightwards-arrow',
    name: 'Rightwards Arrow',
    namedEntity: '&rarr;',
    decimalCode: '&#8594;',
    hexCode: '&#x2192;',
    cssContent: '\\2192',
    jsUnicode: '\\u2192',
    urlEncoded: '%E2%86%92',
    category: 'Arrows & Pointers',
    description: 'Standard right-pointing arrow symbol widely used in UI buttons ("Next &rarr;"), breadcrumbs, and data pipelines.',
  },
  {
    char: '←',
    slug: 'leftwards-arrow',
    name: 'Leftwards Arrow',
    namedEntity: '&larr;',
    decimalCode: '&#8592;',
    hexCode: '&#x2190;',
    cssContent: '\\2190',
    jsUnicode: '\\u2190',
    urlEncoded: '%E2%86%90',
    category: 'Arrows & Pointers',
    description: 'Standard left-pointing arrow symbol for navigation back buttons and undo actions.',
  },
  {
    char: '↑',
    slug: 'upwards-arrow',
    name: 'Upwards Arrow',
    namedEntity: '&uarr;',
    decimalCode: '&#8593;',
    hexCode: '&#x2191;',
    cssContent: '\\2191',
    jsUnicode: '\\u2191',
    urlEncoded: '%E2%86%91',
    category: 'Arrows & Pointers',
    description: 'Upwards pointing arrow for scroll-to-top buttons, positive growth trends, and upload actions.',
  },
  {
    char: '↓',
    slug: 'downwards-arrow',
    name: 'Downwards Arrow',
    namedEntity: '&darr;',
    decimalCode: '&#8595;',
    hexCode: '&#x2193;',
    cssContent: '\\2193',
    jsUnicode: '\\u2193',
    urlEncoded: '%E2%86%93',
    category: 'Arrows & Pointers',
    description: 'Downwards pointing arrow for dropdown menus, negative trends, and download actions.',
  },
  {
    char: '⇄',
    slug: 'left-right-arrows-swap',
    name: 'Left Right Arrows (Swap)',
    namedEntity: '&#8644;',
    decimalCode: '&#8644;',
    hexCode: '&#x21C4;',
    cssContent: '\\21C4',
    jsUnicode: '\\u21C4',
    urlEncoded: '%E2%87%84',
    category: 'Arrows & Pointers',
    description: 'Paired horizontal reciprocal swap arrows used for two-way currency conversion, unit switching, and code format swapping.',
  },

  // --- Math & Science ---
  {
    char: '×',
    slug: 'multiplication-sign',
    name: 'Multiplication Sign',
    namedEntity: '&times;',
    decimalCode: '&#215;',
    hexCode: '&#xD7;',
    cssContent: '\\00D7',
    jsUnicode: '\\u00D7',
    urlEncoded: '%C3%97',
    category: 'Math & Science',
    description: 'The mathematical cross operator used for multiplication, screen resolutions (e.g. 1920×1080), dimensions, and close modal buttons ("X").',
  },
  {
    char: '÷',
    slug: 'division-sign',
    name: 'Division Sign (Obelus)',
    namedEntity: '&divide;',
    decimalCode: '&#247;',
    hexCode: '&#xF7;',
    cssContent: '\\00F7',
    jsUnicode: '\\u00F7',
    urlEncoded: '%C3%B7',
    category: 'Math & Science',
    description: 'The standard arithmetic division operator symbol.',
  },
  {
    char: '±',
    slug: 'plus-minus-sign',
    name: 'Plus-Minus Sign',
    namedEntity: '&plusmn;',
    decimalCode: '&#177;',
    hexCode: '&#xB1;',
    cssContent: '\\00B1',
    jsUnicode: '\\u00B1',
    urlEncoded: '%C2%B1',
    category: 'Math & Science',
    description: 'Mathematical symbol representing both positive and negative quantities or confidence margins of error (e.g. 50 ± 2%).',
  },
  {
    char: '°',
    slug: 'degree-symbol',
    name: 'Degree Symbol',
    namedEntity: '&deg;',
    decimalCode: '&#176;',
    hexCode: '&#xB0;',
    cssContent: '\\00B0',
    jsUnicode: '\\u00B0',
    urlEncoded: '%C2%B0',
    category: 'Math & Science',
    description: 'Used for temperature measurements (e.g. 25°C, 77°F), geographic coordinates (latitude/longitude), and geometric angles (90°).',
  },
  {
    char: '≠',
    slug: 'not-equal-to',
    name: 'Not Equal To Sign',
    namedEntity: '&ne;',
    decimalCode: '&#8800;',
    hexCode: '&#x2260;',
    cssContent: '\\2260',
    jsUnicode: '\\u2260',
    urlEncoded: '%E2%89%A0',
    category: 'Math & Science',
    description: 'Mathematical relational operator indicating inequality between two values.',
  },
  {
    char: '≈',
    slug: 'almost-equal-to',
    name: 'Almost Equal To / Approximately',
    namedEntity: '&asymp;',
    decimalCode: '&#8776;',
    hexCode: '&#x2248;',
    cssContent: '\\2248',
    jsUnicode: '\\u2248',
    urlEncoded: '%E2%89%88',
    category: 'Math & Science',
    description: 'Double wavy tilde symbol denoting approximate equality or rounding.',
  },
  {
    char: '∞',
    slug: 'infinity-symbol',
    name: 'Infinity Symbol (Lemniscate)',
    namedEntity: '&infin;',
    decimalCode: '&#8734;',
    hexCode: '&#x221E;',
    cssContent: '\\221E',
    jsUnicode: '\\u221E',
    urlEncoded: '%E2%88%9E',
    category: 'Math & Science',
    description: 'The horizontal figure-eight symbol representing the concept of unbounded quantity or infinite cycles.',
  },
  {
    char: 'π',
    slug: 'pi-symbol',
    name: 'Greek Small Letter Pi',
    namedEntity: '&pi;',
    decimalCode: '&#960;',
    hexCode: '&#x3C0;',
    cssContent: '\\03C0',
    jsUnicode: '\\u03C0',
    urlEncoded: '%CF%80',
    category: 'Math & Science',
    description: 'The mathematical constant representing the ratio of a circle\'s circumference to its diameter (approximately 3.14159).',
  },
  {
    char: 'µ',
    slug: 'micro-sign',
    name: 'Micro Sign / Micron',
    namedEntity: '&micro;',
    decimalCode: '&#181;',
    hexCode: '&#xB5;',
    cssContent: '\\00B5',
    jsUnicode: '\\u00B5',
    urlEncoded: '%C2%B5',
    category: 'Math & Science',
    description: 'SI unit prefix multiplier representing one millionth (10⁻⁶), such as microseconds (µs) or micrometers (µm).',
  },

  // --- Symbols & Checks ---
  {
    char: '✓',
    slug: 'checkmark-tick',
    name: 'Checkmark / Tick',
    namedEntity: '&check;',
    decimalCode: '&#10003;',
    hexCode: '&#x2713;',
    cssContent: '\\2713',
    jsUnicode: '\\u2713',
    urlEncoded: '%E2%9C%93',
    category: 'Symbols & Shapes',
    description: 'Visual checkmark symbol used to represent verification, task completion, and active options.',
  },
  {
    char: '✔',
    slug: 'heavy-checkmark',
    name: 'Heavy Checkmark',
    namedEntity: '&#10004;',
    decimalCode: '&#10004;',
    hexCode: '&#x2714;',
    cssContent: '\\2714',
    jsUnicode: '\\u2714',
    urlEncoded: '%E2%9C%94',
    category: 'Symbols & Shapes',
    description: 'Bold / heavy checkmark glyph for high-contrast UI status indicators and success alerts.',
  },
  {
    char: '✕',
    slug: 'multiplication-x-mark',
    name: 'Multiplication X / Cross Mark',
    namedEntity: '&#10005;',
    decimalCode: '&#10005;',
    hexCode: '&#x2715;',
    cssContent: '\\2715',
    jsUnicode: '\\u2715',
    urlEncoded: '%E2%9C%95',
    category: 'Symbols & Shapes',
    description: 'Standard cross mark (X) for dismiss buttons, error badges, and rejected options.',
  },
  {
    char: '♥',
    slug: 'black-heart-suit',
    name: 'Heart Symbol',
    namedEntity: '&hearts;',
    decimalCode: '&#9829;',
    hexCode: '&#x2665;',
    cssContent: '\\2665',
    jsUnicode: '\\u2665',
    urlEncoded: '%E2%99%A5',
    category: 'Symbols & Shapes',
    description: 'The solid heart card suit symbol, universally used in web footers ("Made with ♥") and social like reactions.',
  },
  {
    char: '★',
    slug: 'black-star',
    name: 'Solid Star Symbol',
    namedEntity: '&#9733;',
    decimalCode: '&#9733;',
    hexCode: '&#x2605;',
    cssContent: '\\2605',
    jsUnicode: '\\u2605',
    urlEncoded: '%E2%98%85',
    category: 'Symbols & Shapes',
    description: 'Five-pointed solid star symbol used for rating displays (e.g. ★★★★★ 5.0), favorites, and GitHub repo stars.',
  },
  {
    char: '☆',
    slug: 'white-star-outline',
    name: 'Star Outline Symbol',
    namedEntity: '&#9734;',
    decimalCode: '&#9734;',
    hexCode: '&#x2606;',
    cssContent: '\\2606',
    jsUnicode: '\\u2606',
    urlEncoded: '%E2%98%86',
    category: 'Symbols & Shapes',
    description: 'Outlined five-pointed star representing unselected or empty rating values.',
  },
];

export function getAllHtmlEntities(): HtmlEntityData[] {
  return HTML_ENTITIES_DATA;
}

export function getHtmlEntityBySlug(slug: string): HtmlEntityData | undefined {
  return HTML_ENTITIES_DATA.find((e) => e.slug === slug);
}
