export interface MimeData {
  mime: string;
  slug: string;
  name: string;
  category: 'Application' | 'Image' | 'Text' | 'Audio' | 'Video' | 'Font' | 'Multipart';
  extensions: string[];
  description: string;
  httpHeader: string;
  nginxConfig: string;
  apacheConfig: string;
  securityNote: string;
  exampleSnippet: string;
}

export const MIME_DATA: MimeData[] = [
  // --- Application ---
  {
    mime: 'application/json',
    slug: 'application-json',
    name: 'JSON (JavaScript Object Notation)',
    category: 'Application',
    extensions: ['.json'],
    description: 'application/json is the universal MIME type for exchanging structured data in modern REST APIs, GraphQL, and configuration files. Defined in RFC 8259, it does not require a charset parameter as UTF-8 is mandated by default.',
    httpHeader: 'Content-Type: application/json; charset=utf-8',
    nginxConfig: 'types {\n    application/json json;\n}',
    apacheConfig: 'AddType application/json .json',
    securityNote: 'Always validate and parse JSON with safe parsers. Protect against JSON Hijacking / JSON Injection in legacy browsers by ensuring sensitive GET endpoints return objects, not arrays.',
    exampleSnippet: 'res.setHeader("Content-Type", "application/json");\nres.send(JSON.stringify({ status: "success", data: [] }));',
  },
  {
    mime: 'application/pdf',
    slug: 'application-pdf',
    name: 'PDF (Portable Document Format)',
    category: 'Application',
    extensions: ['.pdf'],
    description: 'application/pdf represents Adobe Portable Document Format files. Widely used for invoices, printable reports, whitepapers, and legal contracts across web browsers.',
    httpHeader: 'Content-Type: application/pdf',
    nginxConfig: 'types {\n    application/pdf pdf;\n}',
    apacheConfig: 'AddType application/pdf .pdf',
    securityNote: 'Set "Content-Disposition: inline" to view in browser or "attachment; filename=document.pdf" to force download. PDFs can contain embedded JavaScript; serve untrusted uploads with a sandboxed Content-Security-Policy.',
    exampleSnippet: 'res.setHeader("Content-Type", "application/pdf");\nres.setHeader("Content-Disposition", "inline; filename=report.pdf");',
  },
  {
    mime: 'application/javascript',
    slug: 'application-javascript',
    name: 'JavaScript / ECMAScript',
    category: 'Application',
    extensions: ['.js', '.mjs'],
    description: 'application/javascript is the official IANA standard MIME type for JavaScript source code (superseding text/javascript in RFC 4329, though both are accepted by modern browsers).',
    httpHeader: 'Content-Type: application/javascript; charset=utf-8',
    nginxConfig: 'types {\n    application/javascript js mjs;\n}',
    apacheConfig: 'AddType application/javascript .js .mjs',
    securityNote: 'Always enforce "X-Content-Type-Options: nosniff" to prevent browsers from executing non-JS files masquerading as scripts.',
    exampleSnippet: 'res.setHeader("Content-Type", "application/javascript; charset=utf-8");\nres.setHeader("X-Content-Type-Options", "nosniff");',
  },
  {
    mime: 'application/wasm',
    slug: 'application-wasm',
    name: 'WebAssembly Binary (Wasm)',
    category: 'Application',
    extensions: ['.wasm'],
    description: 'application/wasm is the required MIME type for streaming WebAssembly binaries. WebAssembly.instantiateStreaming() strictly rejects any response that does not send application/wasm.',
    httpHeader: 'Content-Type: application/wasm',
    nginxConfig: 'types {\n    application/wasm wasm;\n}',
    apacheConfig: 'AddType application/wasm .wasm',
    securityNote: 'Browsers require the exact "application/wasm" Content-Type header to compile WebAssembly in background threads without blocking the main UI thread.',
    exampleSnippet: 'const { instance } = await WebAssembly.instantiateStreaming(fetch("/module.wasm"));',
  },
  {
    mime: 'application/xml',
    slug: 'application-xml',
    name: 'XML (Extensible Markup Language)',
    category: 'Application',
    extensions: ['.xml'],
    description: 'application/xml is used for XML documents, SOAP APIs, RSS/Atom feeds, and XML sitemaps.',
    httpHeader: 'Content-Type: application/xml; charset=utf-8',
    nginxConfig: 'types {\n    application/xml xml;\n}',
    apacheConfig: 'AddType application/xml .xml',
    securityNote: 'CRITICAL: Disable external entity resolution (XXE protection) in your XML parser to prevent arbitrary local file disclosure and SSRF attacks.',
    exampleSnippet: 'res.setHeader("Content-Type", "application/xml; charset=utf-8");\nres.send("<response><status>ok</status></response>");',
  },
  {
    mime: 'application/zip',
    slug: 'application-zip',
    name: 'ZIP Archive',
    category: 'Application',
    extensions: ['.zip'],
    description: 'application/zip denotes standard PKZIP compressed file archives.',
    httpHeader: 'Content-Type: application/zip',
    nginxConfig: 'types {\n    application/zip zip;\n}',
    apacheConfig: 'AddType application/zip .zip',
    securityNote: 'Protect decompression routines against "Zip Slip" directory traversal attacks (`../../`) and Zip Bomb denial-of-service files.',
    exampleSnippet: 'res.setHeader("Content-Type", "application/zip");\nres.setHeader("Content-Disposition", "attachment; filename=archive.zip");',
  },
  {
    mime: 'application/octet-stream',
    slug: 'application-octet-stream',
    name: 'Binary Data / Arbitrary Byte Stream',
    category: 'Application',
    extensions: ['.bin', '.exe', '.dll', '.iso'],
    description: 'application/octet-stream is the RFC 2046 fallback MIME type for unknown binary files. Web browsers typically prompt the user to download the file rather than rendering it.',
    httpHeader: 'Content-Type: application/octet-stream',
    nginxConfig: 'default_type application/octet-stream;',
    apacheConfig: 'DefaultType application/octet-stream',
    securityNote: 'Never serve user-uploaded untrusted files as HTML/SVG; fallback to application/octet-stream with "Content-Disposition: attachment" to eliminate stored XSS risks.',
    exampleSnippet: 'res.setHeader("Content-Type", "application/octet-stream");\nres.setHeader("Content-Disposition", "attachment; filename=data.bin");',
  },

  // --- Images ---
  {
    mime: 'image/webp',
    slug: 'image-webp',
    name: 'WebP Image',
    category: 'Image',
    extensions: ['.webp'],
    description: 'image/webp is Google\'s modern web image format providing both lossy and lossless compression with alpha transparency. WebP files are typically 25–34% smaller than comparable JPEGs and PNGs.',
    httpHeader: 'Content-Type: image/webp',
    nginxConfig: 'types {\n    image/webp webp;\n}',
    apacheConfig: 'AddType image/webp .webp',
    securityNote: 'Ensure your web server caches WebP aggressively (`Cache-Control: public, max-age=31536000, immutable`).',
    exampleSnippet: '<picture>\n  <source srcset="photo.webp" type="image/webp">\n  <img src="photo.jpg" alt="Optimized Photo">\n</picture>',
  },
  {
    mime: 'image/svg+xml',
    slug: 'image-svg-xml',
    name: 'SVG (Scalable Vector Graphics)',
    category: 'Image',
    extensions: ['.svg'],
    description: 'image/svg+xml is the XML-based vector graphics format for two-dimensional interactive graphics, icons, and logos.',
    httpHeader: 'Content-Type: image/svg+xml',
    nginxConfig: 'types {\n    image/svg+xml svg svgz;\n}',
    apacheConfig: 'AddType image/svg+xml .svg',
    securityNote: 'CRITICAL SECURITY: SVGs can contain `<script>` tags and onload event handlers. If users upload SVGs, sanitize them thoroughly (e.g. with DOMPurify) or serve them from an isolated domain with `Content-Security-Policy: default-src \'none\'`.',
    exampleSnippet: 'res.setHeader("Content-Type", "image/svg+xml");\nres.setHeader("Content-Security-Policy", "default-src \'none\'");',
  },
  {
    mime: 'image/png',
    slug: 'image-png',
    name: 'PNG (Portable Network Graphics)',
    category: 'Image',
    extensions: ['.png'],
    description: 'image/png is the standard raster graphics format supporting lossless data compression and full 8-bit alpha transparency.',
    httpHeader: 'Content-Type: image/png',
    nginxConfig: 'types {\n    image/png png;\n}',
    apacheConfig: 'AddType image/png .png',
    securityNote: 'PNG files have magic bytes: `89 50 4E 47 0D 0A 1A 0A`. Validate these magic numbers during file upload verification rather than trusting user-submitted extensions.',
    exampleSnippet: 'res.setHeader("Content-Type", "image/png");\nfs.createReadStream("logo.png").pipe(res);',
  },
  {
    mime: 'image/jpeg',
    slug: 'image-jpeg',
    name: 'JPEG / JPG Image',
    category: 'Image',
    extensions: ['.jpg', '.jpeg'],
    description: 'image/jpeg is the most universally supported lossy compression format for digital photographs and realistic images.',
    httpHeader: 'Content-Type: image/jpeg',
    nginxConfig: 'types {\n    image/jpeg jpeg jpg;\n}',
    apacheConfig: 'AddType image/jpeg .jpg .jpeg',
    securityNote: 'Strip EXIF metadata (GPS location coordinates, camera serial numbers) from uploaded images to protect user privacy.',
    exampleSnippet: 'res.setHeader("Content-Type", "image/jpeg");\nres.setHeader("Cache-Control", "public, max-age=31536000, immutable");',
  },
  {
    mime: 'image/avif',
    slug: 'image-avif',
    name: 'AVIF Image (AV1 Still Image File Format)',
    category: 'Image',
    extensions: ['.avif'],
    description: 'image/avif is the next-generation image codec derived from AV1 video frames. Delivers up to 50% better compression efficiency than JPEG with HDR and wide color gamut support.',
    httpHeader: 'Content-Type: image/avif',
    nginxConfig: 'types {\n    image/avif avif;\n}',
    apacheConfig: 'AddType image/avif .avif',
    securityNote: 'Ensure Nginx and Apache mime.types mappings are updated to recognize `.avif` files to prevent browsers from downloading them as octet-stream.',
    exampleSnippet: '<picture>\n  <source srcset="hero.avif" type="image/avif">\n  <source srcset="hero.webp" type="image/webp">\n  <img src="hero.jpg" alt="Hero">\n</picture>',
  },

  // --- Text ---
  {
    mime: 'text/html',
    slug: 'text-html',
    name: 'HTML (HyperText Markup Language)',
    category: 'Text',
    extensions: ['.html', '.htm'],
    description: 'text/html is the foundational MIME type of the World Wide Web, telling browsers to interpret the payload as an interactive DOM document.',
    httpHeader: 'Content-Type: text/html; charset=utf-8',
    nginxConfig: 'types {\n    text/html html htm;\n}',
    apacheConfig: 'AddType text/html .html',
    securityNote: 'Always specify charset=utf-8 to prevent UTF-7 XSS vulnerabilities. Enforce Content-Security-Policy (CSP) headers to block malicious script execution.',
    exampleSnippet: 'res.setHeader("Content-Type", "text/html; charset=utf-8");\nres.send("<!DOCTYPE html><html><body><h1>Hello World</h1></body></html>");',
  },
  {
    mime: 'text/css',
    slug: 'text-css',
    name: 'CSS (Cascading Style Sheets)',
    category: 'Text',
    extensions: ['.css'],
    description: 'text/css instructs browsers to parse the file as styling rules. In strict mode, modern browsers will refuse to load stylesheets with non-text/css MIME types.',
    httpHeader: 'Content-Type: text/css; charset=utf-8',
    nginxConfig: 'types {\n    text/css css;\n}',
    apacheConfig: 'AddType text/css .css',
    securityNote: 'With `X-Content-Type-Options: nosniff`, browsers will strictly refuse to apply stylesheets that do not match `text/css`.',
    exampleSnippet: 'res.setHeader("Content-Type", "text/css; charset=utf-8");\nres.setHeader("X-Content-Type-Options", "nosniff");',
  },
  {
    mime: 'text/csv',
    slug: 'text-csv',
    name: 'CSV (Comma-Separated Values)',
    category: 'Text',
    extensions: ['.csv'],
    description: 'text/csv is the IANA MIME type for tabular data formatted with comma delimiters as defined in RFC 4180.',
    httpHeader: 'Content-Type: text/csv; charset=utf-8',
    nginxConfig: 'types {\n    text/csv csv;\n}',
    apacheConfig: 'AddType text/csv .csv',
    securityNote: 'Guard against CSV/Formula Injection: Cells beginning with `=, +, -, @` can trigger arbitrary command execution when opened in Microsoft Excel or Google Sheets. Prefix untrusted cells with a single quote (`\').',
    exampleSnippet: 'res.setHeader("Content-Type", "text/csv; charset=utf-8");\nres.setHeader("Content-Disposition", "attachment; filename=export.csv");',
  },
  {
    mime: 'text/markdown',
    slug: 'text-markdown',
    name: 'Markdown Document',
    category: 'Text',
    extensions: ['.md', '.markdown'],
    description: 'text/markdown is defined in RFC 7763 for plain text documents utilizing Markdown formatting syntax.',
    httpHeader: 'Content-Type: text/markdown; charset=utf-8',
    nginxConfig: 'types {\n    text/markdown md markdown;\n}',
    apacheConfig: 'AddType text/markdown .md',
    securityNote: 'When rendering Markdown to HTML, always pass it through a sanitizer (like DOMPurify) to neutralize malicious `<script>` or `javascript:` links.',
    exampleSnippet: 'res.setHeader("Content-Type", "text/markdown; charset=utf-8");\nres.send("# DevTransform Documentation\\n\\nWelcome to the API.");',
  },

  // --- Fonts ---
  {
    mime: 'font/woff2',
    slug: 'font-woff2',
    name: 'WOFF2 (Web Open Font Format 2.0)',
    category: 'Font',
    extensions: ['.woff2'],
    description: 'font/woff2 is the recommended W3C font format for the web, utilizing Brotli compression to achieve ~30% smaller file sizes than WOFF 1.0.',
    httpHeader: 'Content-Type: font/woff2',
    nginxConfig: 'types {\n    font/woff2 woff2;\n}',
    apacheConfig: 'AddType font/woff2 .woff2',
    securityNote: 'Ensure CORS headers (`Access-Control-Allow-Origin: *`) are present if web fonts are loaded across subdomains or CDNs.',
    exampleSnippet: '@font-face {\n  font-family: "CustomSans";\n  src: url("/fonts/sans.woff2") format("woff2");\n  font-display: swap;\n}',
  },

  // --- Video & Audio ---
  {
    mime: 'video/mp4',
    slug: 'video-mp4',
    name: 'MP4 Video (MPEG-4 Part 14)',
    category: 'Video',
    extensions: ['.mp4'],
    description: 'video/mp4 is the universally supported digital multimedia container format for H.264/AVC or H.265/HEVC video with AAC audio.',
    httpHeader: 'Content-Type: video/mp4',
    nginxConfig: 'types {\n    video/mp4 mp4;\n}',
    apacheConfig: 'AddType video/mp4 .mp4',
    securityNote: 'Servers must support HTTP Byte-Range requests (`Accept-Ranges: bytes`) to allow video seeking in HTML5 `<video>` players.',
    exampleSnippet: '<video controls preload="metadata">\n  <source src="clip.mp4" type="video/mp4">\n</video>',
  },
  {
    mime: 'audio/mpeg',
    slug: 'audio-mpeg',
    name: 'MP3 Audio (MPEG Audio Layer III)',
    category: 'Audio',
    extensions: ['.mp3'],
    description: 'audio/mpeg is the standard MIME type for MP3 compressed digital audio tracks and podcast streams.',
    httpHeader: 'Content-Type: audio/mpeg',
    nginxConfig: 'types {\n    audio/mpeg mp3;\n}',
    apacheConfig: 'AddType audio/mpeg .mp3',
    securityNote: 'Include `Accept-Ranges: bytes` header for streaming support.',
    exampleSnippet: '<audio controls>\n  <source src="track.mp3" type="audio/mpeg">\n</audio>',
  },

  // --- Multipart & Forms ---
  {
    mime: 'multipart/form-data',
    slug: 'multipart-form-data',
    name: 'Multipart Form Data (File Uploads)',
    category: 'Multipart',
    extensions: [],
    description: 'multipart/form-data is used in HTTP POST requests when submitting HTML forms containing file uploads (`<input type="file">`). Each form field is separated by a unique boundary delimiter string.',
    httpHeader: 'Content-Type: multipart/form-data; boundary=---------------------------974767299852498929531610575',
    nginxConfig: 'client_max_body_size 50M;',
    apacheConfig: 'LimitRequestBody 52428800',
    securityNote: 'Limit maximum request body size (`client_max_body_size`) and strictly validate MIME type and magic bytes on server-side to prevent malicious file execution.',
    exampleSnippet: '<form action="/api/upload" method="POST" enctype="multipart/form-data">\n  <input type="file" name="avatar">\n  <button type="submit">Upload</button>\n</form>',
  },
  {
    mime: 'application/x-www-form-urlencoded',
    slug: 'application-x-www-form-urlencoded',
    name: 'URL-Encoded Form Data',
    category: 'Application',
    extensions: [],
    description: 'application/x-www-form-urlencoded is the default encoding for standard HTML form submissions, formatting key-value pairs as query parameters separated by `&` with percent-encoding.',
    httpHeader: 'Content-Type: application/x-www-form-urlencoded; charset=utf-8',
    nginxConfig: '# Default handled by standard HTTP parser',
    apacheConfig: '# Standard HTTP parser',
    securityNote: 'Always sanitize form values against SQL injection and Cross-Site Scripting (XSS).',
    exampleSnippet: 'fetch("/api/login", {\n  method: "POST",\n  headers: { "Content-Type": "application/x-www-form-urlencoded" },\n  body: new URLSearchParams({ username: "alice", role: "admin" })\n});',
  },
];

export function getAllMimes(): MimeData[] {
  return MIME_DATA;
}

export function getMimeBySlug(slug: string): MimeData | undefined {
  return MIME_DATA.find((m) => m.slug === slug);
}
