export interface PortData {
  port: number;
  slug: string;
  name: string;
  service: string;
  protocol: 'TCP' | 'UDP' | 'TCP/UDP';
  category: 'Web & Dev' | 'Database' | 'DevOps & Cloud' | 'Networking' | 'Messaging & Cache' | 'Security';
  description: string;
  defaultProcess: string;
  riskLevel: 'Low' | 'Medium' | 'High' | 'Critical';
  securityNote: string;
  killCommandLinux: string;
  killCommandWin: string;
  checkCommandLinux: string;
  checkCommandWin: string;
  firewallUfw: string;
  dockerRun: string;
  commonError: string;
}

export const PORTS_DATA: PortData[] = [
  // --- Web & Dev Servers ---
  {
    port: 3000,
    slug: 'port-3000',
    name: 'Port 3000',
    service: 'React / Next.js / Node.js Dev Server',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 3000 is the industry-standard default local development port for Node.js applications, Create React App, Next.js, Express, and Ruby on Rails. When starting a local development server, this is usually the primary listener.',
    defaultProcess: 'node, npm, next-server',
    riskLevel: 'Low',
    securityNote: 'Never expose port 3000 to 0.0.0.0 on production servers without a reverse proxy (like NGINX or Caddy) handling SSL/TLS encryption and rate limiting.',
    killCommandLinux: 'kill -9 $(lsof -t -i:3000)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 3000).OwningProcess -Force',
    checkCommandLinux: 'lsof -i :3000 || ss -tulpn | grep 3000',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 3000',
    firewallUfw: 'sudo ufw allow 3000/tcp',
    dockerRun: 'docker run -p 3000:3000 -d my-node-app',
    commonError: 'Error: listen EADDRINUSE: address already in use :::3000',
  },
  {
    port: 8080,
    slug: 'port-8080',
    name: 'Port 8080',
    service: 'HTTP Alternate / Tomcat / Spring Boot / Vue CLI',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 8080 is the standard HTTP alternate port used by Apache Tomcat, Spring Boot, Vue CLI, Jenkins, and proxy services. It provides unprivileged HTTP serving without requiring root/admin access.',
    defaultProcess: 'java, node, jenkins',
    riskLevel: 'Medium',
    securityNote: 'Frequently targeted by automated scanners looking for exposed Tomcat management dashboards, Jenkins instances, or proxy misconfigurations.',
    killCommandLinux: 'kill -9 $(lsof -t -i:8080)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 8080).OwningProcess -Force',
    checkCommandLinux: 'lsof -i :8080 || ss -tulpn | grep 8080',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 8080',
    firewallUfw: 'sudo ufw allow 8080/tcp',
    dockerRun: 'docker run -p 8080:8080 -d my-spring-app',
    commonError: 'Web server failed to start. Port 8080 was already in use.',
  },
  {
    port: 5173,
    slug: 'port-5173',
    name: 'Port 5173',
    service: 'Vite Dev Server (Vue, Svelte, React)',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 5173 is the default port assigned by the Vite build tool and development server for modern frontend frameworks (Vue 3, Svelte, React, Solid).',
    defaultProcess: 'vite, node',
    riskLevel: 'Low',
    securityNote: 'Local development server. If Vite switches to 5174 or 5175, an existing Vite or background process is still bound to 5173.',
    killCommandLinux: 'kill -9 $(lsof -t -i:5173)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 5173).OwningProcess -Force',
    checkCommandLinux: 'lsof -i :5173',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 5173',
    firewallUfw: 'sudo ufw allow 5173/tcp',
    dockerRun: 'docker run -p 5173:5173 -d my-vite-app',
    commonError: 'Port 5173 is in use, trying another one... -> http://localhost:5174/',
  },
  {
    port: 80,
    slug: 'port-80',
    name: 'Port 80',
    service: 'HTTP (Hypertext Transfer Protocol)',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 80 is the global IANA standard port for unencrypted World Wide Web (HTTP) traffic. All web browsers default to port 80 when http:// is specified.',
    defaultProcess: 'nginx, apache2, httpd, caddy',
    riskLevel: 'Medium',
    securityNote: 'Traffic is completely unencrypted. Modern security standards mandate redirecting all incoming Port 80 requests to Port 443 (HTTPS) with HSTS headers.',
    killCommandLinux: 'sudo kill -9 $(sudo lsof -t -i:80)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 80).OwningProcess -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep :80',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 80',
    firewallUfw: 'sudo ufw allow 80/tcp',
    dockerRun: 'docker run -p 80:80 -d nginx:alpine',
    commonError: 'nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)',
  },
  {
    port: 443,
    slug: 'port-443',
    name: 'Port 443',
    service: 'HTTPS (HTTP over TLS/SSL)',
    protocol: 'TCP/UDP',
    category: 'Web & Dev',
    description: 'Port 443 is the standard port for encrypted secure web communications (HTTPS) and HTTP/3 (QUIC over UDP). It provides end-to-end cryptographic confidentiality and server identity validation.',
    defaultProcess: 'nginx, apache2, caddy, traefik',
    riskLevel: 'Low',
    securityNote: 'Ensure modern TLS configurations (TLS 1.2/1.3 only, disable SSLv3/TLS 1.0/1.1) and implement automated Let\'s Encrypt certificate renewal.',
    killCommandLinux: 'sudo kill -9 $(sudo lsof -t -i:443)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 443).OwningProcess -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep :443',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 443',
    firewallUfw: 'sudo ufw allow 443/tcp && sudo ufw allow 443/udp',
    dockerRun: 'docker run -p 443:443 -d caddy:alpine',
    commonError: 'Failed to bind to HTTPS port 443. Check TLS certificate permissions.',
  },
  {
    port: 5000,
    slug: 'port-5000',
    name: 'Port 5000',
    service: 'Flask / Python Web / Docker Registry',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 5000 is the default port used by Python Flask, ASP.NET Core, and the official Docker Registry. On macOS Monterey and later, Apple AirPlay Receiver binds to 5000 by default.',
    defaultProcess: 'python, flask, AirPlayXPCHelper',
    riskLevel: 'Low',
    securityNote: 'On macOS, disable "AirPlay Receiver" in System Settings > Sharing if port 5000 causes conflict errors with your Python or Docker servers.',
    killCommandLinux: 'kill -9 $(lsof -t -i:5000)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 5000).OwningProcess -Force',
    checkCommandLinux: 'lsof -i :5000',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 5000',
    firewallUfw: 'sudo ufw allow 5000/tcp',
    dockerRun: 'docker run -p 5000:5000 -d registry:2',
    commonError: 'OSError: [Errno 48] Address already in use (Often macOS AirPlay on port 5000)',
  },
  {
    port: 8000,
    slug: 'port-8000',
    name: 'Port 8000',
    service: 'Django / FastAPI / Python SimpleHTTP',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 8000 is the default development port for Python Django (`python manage.py runserver`), FastAPI (uvicorn), and `python -m http.server 8000`.',
    defaultProcess: 'python, uvicorn, gunicorn',
    riskLevel: 'Low',
    securityNote: 'Django\'s built-in development server is not hardened for production. Never run `runserver` directly on a public internet IP.',
    killCommandLinux: 'kill -9 $(lsof -t -i:8000)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 8000).OwningProcess -Force',
    checkCommandLinux: 'lsof -i :8000',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 8000',
    firewallUfw: 'sudo ufw allow 8000/tcp',
    dockerRun: 'docker run -p 8000:8000 -d my-fastapi-app',
    commonError: 'Error: That port is already in use by another Django or Uvicorn instance.',
  },
  {
    port: 4200,
    slug: 'port-4200',
    name: 'Port 4200',
    service: 'Angular CLI Dev Server',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 4200 is the default port used by Angular CLI (`ng serve`) during frontend application development.',
    defaultProcess: 'node, ng',
    riskLevel: 'Low',
    securityNote: 'Development server only. If 4200 is busy, launch with `ng serve --port 4300`.',
    killCommandLinux: 'kill -9 $(lsof -t -i:4200)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 4200).OwningProcess -Force',
    checkCommandLinux: 'lsof -i :4200',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 4200',
    firewallUfw: 'sudo ufw allow 4200/tcp',
    dockerRun: 'docker run -p 4200:4200 -d my-angular-app',
    commonError: 'Port 4200 is already in use. Use \'--port\' to specify a different port.',
  },
  {
    port: 3001,
    slug: 'port-3001',
    name: 'Port 3001',
    service: 'Secondary Node / Express Backend API',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 3001 is commonly used as the companion backend API port when a React/Next.js frontend occupies port 3000, preventing CORS and port collision issues.',
    defaultProcess: 'node, express',
    riskLevel: 'Low',
    securityNote: 'Ensure proper CORS headers (`Access-Control-Allow-Origin: http://localhost:3000`) are configured between frontend and backend.',
    killCommandLinux: 'kill -9 $(lsof -t -i:3001)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 3001).OwningProcess -Force',
    checkCommandLinux: 'lsof -i :3001',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 3001',
    firewallUfw: 'sudo ufw allow 3001/tcp',
    dockerRun: 'docker run -p 3001:3001 -d my-api',
    commonError: 'Error: listen EADDRINUSE :::3001',
  },

  // --- Databases ---
  {
    port: 5432,
    slug: 'port-5432',
    name: 'Port 5432',
    service: 'PostgreSQL Database',
    protocol: 'TCP',
    category: 'Database',
    description: 'Port 5432 is the official IANA assigned port for the PostgreSQL relational database management system. PostgreSQL servers listen on this port for incoming SQL client connections.',
    defaultProcess: 'postgres, pg_ctl',
    riskLevel: 'High',
    securityNote: 'Never bind PostgreSQL to 0.0.0.0 without strict pg_hba.conf IP whitelisting and SSL connection enforcement (ssl=on). Restrict access to localhost or your VPC subnet.',
    killCommandLinux: 'sudo systemctl stop postgresql || sudo kill -9 $(sudo lsof -t -i:5432)',
    killCommandWin: 'Stop-Service postgresql* -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep 5432 || pg_isready -p 5432',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 5432',
    firewallUfw: 'sudo ufw allow from 10.0.0.0/16 to any port 5432 proto tcp',
    dockerRun: 'docker run -p 5432:5432 -e POSTGRES_PASSWORD=securepass -d postgres:16',
    commonError: 'could not connect to server: Connection refused. Is the server running on host "localhost" and accepting TCP/IP connections on port 5432?',
  },
  {
    port: 3306,
    slug: 'port-3306',
    name: 'Port 3306',
    service: 'MySQL / MariaDB Database',
    protocol: 'TCP',
    category: 'Database',
    description: 'Port 3306 is the default port for MySQL and MariaDB databases worldwide. Client libraries (mysql2, PDO, PyMySQL) default to this port for connections.',
    defaultProcess: 'mysqld, mariadbd',
    riskLevel: 'High',
    securityNote: 'Ensure the root user cannot log in remotely (`bind-address = 127.0.0.1` in my.cnf). Use strong user passwords and disable LOAD DATA LOCAL INFILE.',
    killCommandLinux: 'sudo systemctl stop mysql || sudo kill -9 $(sudo lsof -t -i:3306)',
    killCommandWin: 'Stop-Service MySQL* -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep 3306 || mysqladmin ping',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 3306',
    firewallUfw: 'sudo ufw allow from 192.168.1.0/24 to any port 3306 proto tcp',
    dockerRun: 'docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD=secret -d mysql:8',
    commonError: 'ERROR 2003 (HY000): Can\'t connect to MySQL server on \'127.0.0.1:3306\' (111)',
  },
  {
    port: 27017,
    slug: 'port-27017',
    name: 'Port 27017',
    service: 'MongoDB NoSQL Database',
    protocol: 'TCP',
    category: 'Database',
    description: 'Port 27017 is the default listening port for MongoDB daemon (`mongod`) and routing service (`mongos`).',
    defaultProcess: 'mongod',
    riskLevel: 'Critical',
    securityNote: 'CRITICAL SECURITY RISK: Thousands of unauthenticated MongoDB databases have been ransomed by exposing 27017 to the public internet. Always enable authentication (`security.authorization: enabled`) and bind to 127.0.0.1.',
    killCommandLinux: 'sudo systemctl stop mongod || sudo kill -9 $(sudo lsof -t -i:27017)',
    killCommandWin: 'Stop-Service MongoDB -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep 27017',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 27017',
    firewallUfw: 'sudo ufw deny 27017',
    dockerRun: 'docker run -p 27017:27017 -d mongo:latest',
    commonError: 'MongoNetworkError: failed to connect to server [localhost:27017] on first connect',
  },
  {
    port: 6379,
    slug: 'port-6379',
    name: 'Port 6379',
    service: 'Redis In-Memory Key-Value Store',
    protocol: 'TCP',
    category: 'Messaging & Cache',
    description: 'Port 6379 is the default port for Redis in-memory cache and message broker. The number 6379 corresponds to the letters "MERZ" on a telephone keypad (named after Italian singer Alessia Merz).',
    defaultProcess: 'redis-server',
    riskLevel: 'Critical',
    securityNote: 'CRITICAL: Redis is designed to be accessed by trusted clients inside a secure private network. Publicly exposed Redis instances without passwords (`requirepass`) are regularly compromised by crypto-miners.',
    killCommandLinux: 'sudo systemctl stop redis || sudo kill -9 $(sudo lsof -t -i:6379)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 6379).OwningProcess -Force',
    checkCommandLinux: 'redis-cli ping || sudo ss -tulpn | grep 6379',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 6379',
    firewallUfw: 'sudo ufw deny 6379',
    dockerRun: 'docker run -p 6379:6379 -d redis:alpine redis-server --requirepass securepass',
    commonError: 'Could not connect to Redis at 127.0.0.1:6379: Connection refused',
  },
  {
    port: 1433,
    slug: 'port-1433',
    name: 'Port 1433',
    service: 'Microsoft SQL Server (MS SQL)',
    protocol: 'TCP',
    category: 'Database',
    description: 'Port 1433 is the official standard port assigned for Microsoft SQL Server instances.',
    defaultProcess: 'sqlservr.exe',
    riskLevel: 'High',
    securityNote: 'Frequently targeted by SQL brute-force attacks. Disable the `sa` account or assign a 25+ character random password, and enable SQL Server audit logging.',
    killCommandLinux: 'sudo systemctl stop mssql-server',
    killCommandWin: 'Stop-Service MSSQLSERVER -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep 1433',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 1433',
    firewallUfw: 'sudo ufw allow from 10.0.0.0/8 to any port 1433 proto tcp',
    dockerRun: 'docker run -p 1433:1433 -e ACCEPT_EULA=Y -e SA_PASSWORD=YourStrong@Pass -d mcr.microsoft.com/mssql/server:2022-latest',
    commonError: 'Cannot open database requested by the login. Connection to localhost:1433 failed.',
  },
  {
    port: 1521,
    slug: 'port-1521',
    name: 'Port 1521',
    service: 'Oracle Database Listener',
    protocol: 'TCP',
    category: 'Database',
    description: 'Port 1521 is the default port for the Oracle Database TNS (Transparent Network Substrate) Listener.',
    defaultProcess: 'tnslsnr, oracle',
    riskLevel: 'High',
    securityNote: 'Oracle listeners can reveal database version information and SID names. Implement Valid Node Checking (COST) to restrict unauthorized client hosts.',
    killCommandLinux: 'lsnrctl stop',
    killCommandWin: 'Stop-Service OracleOraDB* -Force',
    checkCommandLinux: 'lsnrctl status',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 1521',
    firewallUfw: 'sudo ufw deny 1521',
    dockerRun: 'docker run -p 1521:1521 -d container-registry.oracle.com/database/free:latest',
    commonError: 'ORA-12541: TNS:no listener on port 1521',
  },
  {
    port: 9200,
    slug: 'port-9200',
    name: 'Port 9200',
    service: 'Elasticsearch / OpenSearch REST API',
    protocol: 'TCP',
    category: 'Database',
    description: 'Port 9200 is used by Elasticsearch and OpenSearch for handling JSON HTTP REST queries, indexing documents, and cluster management.',
    defaultProcess: 'java, elasticsearch',
    riskLevel: 'Critical',
    securityNote: 'Ensure X-Pack security (`xpack.security.enabled: true`) is active. Never expose port 9200 to public internet without basic authentication and TLS.',
    killCommandLinux: 'sudo systemctl stop elasticsearch || sudo kill -9 $(sudo lsof -t -i:9200)',
    killCommandWin: 'Stop-Service elasticsearch -Force',
    checkCommandLinux: 'curl -I http://localhost:9200',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 9200',
    firewallUfw: 'sudo ufw deny 9200',
    dockerRun: 'docker run -p 9200:9200 -e discovery.type=single-node -d elasticsearch:8.10.0',
    commonError: 'Connection refused: could not reach Elasticsearch REST API at localhost:9200',
  },

  // --- DevOps & Cloud & Containers ---
  {
    port: 2375,
    slug: 'port-2375',
    name: 'Port 2375',
    service: 'Docker REST API (Unencrypted)',
    protocol: 'TCP',
    category: 'DevOps & Cloud',
    description: 'Port 2375 is used for unencrypted HTTP communication with the Docker engine daemon.',
    defaultProcess: 'dockerd',
    riskLevel: 'Critical',
    securityNote: 'SEVERE SECURITY HAZARD: Exposing port 2375 without TLS allows anyone with network access to run root-level containers and take over the host operating system. Always use TLS (port 2376) or local UNIX socket `/var/run/docker.sock`.',
    killCommandLinux: 'sudo systemctl stop docker',
    killCommandWin: 'Stop-Service docker -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep 2375',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 2375',
    firewallUfw: 'sudo ufw deny 2375',
    dockerRun: 'dockerd -H tcp://0.0.0.0:2375',
    commonError: 'Cannot connect to the Docker daemon at tcp://localhost:2375. Is the docker daemon running?',
  },
  {
    port: 2376,
    slug: 'port-2376',
    name: 'Port 2376',
    service: 'Docker REST API (TLS Encrypted)',
    protocol: 'TCP',
    category: 'DevOps & Cloud',
    description: 'Port 2376 is the official secure port for Docker daemon API communication using mutual TLS authentication.',
    defaultProcess: 'dockerd',
    riskLevel: 'High',
    securityNote: 'Ensure client certificates are signed by a trusted CA and verified before authorizing any Docker container commands.',
    killCommandLinux: 'sudo systemctl restart docker',
    killCommandWin: 'Restart-Service docker',
    checkCommandLinux: 'sudo ss -tulpn | grep 2376',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 2376',
    firewallUfw: 'sudo ufw allow 2376/tcp',
    dockerRun: 'dockerd --tlsverify --tlscacert=ca.pem --tlscert=server-cert.pem --tlskey=server-key.pem -H tcp://0.0.0.0:2376',
    commonError: 'tls: bad certificate error communicating with Docker daemon on port 2376',
  },
  {
    port: 6443,
    slug: 'port-6443',
    name: 'Port 6443',
    service: 'Kubernetes API Server',
    protocol: 'TCP',
    category: 'DevOps & Cloud',
    description: 'Port 6443 is the default port used by `kube-apiserver` for secure communication within a Kubernetes cluster and for external `kubectl` command management.',
    defaultProcess: 'kube-apiserver',
    riskLevel: 'High',
    securityNote: 'Protect this port with RBAC authorization, audit logging, and never allow anonymous authentication (`--anonymous-auth=false`).',
    killCommandLinux: 'sudo systemctl restart kubelet',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 6443).OwningProcess -Force',
    checkCommandLinux: 'kubectl cluster-info || sudo ss -tulpn | grep 6443',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 6443',
    firewallUfw: 'sudo ufw allow 6443/tcp',
    dockerRun: 'minikube start --apiserver-port=6443',
    commonError: 'Unable to connect to the server: dial tcp 127.0.0.1:6443: connect: connection refused',
  },
  {
    port: 9090,
    slug: 'port-9090',
    name: 'Port 9090',
    service: 'Prometheus Server Web UI & Metrics API',
    protocol: 'TCP',
    category: 'DevOps & Cloud',
    description: 'Port 9090 is the default web UI and PromQL querying interface for the Prometheus monitoring system.',
    defaultProcess: 'prometheus',
    riskLevel: 'Medium',
    securityNote: 'Prometheus does not include native authentication by default. Put it behind an authenticating reverse proxy or enable web configuration basic auth.',
    killCommandLinux: 'kill -9 $(lsof -t -i:9090)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 9090).OwningProcess -Force',
    checkCommandLinux: 'curl -I http://localhost:9090/-/healthy',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 9090',
    firewallUfw: 'sudo ufw allow from 10.0.0.0/8 to any port 9090 proto tcp',
    dockerRun: 'docker run -p 9090:9090 -d prom/prometheus',
    commonError: 'Prometheus server startup failed: address already in use on port 9090',
  },
  {
    port: 11434,
    slug: 'port-11434',
    name: 'Port 11434',
    service: 'Ollama AI / Local LLM Server',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 11434 is the default API port used by Ollama to run large language models (Llama 3, Mistral, Gemma) locally on CPU and GPU.',
    defaultProcess: 'ollama',
    riskLevel: 'Medium',
    securityNote: 'By default, Ollama binds to 127.0.0.1. Do not set OLLAMA_HOST=0.0.0.0 on an untrusted network as it has no authentication and allows downloading and running arbitrary model weights.',
    killCommandLinux: 'kill -9 $(lsof -t -i:11434)',
    killCommandWin: 'Stop-Process -Name "ollama app", "ollama" -Force',
    checkCommandLinux: 'curl http://localhost:11434/api/version',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 11434',
    firewallUfw: 'sudo ufw deny 11434',
    dockerRun: 'docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama',
    commonError: 'could not connect to ollama app on localhost:11434, is it running?',
  },

  // --- Networking & Protocols ---
  {
    port: 22,
    slug: 'port-22',
    name: 'Port 22',
    service: 'SSH (Secure Shell) & SFTP',
    protocol: 'TCP',
    category: 'Networking',
    description: 'Port 22 is the standard port used for Secure Shell (SSH) remote command execution, secure file transfer (SFTP), and Git over SSH (`git@github.com`).',
    defaultProcess: 'sshd',
    riskLevel: 'Critical',
    securityNote: 'Public port 22 is under constant brute-force dictionary attack. Disable password authentication (`PasswordAuthentication no`), disable root login (`PermitRootLogin no`), and install Fail2ban.',
    killCommandLinux: 'sudo systemctl restart sshd',
    killCommandWin: 'Stop-Service sshd -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep :22',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 22',
    firewallUfw: 'sudo ufw allow 22/tcp',
    dockerRun: 'docker run -p 2222:22 -d my-ssh-server',
    commonError: 'ssh: connect to host example.com port 22: Connection refused / Connection timed out',
  },
  {
    port: 53,
    slug: 'port-53',
    name: 'Port 53',
    service: 'DNS (Domain Name System)',
    protocol: 'TCP/UDP',
    category: 'Networking',
    description: 'Port 53 handles Domain Name System queries, translating human-readable hostnames (e.g. google.com) into numeric IP addresses (e.g. 142.250.190.46). UDP is used for standard queries; TCP is used for large zone transfers.',
    defaultProcess: 'named, dnsmasq, systemd-resolved',
    riskLevel: 'High',
    securityNote: 'Open DNS resolvers can be weaponized in massive Distributed Denial of Service (DDoS) DNS amplification attacks. Never leave recursive DNS open to the general internet.',
    killCommandLinux: 'sudo systemctl restart systemd-resolved',
    killCommandWin: 'Stop-Service Dnscache -Force',
    checkCommandLinux: 'dig @localhost google.com || sudo ss -ulpn | grep :53',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 53',
    firewallUfw: 'sudo ufw allow 53',
    dockerRun: 'docker run -p 53:53/udp -p 53:53/tcp -d pihole/pihole',
    commonError: 'listen udp 0.0.0.0:53: bind: address already in use (frequently Ubuntu systemd-resolved)',
  },
  {
    port: 21,
    slug: 'port-21',
    name: 'Port 21',
    service: 'FTP (File Transfer Protocol Control)',
    protocol: 'TCP',
    category: 'Networking',
    description: 'Port 21 is the command control port for standard File Transfer Protocol. Data transfer occurs over port 20 or dynamic passive ports.',
    defaultProcess: 'vsftpd, proftpd, pure-ftpd',
    riskLevel: 'Critical',
    securityNote: 'FTP transmits usernames and passwords in clear text over the wire. Deprecate FTP in favor of SFTP (SSH Port 22) or FTPS with mandatory TLS.',
    killCommandLinux: 'sudo systemctl stop vsftpd',
    killCommandWin: 'Stop-Service ftpsvc -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep :21',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 21',
    firewallUfw: 'sudo ufw deny 21/tcp',
    dockerRun: 'docker run -p 21:21 -d fauria/vsftpd',
    commonError: 'ftp: connect: Connection refused on port 21',
  },
  {
    port: 25,
    slug: 'port-25',
    name: 'Port 25',
    service: 'SMTP (Simple Mail Transfer Protocol)',
    protocol: 'TCP',
    category: 'Networking',
    description: 'Port 25 is used by Mail Transfer Agents (MTA) like Postfix and Sendmail for server-to-server email routing.',
    defaultProcess: 'postfix, sendmail, exim',
    riskLevel: 'Critical',
    securityNote: 'Almost all residential ISPs and cloud providers (AWS EC2, Google Cloud, DigitalOcean) block outbound port 25 to stop spam. For sending application emails, use submission ports 587 or 465 with authenticated TLS.',
    killCommandLinux: 'sudo systemctl stop postfix',
    killCommandWin: 'Stop-Service SMTPSVC -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep :25',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 25',
    firewallUfw: 'sudo ufw deny 25/tcp',
    dockerRun: 'docker run -p 25:25 -d namshi/smtp',
    commonError: 'Connection timed out trying to reach mail server on port 25 (Cloud provider blocked)',
  },
  {
    port: 587,
    slug: 'port-587',
    name: 'Port 587',
    service: 'SMTP Submission (STARTTLS)',
    protocol: 'TCP',
    category: 'Networking',
    description: 'Port 587 is the modern standard port for email client-to-server message submission (e.g. SendGrid, Mailgun, Amazon SES) protected by mandatory STARTTLS encryption.',
    defaultProcess: 'postfix, exim4',
    riskLevel: 'Medium',
    securityNote: 'Requires SMTP authentication before relaying any messages to prevent open-relay abuse.',
    killCommandLinux: 'sudo systemctl restart postfix',
    killCommandWin: 'Get-NetTCPConnection -LocalPort 587',
    checkCommandLinux: 'openssl s_client -starttls smtp -connect smtp.gmail.com:587',
    checkCommandWin: 'Test-NetConnection -ComputerName smtp.sendgrid.net -Port 587',
    firewallUfw: 'sudo ufw allow 587/tcp',
    dockerRun: 'docker run -p 587:587 -d my-mail-server',
    commonError: '535 5.7.8 Error: authentication failed on SMTP port 587',
  },

  // --- Messaging & Event Streaming ---
  {
    port: 9092,
    slug: 'port-9092',
    name: 'Port 9092',
    service: 'Apache Kafka Broker',
    protocol: 'TCP',
    category: 'Messaging & Cache',
    description: 'Port 9092 is the default port for Apache Kafka distributed event streaming brokers.',
    defaultProcess: 'java, kafka',
    riskLevel: 'High',
    securityNote: 'Ensure SASL/SCRAM or mTLS authentication is enabled (`listeners=SASL_PLAINTEXT://:9092` or `SSL://:9092`).',
    killCommandLinux: 'kill -9 $(lsof -t -i:9092)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 9092).OwningProcess -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep 9092',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 9092',
    firewallUfw: 'sudo ufw allow from 10.0.0.0/8 to any port 9092 proto tcp',
    dockerRun: 'docker run -p 9092:9092 -d apache/kafka:latest',
    commonError: 'org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms (port 9092)',
  },
  {
    port: 5672,
    slug: 'port-5672',
    name: 'Port 5672',
    service: 'RabbitMQ AMQP Protocol',
    protocol: 'TCP',
    category: 'Messaging & Cache',
    description: 'Port 5672 is the default standard port for the Advanced Message Queuing Protocol (AMQP 0-9-1 and 1.0) utilized by RabbitMQ.',
    defaultProcess: 'beam.smp, rabbitmq',
    riskLevel: 'Medium',
    securityNote: 'Disable the default `guest/guest` account for remote access or restrict it strictly to localhost.',
    killCommandLinux: 'sudo systemctl stop rabbitmq-server',
    killCommandWin: 'Stop-Service RabbitMQ -Force',
    checkCommandLinux: 'sudo rabbitmq-diagnostics check_port_connectivity',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 5672',
    firewallUfw: 'sudo ufw allow 5672/tcp',
    dockerRun: 'docker run -p 5672:5672 -p 15672:15672 -d rabbitmq:3-management',
    commonError: 'AMQP connection failed: Connection refused at localhost:5672',
  },
  {
    port: 15672,
    slug: 'port-15672',
    name: 'Port 15672',
    service: 'RabbitMQ Management Web UI',
    protocol: 'TCP',
    category: 'Messaging & Cache',
    description: 'Port 15672 is the HTTP web management dashboard and REST monitoring API for RabbitMQ.',
    defaultProcess: 'beam.smp',
    riskLevel: 'Medium',
    securityNote: 'Set strong passwords for all administrator accounts and avoid exposing 15672 directly to the internet.',
    killCommandLinux: 'kill -9 $(lsof -t -i:15672)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 15672).OwningProcess -Force',
    checkCommandLinux: 'curl -I http://localhost:15672',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 15672',
    firewallUfw: 'sudo ufw allow 15672/tcp',
    dockerRun: 'docker run -p 15672:15672 -d rabbitmq:management',
    commonError: 'HTTP 401 Unauthorized: Access to management dashboard on 15672 refused.',
  },
  {
  "port": 23,
  "slug": "port-23",
  "name": "Port 23",
  "service": "Telnet Remote Terminal",
  "protocol": "TCP",
  "category": "Security",
  "description": "Port 23 is the historical standard port for the Telnet protocol, providing unencrypted, cleartext remote command-line access to network equipment, routers, and legacy Linux/Unix hosts.",
  "defaultProcess": "telnetd, in.telnetd",
  "riskLevel": "Critical",
  "securityNote": "Telnet transmits usernames, passwords, and commands in plaintext across the network. It should be completely disabled and replaced with SSH (Port 22).",
  "killCommandLinux": "sudo systemctl stop telnetd || sudo killall in.telnetd",
  "killCommandWin": "Stop-Service -Name TlntSvr -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "sudo lsof -i :23 || sudo ss -tulpn | grep \":23 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 23",
  "firewallUfw": "sudo ufw deny 23/tcp",
  "dockerRun": "# Telnet should not be containerized; use SSH or secure bash sessions instead",
  "commonError": "Connection closed by foreign host / Telnet connection refused on port 23."
},
  {
  "port": 67,
  "slug": "port-67",
  "name": "Port 67",
  "service": "DHCP Server (Bootstrap Protocol)",
  "protocol": "UDP",
  "category": "Networking",
  "description": "Port 67 is used by DHCP (Dynamic Host Configuration Protocol) servers to receive broadcast lease requests from client devices seeking IP configuration on local subnets.",
  "defaultProcess": "dhcpd, dnsmasq, isc-dhcp-server",
  "riskLevel": "Medium",
  "securityNote": "Rogue DHCP servers on an untrusted local network can assign malicious DNS resolvers and default gateways, leading to Man-in-the-Middle (MitM) attacks. Implement DHCP snooping on network switches.",
  "killCommandLinux": "sudo systemctl stop isc-dhcp-server || sudo killall dhcpd",
  "killCommandWin": "Stop-Service DHCPServer -Force",
  "checkCommandLinux": "sudo ss -ulpn | grep \":67 \"",
  "checkCommandWin": "Get-NetUDPEndpoint -LocalPort 67",
  "firewallUfw": "sudo ufw allow 67/udp",
  "dockerRun": "docker run -d --net=host -v /etc/dhcp:/data networkboot/dhcpd eth0",
  "commonError": "dhcpd: Address already in use or interface not configured for DHCP broadcasts."
},
  {
  "port": 68,
  "slug": "port-68",
  "name": "Port 68",
  "service": "DHCP Client",
  "protocol": "UDP",
  "category": "Networking",
  "description": "Port 68 is used by DHCP client network daemons (such as dhclient or systemd-networkd) to receive assigned IP lease configurations from the local DHCP server.",
  "defaultProcess": "dhclient, NetworkManager, systemd-networkd",
  "riskLevel": "Low",
  "securityNote": "Used only for client-side local IP negotiation. Keep firewalls configured to allow responses from trusted gateway routers.",
  "killCommandLinux": "sudo killall dhclient",
  "killCommandWin": "ipconfig /release",
  "checkCommandLinux": "sudo ss -ulpn | grep \":68 \"",
  "checkCommandWin": "Get-NetUDPEndpoint -LocalPort 68",
  "firewallUfw": "sudo ufw allow 68/udp",
  "dockerRun": "# Container network interfaces inherit bridge IPs without standalone client daemons",
  "commonError": "dhclient: no DHCPOFFERS received; failed to acquire IP lease on port 68."
},
  {
  "port": 69,
  "slug": "port-69",
  "name": "Port 69",
  "service": "TFTP (Trivial File Transfer Protocol)",
  "protocol": "UDP",
  "category": "Networking",
  "description": "Port 69 is the UDP port for TFTP, an unauthenticated, bare-bones file transfer protocol used primarily for PXE network booting, VoIP phone firmware provisioning, and network router backups.",
  "defaultProcess": "tftpd, in.tftpd, dnsmasq",
  "riskLevel": "High",
  "securityNote": "TFTP has no user authentication or encryption. Any device on the subnet can read or write files. Restrict to dedicated management VLANs.",
  "killCommandLinux": "sudo systemctl stop tftpd-hpa || sudo killall in.tftpd",
  "killCommandWin": "Stop-Service -Name tftpd32 -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "sudo ss -ulpn | grep \":69 \"",
  "checkCommandWin": "Get-NetUDPEndpoint -LocalPort 69",
  "firewallUfw": "sudo ufw allow 69/udp",
  "dockerRun": "docker run -d -p 69:69/udp -v /tftpboot:/var/tftpboot ghcr.io/linuxserver/tftp",
  "commonError": "TFTP error: Access violation / Transfer timed out on port 69."
},
  {
  "port": 110,
  "slug": "port-110",
  "name": "Port 110",
  "service": "POP3 Mail Retrieval",
  "protocol": "TCP",
  "category": "Networking",
  "description": "Port 110 is the standard unencrypted port for the Post Office Protocol version 3 (POP3), used by email clients to retrieve messages from a remote mail server.",
  "defaultProcess": "dovecot, pop3d",
  "riskLevel": "High",
  "securityNote": "Transmits email account passwords and messages in cleartext. Always prefer POP3S over port 995 with SSL/TLS encryption.",
  "killCommandLinux": "sudo systemctl stop dovecot",
  "killCommandWin": "Stop-Service POP3Svc -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "sudo lsof -i :110 || sudo ss -tulpn | grep \":110 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 110",
  "firewallUfw": "sudo ufw deny 110/tcp",
  "dockerRun": "docker run -p 110:110 -d mailserver/docker-mailserver:latest",
  "commonError": "-ERR [AUTH] Authentication failed on unencrypted POP3 port 110."
},
  {
  "port": 123,
  "slug": "port-123",
  "name": "Port 123",
  "service": "NTP (Network Time Protocol)",
  "protocol": "UDP",
  "category": "Networking",
  "description": "Port 123 is the fundamental UDP port for NTP and chrony, synchronizing system clocks across computer networks down to millisecond precision.",
  "defaultProcess": "ntpd, chronyd, systemd-timesyncd",
  "riskLevel": "Low",
  "securityNote": "Older NTP daemon versions are vulnerable to NTP amplification DDoS attacks (monlist). Ensure NTP monlist is disabled in ntp.conf.",
  "killCommandLinux": "sudo systemctl stop chronyd || sudo systemctl stop ntp",
  "killCommandWin": "Stop-Service W32Time -Force",
  "checkCommandLinux": "chronyc tracking || sudo ss -ulpn | grep \":123 \"",
  "checkCommandWin": "w32tm /query /status",
  "firewallUfw": "sudo ufw allow 123/udp",
  "dockerRun": "docker run -d -p 123:123/udp --cap-add=SYS_TIME cturra/ntp",
  "commonError": "ntpdate: no server suitable for synchronization found on port 123."
},
  {
  "port": 143,
  "slug": "port-143",
  "name": "Port 143",
  "service": "IMAP Mail Protocol",
  "protocol": "TCP",
  "category": "Networking",
  "description": "Port 143 is the standard port for the Internet Message Access Protocol (IMAP), allowing email clients to manage folders and messages on the mail server.",
  "defaultProcess": "dovecot, imapd, courier-imap",
  "riskLevel": "Medium",
  "securityNote": "Cleartext IMAP transmits login credentials without encryption. Use STARTTLS or migrate to port 993 (IMAPS) with explicit TLS.",
  "killCommandLinux": "sudo systemctl stop dovecot",
  "killCommandWin": "Stop-Service MSExchangeIS -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "sudo lsof -i :143 || sudo ss -tulpn | grep \":143 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 143",
  "firewallUfw": "sudo ufw allow 143/tcp",
  "dockerRun": "docker run -p 143:143 -d mailserver/docker-mailserver",
  "commonError": "* NO [AUTHENTICATIONFAILED] Authentication failed on port 143."
},
  {
  "port": 161,
  "slug": "port-161",
  "name": "Port 161",
  "service": "SNMP (Simple Network Management Protocol)",
  "protocol": "UDP",
  "category": "Networking",
  "description": "Port 161 is used by SNMP agents to listen for monitoring requests, telemetry queries, and device status polls from Network Management Stations (NMS).",
  "defaultProcess": "snmpd",
  "riskLevel": "High",
  "securityNote": "SNMP v1 and v2c use plaintext community strings (frequently default to \"public\"), exposing network topologies and hardware details. Upgrade to SNMPv3 with authPriv encryption.",
  "killCommandLinux": "sudo systemctl stop snmpd",
  "killCommandWin": "Stop-Service SNMP -Force",
  "checkCommandLinux": "sudo ss -ulpn | grep \":161 \"",
  "checkCommandWin": "Get-NetUDPEndpoint -LocalPort 161",
  "firewallUfw": "sudo ufw allow from 10.0.0.0/8 to any port 161 proto udp",
  "dockerRun": "docker run -d -p 161:161/udp prom/snmp-exporter",
  "commonError": "Timeout: No Response from host on UDP port 161 (snmpwalk timed out)."
},
  {
  "port": 389,
  "slug": "port-389",
  "name": "Port 389",
  "service": "LDAP Directory Service",
  "protocol": "TCP",
  "category": "Security",
  "description": "Port 389 is the default port for Lightweight Directory Access Protocol (LDAP) and Active Directory Domain Services, used for centralized enterprise user authentication and directory queries.",
  "defaultProcess": "slapd, lsass.exe, openldap",
  "riskLevel": "Medium",
  "securityNote": "Ensure STARTTLS is enforced or migrate clients to LDAPS (Port 636) to prevent credentials from being intercepted over the wire.",
  "killCommandLinux": "sudo systemctl stop slapd",
  "killCommandWin": "Stop-Service NTDS -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "sudo lsof -i :389 || sudo ss -tulpn | grep \":389 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 389",
  "firewallUfw": "sudo ufw allow 389/tcp",
  "dockerRun": "docker run -p 389:389 -d osixia/openldap:latest",
  "commonError": "ldap_bind: Can't contact LDAP server (port 389)."
},
  {
  "port": 445,
  "slug": "port-445",
  "name": "Port 445",
  "service": "Microsoft SMB / CIFS File Sharing",
  "protocol": "TCP",
  "category": "Networking",
  "description": "Port 445 provides direct TCP hosting for Server Message Block (SMB) file and printer sharing in Windows, Samba, and enterprise NAS systems without requiring NetBIOS.",
  "defaultProcess": "System (ntoskrnl.exe), smbd",
  "riskLevel": "Critical",
  "securityNote": "Port 445 has been the primary attack vector for major ransomware and worms (WannaCry, EternalBlue, NotPetya). NEVER expose port 445 to the public internet.",
  "killCommandLinux": "sudo systemctl stop smbd",
  "killCommandWin": "Stop-Service LanmanServer -Force",
  "checkCommandLinux": "sudo lsof -i :445 || sudo ss -tulpn | grep \":445 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 445",
  "firewallUfw": "sudo ufw deny 445/tcp",
  "dockerRun": "docker run -d -p 445:445 dperson/samba",
  "commonError": "System error 53 has occurred. The network path was not found on port 445."
},
  {
  "port": 465,
  "slug": "port-465",
  "name": "Port 465",
  "service": "SMTPS (Secure SMTP over SSL)",
  "protocol": "TCP",
  "category": "Networking",
  "description": "Port 465 is the standard encrypted submission port for SMTP over implicit TLS/SSL (RFC 8314), ensuring secure transmission of outbound emails from client to server.",
  "defaultProcess": "postfix, exim4, sendmail",
  "riskLevel": "Low",
  "securityNote": "Ensure valid SSL/TLS certificates and enforce modern cipher suites (TLS 1.2/1.3) to prevent downgrade attacks.",
  "killCommandLinux": "sudo systemctl stop postfix",
  "killCommandWin": "Stop-Service SMTPSVC -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "sudo lsof -i :465 || sudo ss -tulpn | grep \":465 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 465",
  "firewallUfw": "sudo ufw allow 465/tcp",
  "dockerRun": "docker run -p 465:465 -d mailserver/docker-mailserver",
  "commonError": "SSL handshake failed: certificate verification failed connecting to port 465."
},
  {
  "port": 514,
  "slug": "port-514",
  "name": "Port 514",
  "service": "Syslog Event Logging",
  "protocol": "UDP",
  "category": "DevOps & Cloud",
  "description": "Port 514 is the traditional UDP port for Syslog daemons (rsyslog, syslog-ng), collecting centralized security events, system alerts, and audit logs from network devices.",
  "defaultProcess": "rsyslogd, syslog-ng",
  "riskLevel": "Medium",
  "securityNote": "Standard UDP syslog does not verify sender identity or encrypt log content. For sensitive compliance data, use Syslog over TLS (RFC 5425, port 6514).",
  "killCommandLinux": "sudo systemctl stop rsyslog",
  "killCommandWin": "Stop-Service Syslog -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "sudo ss -ulpn | grep \":514 \"",
  "checkCommandWin": "Get-NetUDPEndpoint -LocalPort 514",
  "firewallUfw": "sudo ufw allow from 10.0.0.0/8 to any port 514 proto udp",
  "dockerRun": "docker run -d -p 514:514/udp -v /var/log:/var/log balabit/syslog-ng:latest",
  "commonError": "rsyslogd: bind() error on port 514: Address already in use."
},
  {
  "port": 636,
  "slug": "port-636",
  "name": "Port 636",
  "service": "LDAPS (Secure LDAP over SSL)",
  "protocol": "TCP",
  "category": "Security",
  "description": "Port 636 is the official port for LDAPS (LDAP over SSL), providing encrypted transport for enterprise directory lookups, user authorization, and password management.",
  "defaultProcess": "slapd, lsass.exe",
  "riskLevel": "Low",
  "securityNote": "Preferred standard over cleartext port 389. Ensure CA certificates are deployed across client servers to validate trust chains.",
  "killCommandLinux": "sudo systemctl stop slapd",
  "killCommandWin": "Stop-Service NTDS -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "sudo lsof -i :636 || sudo ss -tulpn | grep \":636 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 636",
  "firewallUfw": "sudo ufw allow 636/tcp",
  "dockerRun": "docker run -p 636:636 -d osixia/openldap:latest",
  "commonError": "LDAP error: TLS negotiation failed connecting to port 636."
},
  {
  "port": 873,
  "slug": "port-873",
  "name": "Port 873",
  "service": "rsync Remote Sync Daemon",
  "protocol": "TCP",
  "category": "DevOps & Cloud",
  "description": "Port 873 is the default TCP port for the rsync daemon (rsyncd), facilitating high-speed differential file synchronization and server backups across networks.",
  "defaultProcess": "rsync, rsyncd",
  "riskLevel": "Medium",
  "securityNote": "Rsync daemon authentication can be weak if rsyncd.secrets is misconfigured. In most modern infrastructures, rsync over SSH (port 22) is preferred.",
  "killCommandLinux": "sudo systemctl stop rsync || sudo killall rsync",
  "killCommandWin": "Stop-Process -Name rsync -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "sudo lsof -i :873 || sudo ss -tulpn | grep \":873 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 873",
  "firewallUfw": "sudo ufw allow from 192.168.1.0/24 to any port 873 proto tcp",
  "dockerRun": "docker run -d -p 873:873 -v /data:/data servercontainers/rsync",
  "commonError": "rsync: failed to connect to host (port 873): Connection refused."
},
  {
  "port": 993,
  "slug": "port-993",
  "name": "Port 993",
  "service": "IMAPS (IMAP over SSL/TLS)",
  "protocol": "TCP",
  "category": "Networking",
  "description": "Port 993 is the secure, industry-standard port for IMAP over SSL/TLS, encrypting all client-server mail communication from the initial connection.",
  "defaultProcess": "dovecot, imapd",
  "riskLevel": "Low",
  "securityNote": "Standard secure email retrieval port. Enforce modern TLS 1.3 protocol and keep mail server SSL certificates automatically renewed with Let's Encrypt.",
  "killCommandLinux": "sudo systemctl stop dovecot",
  "killCommandWin": "Stop-Service MSExchangeIS -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "sudo lsof -i :993 || sudo ss -tulpn | grep \":993 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 993",
  "firewallUfw": "sudo ufw allow 993/tcp",
  "dockerRun": "docker run -p 993:993 -d mailserver/docker-mailserver:latest",
  "commonError": "Connection refused connecting to mail server IMAPS on port 993."
},
  {
  "port": 995,
  "slug": "port-995",
  "name": "Port 995",
  "service": "POP3S (POP3 over SSL/TLS)",
  "protocol": "TCP",
  "category": "Networking",
  "description": "Port 995 is the secure, encrypted port for POP3 email downloads, protecting mailbox authentication credentials and email content from packet sniffing.",
  "defaultProcess": "dovecot, pop3d",
  "riskLevel": "Low",
  "securityNote": "Secure replacement for legacy port 110. Restrict weak ciphers in mail server configuration.",
  "killCommandLinux": "sudo systemctl stop dovecot",
  "killCommandWin": "Stop-Service POP3Svc -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "sudo lsof -i :995 || sudo ss -tulpn | grep \":995 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 995",
  "firewallUfw": "sudo ufw allow 995/tcp",
  "dockerRun": "docker run -p 995:995 -d mailserver/docker-mailserver",
  "commonError": "POP3S connection failed: SSL peer shut down incorrectly on port 995."
},
  {
  "port": 1080,
  "slug": "port-1080",
  "name": "Port 1080",
  "service": "SOCKS Proxy Protocol (SOCKS4 / SOCKS5)",
  "protocol": "TCP",
  "category": "Security",
  "description": "Port 1080 is the designated default port for SOCKS proxy servers (such as Dante or Shadowsocks), routing arbitrary TCP/UDP client traffic through an intermediary proxy.",
  "defaultProcess": "danted, shadowsocks, microsocks",
  "riskLevel": "High",
  "securityNote": "Open, unauthenticated SOCKS proxies on port 1080 are quickly discovered by botnets and abused as spam relays or attack launchpads.",
  "killCommandLinux": "sudo systemctl stop danted || sudo killall danted",
  "killCommandWin": "Stop-Process -Name danted -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "sudo lsof -i :1080 || sudo ss -tulpn | grep \":1080 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 1080",
  "firewallUfw": "sudo ufw allow from 127.0.0.1 to any port 1080 proto tcp",
  "dockerRun": "docker run -d -p 1080:1080 vimagick/dante",
  "commonError": "curl: (7) Failed to connect to localhost port 1080: Connection refused (SOCKS5 proxy down)."
},
  {
  "port": 1194,
  "slug": "port-1194",
  "name": "Port 1194",
  "service": "OpenVPN Virtual Private Network",
  "protocol": "UDP",
  "category": "Security",
  "description": "Port 1194 is the IANA-assigned default port for OpenVPN tunnels, establishing encrypted point-to-point and site-to-site VPN connections between remote hosts and private subnets.",
  "defaultProcess": "openvpn",
  "riskLevel": "Low",
  "securityNote": "Ensure client certificates are required (TLS-Auth or TLS-Crypt) to prevent port scanning reconnaissance from fingerprinting the VPN server.",
  "killCommandLinux": "sudo systemctl stop openvpn || sudo killall openvpn",
  "killCommandWin": "Stop-Service OpenVPNService -Force",
  "checkCommandLinux": "sudo ss -ulpn | grep \":1194 \"",
  "checkCommandWin": "Get-NetUDPEndpoint -LocalPort 1194",
  "firewallUfw": "sudo ufw allow 1194/udp",
  "dockerRun": "docker run -d --cap-add=NET_ADMIN -p 1194:1194/udp kylemanna/openvpn",
  "commonError": "TLS Error: TLS key negotiation failed to occur within 60 seconds (check port 1194 UDP routing)."
},
  {
  "port": 1883,
  "slug": "port-1883",
  "name": "Port 1883",
  "service": "MQTT Broker (Internet of Things)",
  "protocol": "TCP",
  "category": "Messaging & Cache",
  "description": "Port 1883 is the standard unencrypted port for MQTT (Message Queuing Telemetry Transport) brokers (Eclipse Mosquitto, EMQX, HiveMQ), connecting IoT sensors, home automation, and lightweight telemetry devices.",
  "defaultProcess": "mosquitto, emqx",
  "riskLevel": "High",
  "securityNote": "Never expose unencrypted MQTT on port 1883 to the public internet. Use MQTT over TLS on port 8883 with client certificates for production IoT deployments.",
  "killCommandLinux": "sudo systemctl stop mosquitto || sudo killall mosquitto",
  "killCommandWin": "Stop-Service mosquitto -Force",
  "checkCommandLinux": "sudo lsof -i :1883 || sudo ss -tulpn | grep \":1883 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 1883",
  "firewallUfw": "sudo ufw allow 1883/tcp",
  "dockerRun": "docker run -d -p 1883:1883 -p 9001:9001 eclipse-mosquitto",
  "commonError": "Connection refused: Broker unreachable at tcp://localhost:1883."
},
  {
  "port": 2049,
  "slug": "port-2049",
  "name": "Port 2049",
  "service": "NFS (Network File System)",
  "protocol": "TCP/UDP",
  "category": "Networking",
  "description": "Port 2049 is the standard port for NFS (NFSv3 and NFSv4) storage services, allowing remote Linux and Unix systems to mount distributed file systems across high-speed LANs.",
  "defaultProcess": "nfsd, rpc.mountd",
  "riskLevel": "Critical",
  "securityNote": "NFS exports must be restricted strictly to authorized client IP ranges in /etc/exports. Never expose port 2049 beyond a trusted private storage network.",
  "killCommandLinux": "sudo systemctl stop nfs-server",
  "killCommandWin": "Stop-Service NfsSvc -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "sudo lsof -i :2049 || sudo ss -tulpn | grep \":2049 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 2049",
  "firewallUfw": "sudo ufw allow from 10.0.0.0/8 to any port 2049 proto tcp",
  "dockerRun": "docker run -d --privileged -p 2049:2049 itsthenetwork/nfs-server-alpine",
  "commonError": "mount.nfs: mount system call failed: Connection refused on port 2049."
},
  {
  "port": 2181,
  "slug": "port-2181",
  "name": "Port 2181",
  "service": "Apache ZooKeeper Coordination",
  "protocol": "TCP",
  "category": "DevOps & Cloud",
  "description": "Port 2181 is the default client connection port for Apache ZooKeeper, managing distributed synchronization, configuration, and cluster consensus for systems like Apache Kafka and Hadoop.",
  "defaultProcess": "java (zookeeper)",
  "riskLevel": "High",
  "securityNote": "Exposed ZooKeeper clusters on port 2181 can be queried via the 'four-letter-words' commands (ruok, dump, stat), leaking sensitive cluster secrets. Restrict access strictly to local private subnets.",
  "killCommandLinux": "sudo systemctl stop zookeeper || kill -9 $(lsof -t -i:2181)",
  "killCommandWin": "Stop-Process -Id (Get-NetTCPConnection -LocalPort 2181).OwningProcess -Force",
  "checkCommandLinux": "echo ruok | nc localhost 2181 || sudo lsof -i :2181",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 2181",
  "firewallUfw": "sudo ufw allow from 10.0.0.0/8 to any port 2181 proto tcp",
  "dockerRun": "docker run -d -p 2181:2181 --name zookeeper zookeeper:latest",
  "commonError": "KeeperErrorCode = ConnectionLoss for localhost:2181."
},
  {
  "port": 2379,
  "slug": "port-2379",
  "name": "Port 2379",
  "service": "etcd Client API (Kubernetes Datastore)",
  "protocol": "TCP",
  "category": "DevOps & Cloud",
  "description": "Port 2379 is the primary gRPC client communication port for etcd, the distributed key-value store that houses the entire state and secret configuration of Kubernetes clusters.",
  "defaultProcess": "etcd",
  "riskLevel": "Critical",
  "securityNote": "Direct unauthenticated access to etcd port 2379 grants full administrative control over the Kubernetes cluster, including access to all cluster secrets and certificates. Always enforce mTLS.",
  "killCommandLinux": "sudo systemctl stop etcd || kill -9 $(lsof -t -i:2379)",
  "killCommandWin": "Stop-Process -Id (Get-NetTCPConnection -LocalPort 2379).OwningProcess -Force",
  "checkCommandLinux": "etcdctl endpoint health || sudo lsof -i :2379",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 2379",
  "firewallUfw": "sudo ufw deny 2379/tcp",
  "dockerRun": "docker run -d -p 2379:2379 quay.io/coreos/etcd:latest",
  "commonError": "rpc error: code = Unavailable desc = connection refused to etcd cluster on port 2379."
},
  {
  "port": 3128,
  "slug": "port-3128",
  "name": "Port 3128",
  "service": "Squid HTTP Proxy / Caching",
  "protocol": "TCP",
  "category": "Networking",
  "description": "Port 3128 is the default listening port for Squid Web Proxy Cache, utilized in enterprise networks for content filtering, web acceleration, and internet access control.",
  "defaultProcess": "squid",
  "riskLevel": "High",
  "securityNote": "Open Squid proxies allow external threat actors to tunnel traffic through your IP, masking malicious actions and consuming bandwidth. Enforce strict ACLs in squid.conf.",
  "killCommandLinux": "sudo systemctl stop squid || sudo killall squid",
  "killCommandWin": "Stop-Service Squid -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "sudo lsof -i :3128 || sudo ss -tulpn | grep \":3128 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 3128",
  "firewallUfw": "sudo ufw allow 3128/tcp",
  "dockerRun": "docker run -d -p 3128:3128 ubuntu/squid",
  "commonError": "Squid Proxy Error: Access Denied / Connection to localhost:3128 failed."
},
  {
  "port": 3389,
  "slug": "port-3389",
  "name": "Port 3389",
  "service": "RDP (Remote Desktop Protocol)",
  "protocol": "TCP/UDP",
  "category": "Networking",
  "description": "Port 3389 is the Microsoft Remote Desktop Protocol (RDP) listening port, enabling graphical desktop access and terminal server management on Windows and Linux (xrdp) hosts.",
  "defaultProcess": "TermService (svchost.exe), xrdp",
  "riskLevel": "Critical",
  "securityNote": "Port 3389 is the single most targeted port on the internet for automated brute-force attacks and credential stuffing. NEVER expose port 3389 directly; always require a VPN, WireGuard, or bastion jumpbox with MFA.",
  "killCommandLinux": "sudo systemctl stop xrdp",
  "killCommandWin": "Stop-Service TermService -Force",
  "checkCommandLinux": "sudo lsof -i :3389 || sudo ss -tulpn | grep \":3389 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 3389",
  "firewallUfw": "sudo ufw deny 3389/tcp",
  "dockerRun": "docker run -d -p 3389:3389 scottyhardy/docker-remote-desktop",
  "commonError": "Remote Desktop can't connect to the remote computer for one of these reasons on port 3389."
},
  {
  "port": 4000,
  "slug": "port-4000",
  "name": "Port 4000",
  "service": "Strapi / Hexo / Phoenix Dev Server",
  "protocol": "TCP",
  "category": "Web & Dev",
  "description": "Port 4000 is the common default port for static site generators (Hexo, Jekyll), headless CMS frameworks (Strapi), GraphQL Playgrounds, and Elixir Phoenix development servers.",
  "defaultProcess": "node, strapi, mix",
  "riskLevel": "Low",
  "securityNote": "Ensure debug admin panels and GraphQL Introspection queries are disabled in production builds.",
  "killCommandLinux": "kill -9 $(lsof -t -i:4000)",
  "killCommandWin": "Stop-Process -Id (Get-NetTCPConnection -LocalPort 4000).OwningProcess -Force",
  "checkCommandLinux": "sudo lsof -i :4000 || sudo ss -tulpn | grep \":4000 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 4000",
  "firewallUfw": "sudo ufw allow 4000/tcp",
  "dockerRun": "docker run -p 4000:4000 -d strapi/strapi",
  "commonError": "Error: Port 4000 is already in use by another process."
},
  {
  "port": 4317,
  "slug": "port-4317",
  "name": "Port 4317",
  "service": "OpenTelemetry OTLP gRPC Receiver",
  "protocol": "TCP",
  "category": "DevOps & Cloud",
  "description": "Port 4317 is the standard IANA port for the OpenTelemetry Protocol (OTLP) over gRPC, collecting distributed traces, metrics, and application telemetry across cloud-native clusters.",
  "defaultProcess": "otelcol, otelcol-contrib",
  "riskLevel": "Low",
  "securityNote": "Ensure TLS authentication is enabled when forwarding telemetry over public or inter-region cloud networks.",
  "killCommandLinux": "sudo systemctl stop otel-collector || kill -9 $(lsof -t -i:4317)",
  "killCommandWin": "Stop-Process -Id (Get-NetTCPConnection -LocalPort 4317).OwningProcess -Force",
  "checkCommandLinux": "sudo lsof -i :4317 || sudo ss -tulpn | grep \":4317 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 4317",
  "firewallUfw": "sudo ufw allow 4317/tcp",
  "dockerRun": "docker run -d -p 4317:4317 otel/opentelemetry-collector:latest",
  "commonError": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp :4317: connect: connection refused\"."
},
  {
  "port": 4318,
  "slug": "port-4318",
  "name": "Port 4318",
  "service": "OpenTelemetry OTLP HTTP Receiver",
  "protocol": "TCP",
  "category": "DevOps & Cloud",
  "description": "Port 4318 is the official port for OpenTelemetry Protocol (OTLP) telemetry ingestion over HTTP/JSON and Protobuf, widely used in web frontend instrumentation and serverless functions.",
  "defaultProcess": "otelcol, otelcol-contrib",
  "riskLevel": "Low",
  "securityNote": "Configure rate limiting and body size limits in the collector pipeline to avoid telemetry denial-of-service.",
  "killCommandLinux": "sudo systemctl stop otel-collector || kill -9 $(lsof -t -i:4318)",
  "killCommandWin": "Stop-Process -Id (Get-NetTCPConnection -LocalPort 4318).OwningProcess -Force",
  "checkCommandLinux": "curl -I http://localhost:4318/v1/traces",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 4318",
  "firewallUfw": "sudo ufw allow 4318/tcp",
  "dockerRun": "docker run -d -p 4318:4318 otel/opentelemetry-collector:latest",
  "commonError": "Failed to export traces to http://localhost:4318/v1/traces: Connection refused."
},
  {
  "port": 5060,
  "slug": "port-5060",
  "name": "Port 5060",
  "service": "SIP (Session Initiation Protocol / VoIP)",
  "protocol": "TCP/UDP",
  "category": "Networking",
  "description": "Port 5060 is the primary signaling port for SIP, setting up, routing, and terminating voice and video calls in Asterisk, FreePBX, and corporate VoIP PBX systems.",
  "defaultProcess": "asterisk, freeswitch",
  "riskLevel": "High",
  "securityNote": "Frequently scanned for SIP toll fraud, where attackers attempt brute force on SIP extensions to route high-cost international calls. Implement Fail2ban with SIP filters.",
  "killCommandLinux": "sudo systemctl stop asterisk || sudo killall asterisk",
  "killCommandWin": "Stop-Service 3CXPhoneSystem -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "sudo ss -ulpn | grep \":5060 \"",
  "checkCommandWin": "Get-NetUDPEndpoint -LocalPort 5060",
  "firewallUfw": "sudo ufw allow 5060/udp",
  "dockerRun": "docker run -d --net=host andrius/asterisk",
  "commonError": "SIP Registration timed out on port 5060."
},
  {
  "port": 5900,
  "slug": "port-5900",
  "name": "Port 5900",
  "service": "VNC Remote Desktop (RFB Protocol)",
  "protocol": "TCP",
  "category": "Networking",
  "description": "Port 5900 is the default TCP listening port for Virtual Network Computing (VNC / RFB protocol) servers, including TightVNC, TigerVNC, RealVNC, and macOS Screen Sharing.",
  "defaultProcess": "Xvnc, tigervnc, winvnc.exe",
  "riskLevel": "Critical",
  "securityNote": "Traditional VNC passwords are truncated to 8 characters and encryption is often nonexistent. Tunnel VNC over an SSH connection (ssh -L 5900:localhost:5900) instead of exposing port 5900.",
  "killCommandLinux": "vncserver -kill :0 || kill -9 $(lsof -t -i:5900)",
  "killCommandWin": "Stop-Process -Name winvnc* -Force",
  "checkCommandLinux": "sudo lsof -i :5900 || sudo ss -tulpn | grep \":5900 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 5900",
  "firewallUfw": "sudo ufw deny 5900/tcp",
  "dockerRun": "docker run -d -p 5900:5900 dorowu/ubuntu-desktop-lxde-vnc",
  "commonError": "VNC connection closed unexpectedly: RFB server not answering on port 5900."
},
  {
  "port": 7000,
  "slug": "port-7000",
  "name": "Port 7000",
  "service": "Apache Cassandra Inter-Node Cluster",
  "protocol": "TCP",
  "category": "Database",
  "description": "Port 7000 is used by Apache Cassandra nodes for peer-to-peer inter-node gossip and cluster communication (storage_port).",
  "defaultProcess": "java (cassandra)",
  "riskLevel": "High",
  "securityNote": "Keep port 7000 strictly enclosed within a trusted cluster subnet or VPC. Never allow direct internet traffic.",
  "killCommandLinux": "sudo systemctl stop cassandra || kill -9 $(lsof -t -i:7000)",
  "killCommandWin": "Stop-Process -Id (Get-NetTCPConnection -LocalPort 7000).OwningProcess -Force",
  "checkCommandLinux": "nodetool status || sudo lsof -i :7000",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 7000",
  "firewallUfw": "sudo ufw allow from 10.0.0.0/8 to any port 7000 proto tcp",
  "dockerRun": "docker run -d -p 7000:7000 cassandra:latest",
  "commonError": "Failed to connect to Cassandra cluster peer on port 7000."
},
  {
  "port": 8081,
  "slug": "port-8081",
  "name": "Port 8081",
  "service": "React Native Metro Bundler / Webpack Alt",
  "protocol": "TCP",
  "category": "Web & Dev",
  "description": "Port 8081 is the default port for the React Native Metro JavaScript bundler, as well as alternative development proxies and microservice listeners.",
  "defaultProcess": "node (metro)",
  "riskLevel": "Low",
  "securityNote": "Ensure developer tools and sourcemaps are not exposed on public staging IPs.",
  "killCommandLinux": "kill -9 $(lsof -t -i:8081)",
  "killCommandWin": "Stop-Process -Id (Get-NetTCPConnection -LocalPort 8081).OwningProcess -Force",
  "checkCommandLinux": "sudo lsof -i :8081 || sudo ss -tulpn | grep \":8081 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 8081",
  "firewallUfw": "sudo ufw allow 8081/tcp",
  "dockerRun": "docker run -p 8081:8081 -d my-node-bundler",
  "commonError": "Metro Bundler failed to start: Port 8081 is already in use."
},
  {
  "port": 8088,
  "slug": "port-8088",
  "name": "Port 8088",
  "service": "Apache Hadoop YARN Web UI",
  "protocol": "TCP",
  "category": "DevOps & Cloud",
  "description": "Port 8088 is the default HTTP web management dashboard port for Apache Hadoop YARN ResourceManager, monitoring cluster job queues and node allocations.",
  "defaultProcess": "java (yarn)",
  "riskLevel": "Critical",
  "securityNote": "Exposed YARN UI on port 8088 without authentication is heavily targeted by cryptocurrency miners to submit malicious jobs via the REST API. Never expose to 0.0.0.0.",
  "killCommandLinux": "stop-yarn.sh || kill -9 $(lsof -t -i:8088)",
  "killCommandWin": "Stop-Process -Id (Get-NetTCPConnection -LocalPort 8088).OwningProcess -Force",
  "checkCommandLinux": "curl -I http://localhost:8088/ws/v1/cluster/info",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 8088",
  "firewallUfw": "sudo ufw allow from 10.0.0.0/8 to any port 8088 proto tcp",
  "dockerRun": "docker run -d -p 8088:8088 bde2020/hadoop-resourcemanager",
  "commonError": "YARN ResourceManager unreachable on port 8088."
},
  {
  "port": 8443,
  "slug": "port-8443",
  "name": "Port 8443",
  "service": "HTTPS Alternate / UniFi Controller / Tomcat SSL",
  "protocol": "TCP",
  "category": "Web & Dev",
  "description": "Port 8443 is the standard secondary SSL/TLS encrypted HTTPS port used by Apache Tomcat, UniFi Network Controllers, Jenkins, and client web dashboards without requiring root privileges.",
  "defaultProcess": "java, node, unifi",
  "riskLevel": "Medium",
  "securityNote": "Ensure the SSL certificate matches the domain to prevent client browser warning screens.",
  "killCommandLinux": "kill -9 $(lsof -t -i:8443)",
  "killCommandWin": "Stop-Process -Id (Get-NetTCPConnection -LocalPort 8443).OwningProcess -Force",
  "checkCommandLinux": "curl -k -I https://localhost:8443",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 8443",
  "firewallUfw": "sudo ufw allow 8443/tcp",
  "dockerRun": "docker run -p 8443:8443 -d my-secure-app",
  "commonError": "Failed to bind to HTTPS port 8443: Address already in use."
},
  {
  "port": 8500,
  "slug": "port-8500",
  "name": "Port 8500",
  "service": "HashiCorp Consul HTTP API & Dashboard",
  "protocol": "TCP",
  "category": "DevOps & Cloud",
  "description": "Port 8500 is the HTTP API and web management UI port for HashiCorp Consul service discovery, service mesh, and distributed key-value configuration.",
  "defaultProcess": "consul",
  "riskLevel": "High",
  "securityNote": "Enforce ACL tokens on all Consul HTTP endpoints to prevent unauthorized cluster service registration.",
  "killCommandLinux": "sudo systemctl stop consul || kill -9 $(lsof -t -i:8500)",
  "killCommandWin": "Stop-Process -Name consul -Force",
  "checkCommandLinux": "curl http://localhost:8500/v1/status/leader",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 8500",
  "firewallUfw": "sudo ufw allow from 10.0.0.0/8 to any port 8500 proto tcp",
  "dockerRun": "docker run -d -p 8500:8500 hashicorp/consul:latest",
  "commonError": "Consul agent returned 500 / Connection refused on port 8500."
},
  {
  "port": 8888,
  "slug": "port-8888",
  "name": "Port 8888",
  "service": "Jupyter Notebook / Data Science Server",
  "protocol": "TCP",
  "category": "Web & Dev",
  "description": "Port 8888 is the default listening port for Jupyter Notebook and JupyterLab interactive Python computational environments.",
  "defaultProcess": "python, jupyter-lab",
  "riskLevel": "High",
  "securityNote": "Never disable notebook token authentication when running Jupyter on remote servers, as arbitrary code execution is allowed by design in notebooks.",
  "killCommandLinux": "jupyter notebook stop 8888 || kill -9 $(lsof -t -i:8888)",
  "killCommandWin": "Stop-Process -Id (Get-NetTCPConnection -LocalPort 8888).OwningProcess -Force",
  "checkCommandLinux": "jupyter notebook list || sudo lsof -i :8888",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 8888",
  "firewallUfw": "sudo ufw allow from 127.0.0.1 to any port 8888 proto tcp",
  "dockerRun": "docker run -p 8888:8888 -d jupyter/scipy-notebook",
  "commonError": "The port 8888 is already in use, trying another port."
},
  {
  "port": 9000,
  "slug": "port-9000",
  "name": "Port 9000",
  "service": "SonarQube / PHP-FPM / MinIO S3 API",
  "protocol": "TCP",
  "category": "DevOps & Cloud",
  "description": "Port 9000 is widely used by SonarQube code quality servers, PHP-FPM FastCGI listeners, MinIO Object Storage S3 APIs, and Portainer Docker management.",
  "defaultProcess": "java (sonarqube), php-fpm, minio",
  "riskLevel": "Medium",
  "securityNote": "Ensure the default administrator password is changed immediately upon initial SonarQube setup.",
  "killCommandLinux": "kill -9 $(lsof -t -i:9000)",
  "killCommandWin": "Stop-Process -Id (Get-NetTCPConnection -LocalPort 9000).OwningProcess -Force",
  "checkCommandLinux": "sudo lsof -i :9000 || sudo ss -tulpn | grep \":9000 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 9000",
  "firewallUfw": "sudo ufw allow 9000/tcp",
  "dockerRun": "docker run -d -p 9000:9000 sonarqube:lts-community",
  "commonError": "SonarQube server startup failed: Port 9000 is occupied."
},
  {
  "port": 9100,
  "slug": "port-9100",
  "name": "Port 9100",
  "service": "Prometheus Node Exporter",
  "protocol": "TCP",
  "category": "DevOps & Cloud",
  "description": "Port 9100 is the standard HTTP scraping metrics port for Prometheus Node Exporter, publishing real-time host CPU, memory, disk, and network stats.",
  "defaultProcess": "node_exporter",
  "riskLevel": "Low",
  "securityNote": "Node Exporter outputs detailed server hardware specs and kernel details. Restrict scraping to authorized Prometheus server IPs.",
  "killCommandLinux": "sudo systemctl stop node_exporter || kill -9 $(lsof -t -i:9100)",
  "killCommandWin": "Stop-Process -Name node_exporter -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "curl -s http://localhost:9100/metrics | head -n 10",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 9100",
  "firewallUfw": "sudo ufw allow from 10.0.0.0/8 to any port 9100 proto tcp",
  "dockerRun": "docker run -d -p 9100:9100 prom/node-exporter",
  "commonError": "Prometheus server scraping error: dial tcp :9100: connect: connection refused."
},
  {
  "port": 9300,
  "slug": "port-9300",
  "name": "Port 9300",
  "service": "Elasticsearch Cluster Transport Communication",
  "protocol": "TCP",
  "category": "Database",
  "description": "Port 9300 is the internal cluster transport port utilized by Elasticsearch nodes to communicate, distribute shards, and execute master node elections.",
  "defaultProcess": "java (elasticsearch)",
  "riskLevel": "High",
  "securityNote": "Ensure xpack.security.transport.ssl is enabled so inter-node cluster data is encrypted across VPC networks.",
  "killCommandLinux": "sudo systemctl stop elasticsearch",
  "killCommandWin": "Stop-Service elasticsearch-service-x64 -Force",
  "checkCommandLinux": "sudo lsof -i :9300 || sudo ss -tulpn | grep \":9300 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 9300",
  "firewallUfw": "sudo ufw allow from 10.0.0.0/8 to any port 9300 proto tcp",
  "dockerRun": "docker run -d -p 9200:9200 -p 9300:9300 elasticsearch:8.12.0",
  "commonError": "NodeDisconnectedException: disconnected from node on port 9300."
},
  {
  "port": 9411,
  "slug": "port-9411",
  "name": "Port 9411",
  "service": "Zipkin Distributed Tracing",
  "protocol": "TCP",
  "category": "DevOps & Cloud",
  "description": "Port 9411 is the primary HTTP ingestion and query dashboard port for OpenZipkin distributed request tracing across microservice architectures.",
  "defaultProcess": "java (zipkin)",
  "riskLevel": "Low",
  "securityNote": "Internal observability tool. Isolate behind an authenticated internal ingress.",
  "killCommandLinux": "kill -9 $(lsof -t -i:9411)",
  "killCommandWin": "Stop-Process -Id (Get-NetTCPConnection -LocalPort 9411).OwningProcess -Force",
  "checkCommandLinux": "curl -I http://localhost:9411/health",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 9411",
  "firewallUfw": "sudo ufw allow 9411/tcp",
  "dockerRun": "docker run -d -p 9411:9411 openzipkin/zipkin",
  "commonError": "Zipkin trace submission failed: Connection refused on port 9411."
},
  {
  "port": 9999,
  "slug": "port-9999",
  "name": "Port 9999",
  "service": "JMX Remote Monitoring / Urchin / Akka",
  "protocol": "TCP",
  "category": "DevOps & Cloud",
  "description": "Port 9999 is frequently designated for Java JMX remote management, Akka remoting, and local custom microservice debugging.",
  "defaultProcess": "java",
  "riskLevel": "Critical",
  "securityNote": "Unauthenticated JMX listeners on port 9999 allow remote code execution via MBean deserialization attacks. Never expose JMX without authentication and SSL.",
  "killCommandLinux": "kill -9 $(lsof -t -i:9999)",
  "killCommandWin": "Stop-Process -Id (Get-NetTCPConnection -LocalPort 9999).OwningProcess -Force",
  "checkCommandLinux": "sudo lsof -i :9999 || sudo ss -tulpn | grep \":9999 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 9999",
  "firewallUfw": "sudo ufw deny 9999/tcp",
  "dockerRun": "docker run -p 9999:9999 -d my-java-app",
  "commonError": "Failed to connect to JMX connector on port 9999: Connection refused."
},
  {
  "port": 10250,
  "slug": "port-10250",
  "name": "Port 10250",
  "service": "Kubernetes Kubelet API",
  "protocol": "TCP",
  "category": "DevOps & Cloud",
  "description": "Port 10250 is the HTTPS listening port for the Kubernetes Kubelet daemon on worker nodes, allowing control plane components to query node stats and execute pod commands.",
  "defaultProcess": "kubelet",
  "riskLevel": "Critical",
  "securityNote": "If --anonymous-auth=true is enabled, attackers can query Kubelet port 10250 to execute arbitrary commands inside running containers (exec/run). Require webhook/certificate authentication.",
  "killCommandLinux": "sudo systemctl stop kubelet || kill -9 $(lsof -t -i:10250)",
  "killCommandWin": "Stop-Service kubelet -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "curl -k -I https://localhost:10250/pods",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 10250",
  "firewallUfw": "sudo ufw allow from 10.0.0.0/8 to any port 10250 proto tcp",
  "dockerRun": "# Kubelet runs directly on node host rather than standard container",
  "commonError": "Unauthorized error 401 when communicating with Kubelet on port 10250."
},
  {
  "port": 11211,
  "slug": "port-11211",
  "name": "Port 11211",
  "service": "Memcached In-Memory Cache",
  "protocol": "TCP/UDP",
  "category": "Messaging & Cache",
  "description": "Port 11211 is the default port for Memcached, a high-performance in-memory key-value caching system used to accelerate database-driven web apps.",
  "defaultProcess": "memcached",
  "riskLevel": "High",
  "securityNote": "Exposed UDP port 11211 was historically responsible for the largest DDoS reflection amplification attacks in internet history (>1.3 Tbps). Bind Memcached exclusively to 127.0.0.1 and disable UDP (-U 0).",
  "killCommandLinux": "sudo systemctl stop memcached || sudo killall memcached",
  "killCommandWin": "Stop-Service memcached -Force -ErrorAction SilentlyContinue",
  "checkCommandLinux": "echo stats | nc localhost 11211 || sudo lsof -i :11211",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 11211",
  "firewallUfw": "sudo ufw allow from 127.0.0.1 to any port 11211 proto tcp",
  "dockerRun": "docker run -d -p 11211:11211 memcached:alpine memcached -m 64",
  "commonError": "Memcached::get(): Failed to connect to server on port 11211: Connection refused."
},
  {
  "port": 28017,
  "slug": "port-28017",
  "name": "Port 28017",
  "service": "MongoDB HTTP Web Admin Interface",
  "protocol": "TCP",
  "category": "Database",
  "description": "Port 28017 was the legacy HTTP status and web diagnostic interface for MongoDB database instances (offset 1000 from port 27017).",
  "defaultProcess": "mongod",
  "riskLevel": "Critical",
  "securityNote": "Legacy MongoDB HTTP console on port 28017 leaked database names, collections, and server statistics. Deprecated and disabled in modern MongoDB versions.",
  "killCommandLinux": "sudo systemctl stop mongod",
  "killCommandWin": "Stop-Service MongoDB -Force",
  "checkCommandLinux": "sudo lsof -i :28017 || sudo ss -tulpn | grep \":28017 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 28017",
  "firewallUfw": "sudo ufw deny 28017/tcp",
  "dockerRun": "# Deprecated; use MongoDB Compass or modern admin panels instead",
  "commonError": "HTTP 403 / REST interface is disabled on port 28017."
},
  {
  "port": 50000,
  "slug": "port-50000",
  "name": "Port 50000",
  "service": "Jenkins Inbound Agent (JNLP) Listener",
  "protocol": "TCP",
  "category": "DevOps & Cloud",
  "description": "Port 50000 is the default TCP port for Jenkins controller servers to communicate with inbound JNLP (Java Network Launch Protocol) build agents and worker nodes.",
  "defaultProcess": "java (jenkins)",
  "riskLevel": "High",
  "securityNote": "Restrict port 50000 strictly to build agent IP addresses. Disable JNLP protocols that do not use modern TLS encryption.",
  "killCommandLinux": "sudo systemctl stop jenkins",
  "killCommandWin": "Stop-Service Jenkins -Force",
  "checkCommandLinux": "sudo lsof -i :50000 || sudo ss -tulpn | grep \":50000 \"",
  "checkCommandWin": "Get-NetTCPConnection -LocalPort 50000",
  "firewallUfw": "sudo ufw allow from 10.0.0.0/8 to any port 50000 proto tcp",
  "dockerRun": "docker run -p 8080:8080 -p 50000:50000 -d jenkins/jenkins:lts",
  "commonError": "Jenkins agent failed to connect to controller on port 50000: Connection refused."
}
];



export function getAllPorts(): PortData[] {
  return PORTS_DATA;
}

export function getPortBySlug(slug: string): PortData | undefined {
  return PORTS_DATA.find((p) => p.slug === slug);
}
