export interface PortData {
  port: number;
  slug: string;
  name: string;
  service: string;
  protocol: 'TCP' | 'UDP' | 'TCP/UDP';
  category: 'Web & Dev' | 'Database' | 'DevOps & Cloud' | 'Networking' | 'Messaging & Cache' | 'Security';
  description: string;
  defaultProcess: string;
  riskLevel: 'Low' | 'Medium' | 'High' | 'Critical';
  securityNote: string;
  killCommandLinux: string;
  killCommandWin: string;
  checkCommandLinux: string;
  checkCommandWin: string;
  firewallUfw: string;
  dockerRun: string;
  commonError: string;
}

export const PORTS_DATA: PortData[] = [
  // --- Web & Dev Servers ---
  {
    port: 3000,
    slug: 'port-3000',
    name: 'Port 3000',
    service: 'React / Next.js / Node.js Dev Server',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 3000 is the industry-standard default local development port for Node.js applications, Create React App, Next.js, Express, and Ruby on Rails. When starting a local development server, this is usually the primary listener.',
    defaultProcess: 'node, npm, next-server',
    riskLevel: 'Low',
    securityNote: 'Never expose port 3000 to 0.0.0.0 on production servers without a reverse proxy (like NGINX or Caddy) handling SSL/TLS encryption and rate limiting.',
    killCommandLinux: 'kill -9 $(lsof -t -i:3000)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 3000).OwningProcess -Force',
    checkCommandLinux: 'lsof -i :3000 || ss -tulpn | grep 3000',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 3000',
    firewallUfw: 'sudo ufw allow 3000/tcp',
    dockerRun: 'docker run -p 3000:3000 -d my-node-app',
    commonError: 'Error: listen EADDRINUSE: address already in use :::3000',
  },
  {
    port: 8080,
    slug: 'port-8080',
    name: 'Port 8080',
    service: 'HTTP Alternate / Tomcat / Spring Boot / Vue CLI',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 8080 is the standard HTTP alternate port used by Apache Tomcat, Spring Boot, Vue CLI, Jenkins, and proxy services. It provides unprivileged HTTP serving without requiring root/admin access.',
    defaultProcess: 'java, node, jenkins',
    riskLevel: 'Medium',
    securityNote: 'Frequently targeted by automated scanners looking for exposed Tomcat management dashboards, Jenkins instances, or proxy misconfigurations.',
    killCommandLinux: 'kill -9 $(lsof -t -i:8080)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 8080).OwningProcess -Force',
    checkCommandLinux: 'lsof -i :8080 || ss -tulpn | grep 8080',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 8080',
    firewallUfw: 'sudo ufw allow 8080/tcp',
    dockerRun: 'docker run -p 8080:8080 -d my-spring-app',
    commonError: 'Web server failed to start. Port 8080 was already in use.',
  },
  {
    port: 5173,
    slug: 'port-5173',
    name: 'Port 5173',
    service: 'Vite Dev Server (Vue, Svelte, React)',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 5173 is the default port assigned by the Vite build tool and development server for modern frontend frameworks (Vue 3, Svelte, React, Solid).',
    defaultProcess: 'vite, node',
    riskLevel: 'Low',
    securityNote: 'Local development server. If Vite switches to 5174 or 5175, an existing Vite or background process is still bound to 5173.',
    killCommandLinux: 'kill -9 $(lsof -t -i:5173)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 5173).OwningProcess -Force',
    checkCommandLinux: 'lsof -i :5173',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 5173',
    firewallUfw: 'sudo ufw allow 5173/tcp',
    dockerRun: 'docker run -p 5173:5173 -d my-vite-app',
    commonError: 'Port 5173 is in use, trying another one... -> http://localhost:5174/',
  },
  {
    port: 80,
    slug: 'port-80',
    name: 'Port 80',
    service: 'HTTP (Hypertext Transfer Protocol)',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 80 is the global IANA standard port for unencrypted World Wide Web (HTTP) traffic. All web browsers default to port 80 when http:// is specified.',
    defaultProcess: 'nginx, apache2, httpd, caddy',
    riskLevel: 'Medium',
    securityNote: 'Traffic is completely unencrypted. Modern security standards mandate redirecting all incoming Port 80 requests to Port 443 (HTTPS) with HSTS headers.',
    killCommandLinux: 'sudo kill -9 $(sudo lsof -t -i:80)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 80).OwningProcess -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep :80',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 80',
    firewallUfw: 'sudo ufw allow 80/tcp',
    dockerRun: 'docker run -p 80:80 -d nginx:alpine',
    commonError: 'nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)',
  },
  {
    port: 443,
    slug: 'port-443',
    name: 'Port 443',
    service: 'HTTPS (HTTP over TLS/SSL)',
    protocol: 'TCP/UDP',
    category: 'Web & Dev',
    description: 'Port 443 is the standard port for encrypted secure web communications (HTTPS) and HTTP/3 (QUIC over UDP). It provides end-to-end cryptographic confidentiality and server identity validation.',
    defaultProcess: 'nginx, apache2, caddy, traefik',
    riskLevel: 'Low',
    securityNote: 'Ensure modern TLS configurations (TLS 1.2/1.3 only, disable SSLv3/TLS 1.0/1.1) and implement automated Let\'s Encrypt certificate renewal.',
    killCommandLinux: 'sudo kill -9 $(sudo lsof -t -i:443)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 443).OwningProcess -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep :443',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 443',
    firewallUfw: 'sudo ufw allow 443/tcp && sudo ufw allow 443/udp',
    dockerRun: 'docker run -p 443:443 -d caddy:alpine',
    commonError: 'Failed to bind to HTTPS port 443. Check TLS certificate permissions.',
  },
  {
    port: 5000,
    slug: 'port-5000',
    name: 'Port 5000',
    service: 'Flask / Python Web / Docker Registry',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 5000 is the default port used by Python Flask, ASP.NET Core, and the official Docker Registry. On macOS Monterey and later, Apple AirPlay Receiver binds to 5000 by default.',
    defaultProcess: 'python, flask, AirPlayXPCHelper',
    riskLevel: 'Low',
    securityNote: 'On macOS, disable "AirPlay Receiver" in System Settings > Sharing if port 5000 causes conflict errors with your Python or Docker servers.',
    killCommandLinux: 'kill -9 $(lsof -t -i:5000)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 5000).OwningProcess -Force',
    checkCommandLinux: 'lsof -i :5000',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 5000',
    firewallUfw: 'sudo ufw allow 5000/tcp',
    dockerRun: 'docker run -p 5000:5000 -d registry:2',
    commonError: 'OSError: [Errno 48] Address already in use (Often macOS AirPlay on port 5000)',
  },
  {
    port: 8000,
    slug: 'port-8000',
    name: 'Port 8000',
    service: 'Django / FastAPI / Python SimpleHTTP',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 8000 is the default development port for Python Django (`python manage.py runserver`), FastAPI (uvicorn), and `python -m http.server 8000`.',
    defaultProcess: 'python, uvicorn, gunicorn',
    riskLevel: 'Low',
    securityNote: 'Django\'s built-in development server is not hardened for production. Never run `runserver` directly on a public internet IP.',
    killCommandLinux: 'kill -9 $(lsof -t -i:8000)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 8000).OwningProcess -Force',
    checkCommandLinux: 'lsof -i :8000',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 8000',
    firewallUfw: 'sudo ufw allow 8000/tcp',
    dockerRun: 'docker run -p 8000:8000 -d my-fastapi-app',
    commonError: 'Error: That port is already in use by another Django or Uvicorn instance.',
  },
  {
    port: 4200,
    slug: 'port-4200',
    name: 'Port 4200',
    service: 'Angular CLI Dev Server',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 4200 is the default port used by Angular CLI (`ng serve`) during frontend application development.',
    defaultProcess: 'node, ng',
    riskLevel: 'Low',
    securityNote: 'Development server only. If 4200 is busy, launch with `ng serve --port 4300`.',
    killCommandLinux: 'kill -9 $(lsof -t -i:4200)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 4200).OwningProcess -Force',
    checkCommandLinux: 'lsof -i :4200',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 4200',
    firewallUfw: 'sudo ufw allow 4200/tcp',
    dockerRun: 'docker run -p 4200:4200 -d my-angular-app',
    commonError: 'Port 4200 is already in use. Use \'--port\' to specify a different port.',
  },
  {
    port: 3001,
    slug: 'port-3001',
    name: 'Port 3001',
    service: 'Secondary Node / Express Backend API',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 3001 is commonly used as the companion backend API port when a React/Next.js frontend occupies port 3000, preventing CORS and port collision issues.',
    defaultProcess: 'node, express',
    riskLevel: 'Low',
    securityNote: 'Ensure proper CORS headers (`Access-Control-Allow-Origin: http://localhost:3000`) are configured between frontend and backend.',
    killCommandLinux: 'kill -9 $(lsof -t -i:3001)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 3001).OwningProcess -Force',
    checkCommandLinux: 'lsof -i :3001',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 3001',
    firewallUfw: 'sudo ufw allow 3001/tcp',
    dockerRun: 'docker run -p 3001:3001 -d my-api',
    commonError: 'Error: listen EADDRINUSE :::3001',
  },

  // --- Databases ---
  {
    port: 5432,
    slug: 'port-5432',
    name: 'Port 5432',
    service: 'PostgreSQL Database',
    protocol: 'TCP',
    category: 'Database',
    description: 'Port 5432 is the official IANA assigned port for the PostgreSQL relational database management system. PostgreSQL servers listen on this port for incoming SQL client connections.',
    defaultProcess: 'postgres, pg_ctl',
    riskLevel: 'High',
    securityNote: 'Never bind PostgreSQL to 0.0.0.0 without strict pg_hba.conf IP whitelisting and SSL connection enforcement (ssl=on). Restrict access to localhost or your VPC subnet.',
    killCommandLinux: 'sudo systemctl stop postgresql || sudo kill -9 $(sudo lsof -t -i:5432)',
    killCommandWin: 'Stop-Service postgresql* -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep 5432 || pg_isready -p 5432',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 5432',
    firewallUfw: 'sudo ufw allow from 10.0.0.0/16 to any port 5432 proto tcp',
    dockerRun: 'docker run -p 5432:5432 -e POSTGRES_PASSWORD=securepass -d postgres:16',
    commonError: 'could not connect to server: Connection refused. Is the server running on host "localhost" and accepting TCP/IP connections on port 5432?',
  },
  {
    port: 3306,
    slug: 'port-3306',
    name: 'Port 3306',
    service: 'MySQL / MariaDB Database',
    protocol: 'TCP',
    category: 'Database',
    description: 'Port 3306 is the default port for MySQL and MariaDB databases worldwide. Client libraries (mysql2, PDO, PyMySQL) default to this port for connections.',
    defaultProcess: 'mysqld, mariadbd',
    riskLevel: 'High',
    securityNote: 'Ensure the root user cannot log in remotely (`bind-address = 127.0.0.1` in my.cnf). Use strong user passwords and disable LOAD DATA LOCAL INFILE.',
    killCommandLinux: 'sudo systemctl stop mysql || sudo kill -9 $(sudo lsof -t -i:3306)',
    killCommandWin: 'Stop-Service MySQL* -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep 3306 || mysqladmin ping',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 3306',
    firewallUfw: 'sudo ufw allow from 192.168.1.0/24 to any port 3306 proto tcp',
    dockerRun: 'docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD=secret -d mysql:8',
    commonError: 'ERROR 2003 (HY000): Can\'t connect to MySQL server on \'127.0.0.1:3306\' (111)',
  },
  {
    port: 27017,
    slug: 'port-27017',
    name: 'Port 27017',
    service: 'MongoDB NoSQL Database',
    protocol: 'TCP',
    category: 'Database',
    description: 'Port 27017 is the default listening port for MongoDB daemon (`mongod`) and routing service (`mongos`).',
    defaultProcess: 'mongod',
    riskLevel: 'Critical',
    securityNote: 'CRITICAL SECURITY RISK: Thousands of unauthenticated MongoDB databases have been ransomed by exposing 27017 to the public internet. Always enable authentication (`security.authorization: enabled`) and bind to 127.0.0.1.',
    killCommandLinux: 'sudo systemctl stop mongod || sudo kill -9 $(sudo lsof -t -i:27017)',
    killCommandWin: 'Stop-Service MongoDB -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep 27017',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 27017',
    firewallUfw: 'sudo ufw deny 27017',
    dockerRun: 'docker run -p 27017:27017 -d mongo:latest',
    commonError: 'MongoNetworkError: failed to connect to server [localhost:27017] on first connect',
  },
  {
    port: 6379,
    slug: 'port-6379',
    name: 'Port 6379',
    service: 'Redis In-Memory Key-Value Store',
    protocol: 'TCP',
    category: 'Messaging & Cache',
    description: 'Port 6379 is the default port for Redis in-memory cache and message broker. The number 6379 corresponds to the letters "MERZ" on a telephone keypad (named after Italian singer Alessia Merz).',
    defaultProcess: 'redis-server',
    riskLevel: 'Critical',
    securityNote: 'CRITICAL: Redis is designed to be accessed by trusted clients inside a secure private network. Publicly exposed Redis instances without passwords (`requirepass`) are regularly compromised by crypto-miners.',
    killCommandLinux: 'sudo systemctl stop redis || sudo kill -9 $(sudo lsof -t -i:6379)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 6379).OwningProcess -Force',
    checkCommandLinux: 'redis-cli ping || sudo ss -tulpn | grep 6379',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 6379',
    firewallUfw: 'sudo ufw deny 6379',
    dockerRun: 'docker run -p 6379:6379 -d redis:alpine redis-server --requirepass securepass',
    commonError: 'Could not connect to Redis at 127.0.0.1:6379: Connection refused',
  },
  {
    port: 1433,
    slug: 'port-1433',
    name: 'Port 1433',
    service: 'Microsoft SQL Server (MS SQL)',
    protocol: 'TCP',
    category: 'Database',
    description: 'Port 1433 is the official standard port assigned for Microsoft SQL Server instances.',
    defaultProcess: 'sqlservr.exe',
    riskLevel: 'High',
    securityNote: 'Frequently targeted by SQL brute-force attacks. Disable the `sa` account or assign a 25+ character random password, and enable SQL Server audit logging.',
    killCommandLinux: 'sudo systemctl stop mssql-server',
    killCommandWin: 'Stop-Service MSSQLSERVER -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep 1433',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 1433',
    firewallUfw: 'sudo ufw allow from 10.0.0.0/8 to any port 1433 proto tcp',
    dockerRun: 'docker run -p 1433:1433 -e ACCEPT_EULA=Y -e SA_PASSWORD=YourStrong@Pass -d mcr.microsoft.com/mssql/server:2022-latest',
    commonError: 'Cannot open database requested by the login. Connection to localhost:1433 failed.',
  },
  {
    port: 1521,
    slug: 'port-1521',
    name: 'Port 1521',
    service: 'Oracle Database Listener',
    protocol: 'TCP',
    category: 'Database',
    description: 'Port 1521 is the default port for the Oracle Database TNS (Transparent Network Substrate) Listener.',
    defaultProcess: 'tnslsnr, oracle',
    riskLevel: 'High',
    securityNote: 'Oracle listeners can reveal database version information and SID names. Implement Valid Node Checking (COST) to restrict unauthorized client hosts.',
    killCommandLinux: 'lsnrctl stop',
    killCommandWin: 'Stop-Service OracleOraDB* -Force',
    checkCommandLinux: 'lsnrctl status',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 1521',
    firewallUfw: 'sudo ufw deny 1521',
    dockerRun: 'docker run -p 1521:1521 -d container-registry.oracle.com/database/free:latest',
    commonError: 'ORA-12541: TNS:no listener on port 1521',
  },
  {
    port: 9200,
    slug: 'port-9200',
    name: 'Port 9200',
    service: 'Elasticsearch / OpenSearch REST API',
    protocol: 'TCP',
    category: 'Database',
    description: 'Port 9200 is used by Elasticsearch and OpenSearch for handling JSON HTTP REST queries, indexing documents, and cluster management.',
    defaultProcess: 'java, elasticsearch',
    riskLevel: 'Critical',
    securityNote: 'Ensure X-Pack security (`xpack.security.enabled: true`) is active. Never expose port 9200 to public internet without basic authentication and TLS.',
    killCommandLinux: 'sudo systemctl stop elasticsearch || sudo kill -9 $(sudo lsof -t -i:9200)',
    killCommandWin: 'Stop-Service elasticsearch -Force',
    checkCommandLinux: 'curl -I http://localhost:9200',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 9200',
    firewallUfw: 'sudo ufw deny 9200',
    dockerRun: 'docker run -p 9200:9200 -e discovery.type=single-node -d elasticsearch:8.10.0',
    commonError: 'Connection refused: could not reach Elasticsearch REST API at localhost:9200',
  },

  // --- DevOps & Cloud & Containers ---
  {
    port: 2375,
    slug: 'port-2375',
    name: 'Port 2375',
    service: 'Docker REST API (Unencrypted)',
    protocol: 'TCP',
    category: 'DevOps & Cloud',
    description: 'Port 2375 is used for unencrypted HTTP communication with the Docker engine daemon.',
    defaultProcess: 'dockerd',
    riskLevel: 'Critical',
    securityNote: 'SEVERE SECURITY HAZARD: Exposing port 2375 without TLS allows anyone with network access to run root-level containers and take over the host operating system. Always use TLS (port 2376) or local UNIX socket `/var/run/docker.sock`.',
    killCommandLinux: 'sudo systemctl stop docker',
    killCommandWin: 'Stop-Service docker -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep 2375',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 2375',
    firewallUfw: 'sudo ufw deny 2375',
    dockerRun: 'dockerd -H tcp://0.0.0.0:2375',
    commonError: 'Cannot connect to the Docker daemon at tcp://localhost:2375. Is the docker daemon running?',
  },
  {
    port: 2376,
    slug: 'port-2376',
    name: 'Port 2376',
    service: 'Docker REST API (TLS Encrypted)',
    protocol: 'TCP',
    category: 'DevOps & Cloud',
    description: 'Port 2376 is the official secure port for Docker daemon API communication using mutual TLS authentication.',
    defaultProcess: 'dockerd',
    riskLevel: 'High',
    securityNote: 'Ensure client certificates are signed by a trusted CA and verified before authorizing any Docker container commands.',
    killCommandLinux: 'sudo systemctl restart docker',
    killCommandWin: 'Restart-Service docker',
    checkCommandLinux: 'sudo ss -tulpn | grep 2376',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 2376',
    firewallUfw: 'sudo ufw allow 2376/tcp',
    dockerRun: 'dockerd --tlsverify --tlscacert=ca.pem --tlscert=server-cert.pem --tlskey=server-key.pem -H tcp://0.0.0.0:2376',
    commonError: 'tls: bad certificate error communicating with Docker daemon on port 2376',
  },
  {
    port: 6443,
    slug: 'port-6443',
    name: 'Port 6443',
    service: 'Kubernetes API Server',
    protocol: 'TCP',
    category: 'DevOps & Cloud',
    description: 'Port 6443 is the default port used by `kube-apiserver` for secure communication within a Kubernetes cluster and for external `kubectl` command management.',
    defaultProcess: 'kube-apiserver',
    riskLevel: 'High',
    securityNote: 'Protect this port with RBAC authorization, audit logging, and never allow anonymous authentication (`--anonymous-auth=false`).',
    killCommandLinux: 'sudo systemctl restart kubelet',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 6443).OwningProcess -Force',
    checkCommandLinux: 'kubectl cluster-info || sudo ss -tulpn | grep 6443',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 6443',
    firewallUfw: 'sudo ufw allow 6443/tcp',
    dockerRun: 'minikube start --apiserver-port=6443',
    commonError: 'Unable to connect to the server: dial tcp 127.0.0.1:6443: connect: connection refused',
  },
  {
    port: 9090,
    slug: 'port-9090',
    name: 'Port 9090',
    service: 'Prometheus Server Web UI & Metrics API',
    protocol: 'TCP',
    category: 'DevOps & Cloud',
    description: 'Port 9090 is the default web UI and PromQL querying interface for the Prometheus monitoring system.',
    defaultProcess: 'prometheus',
    riskLevel: 'Medium',
    securityNote: 'Prometheus does not include native authentication by default. Put it behind an authenticating reverse proxy or enable web configuration basic auth.',
    killCommandLinux: 'kill -9 $(lsof -t -i:9090)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 9090).OwningProcess -Force',
    checkCommandLinux: 'curl -I http://localhost:9090/-/healthy',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 9090',
    firewallUfw: 'sudo ufw allow from 10.0.0.0/8 to any port 9090 proto tcp',
    dockerRun: 'docker run -p 9090:9090 -d prom/prometheus',
    commonError: 'Prometheus server startup failed: address already in use on port 9090',
  },
  {
    port: 11434,
    slug: 'port-11434',
    name: 'Port 11434',
    service: 'Ollama AI / Local LLM Server',
    protocol: 'TCP',
    category: 'Web & Dev',
    description: 'Port 11434 is the default API port used by Ollama to run large language models (Llama 3, Mistral, Gemma) locally on CPU and GPU.',
    defaultProcess: 'ollama',
    riskLevel: 'Medium',
    securityNote: 'By default, Ollama binds to 127.0.0.1. Do not set OLLAMA_HOST=0.0.0.0 on an untrusted network as it has no authentication and allows downloading and running arbitrary model weights.',
    killCommandLinux: 'kill -9 $(lsof -t -i:11434)',
    killCommandWin: 'Stop-Process -Name "ollama app", "ollama" -Force',
    checkCommandLinux: 'curl http://localhost:11434/api/version',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 11434',
    firewallUfw: 'sudo ufw deny 11434',
    dockerRun: 'docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama',
    commonError: 'could not connect to ollama app on localhost:11434, is it running?',
  },

  // --- Networking & Protocols ---
  {
    port: 22,
    slug: 'port-22',
    name: 'Port 22',
    service: 'SSH (Secure Shell) & SFTP',
    protocol: 'TCP',
    category: 'Networking',
    description: 'Port 22 is the standard port used for Secure Shell (SSH) remote command execution, secure file transfer (SFTP), and Git over SSH (`git@github.com`).',
    defaultProcess: 'sshd',
    riskLevel: 'Critical',
    securityNote: 'Public port 22 is under constant brute-force dictionary attack. Disable password authentication (`PasswordAuthentication no`), disable root login (`PermitRootLogin no`), and install Fail2ban.',
    killCommandLinux: 'sudo systemctl restart sshd',
    killCommandWin: 'Stop-Service sshd -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep :22',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 22',
    firewallUfw: 'sudo ufw allow 22/tcp',
    dockerRun: 'docker run -p 2222:22 -d my-ssh-server',
    commonError: 'ssh: connect to host example.com port 22: Connection refused / Connection timed out',
  },
  {
    port: 53,
    slug: 'port-53',
    name: 'Port 53',
    service: 'DNS (Domain Name System)',
    protocol: 'TCP/UDP',
    category: 'Networking',
    description: 'Port 53 handles Domain Name System queries, translating human-readable hostnames (e.g. google.com) into numeric IP addresses (e.g. 142.250.190.46). UDP is used for standard queries; TCP is used for large zone transfers.',
    defaultProcess: 'named, dnsmasq, systemd-resolved',
    riskLevel: 'High',
    securityNote: 'Open DNS resolvers can be weaponized in massive Distributed Denial of Service (DDoS) DNS amplification attacks. Never leave recursive DNS open to the general internet.',
    killCommandLinux: 'sudo systemctl restart systemd-resolved',
    killCommandWin: 'Stop-Service Dnscache -Force',
    checkCommandLinux: 'dig @localhost google.com || sudo ss -ulpn | grep :53',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 53',
    firewallUfw: 'sudo ufw allow 53',
    dockerRun: 'docker run -p 53:53/udp -p 53:53/tcp -d pihole/pihole',
    commonError: 'listen udp 0.0.0.0:53: bind: address already in use (frequently Ubuntu systemd-resolved)',
  },
  {
    port: 21,
    slug: 'port-21',
    name: 'Port 21',
    service: 'FTP (File Transfer Protocol Control)',
    protocol: 'TCP',
    category: 'Networking',
    description: 'Port 21 is the command control port for standard File Transfer Protocol. Data transfer occurs over port 20 or dynamic passive ports.',
    defaultProcess: 'vsftpd, proftpd, pure-ftpd',
    riskLevel: 'Critical',
    securityNote: 'FTP transmits usernames and passwords in clear text over the wire. Deprecate FTP in favor of SFTP (SSH Port 22) or FTPS with mandatory TLS.',
    killCommandLinux: 'sudo systemctl stop vsftpd',
    killCommandWin: 'Stop-Service ftpsvc -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep :21',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 21',
    firewallUfw: 'sudo ufw deny 21/tcp',
    dockerRun: 'docker run -p 21:21 -d fauria/vsftpd',
    commonError: 'ftp: connect: Connection refused on port 21',
  },
  {
    port: 25,
    slug: 'port-25',
    name: 'Port 25',
    service: 'SMTP (Simple Mail Transfer Protocol)',
    protocol: 'TCP',
    category: 'Networking',
    description: 'Port 25 is used by Mail Transfer Agents (MTA) like Postfix and Sendmail for server-to-server email routing.',
    defaultProcess: 'postfix, sendmail, exim',
    riskLevel: 'Critical',
    securityNote: 'Almost all residential ISPs and cloud providers (AWS EC2, Google Cloud, DigitalOcean) block outbound port 25 to stop spam. For sending application emails, use submission ports 587 or 465 with authenticated TLS.',
    killCommandLinux: 'sudo systemctl stop postfix',
    killCommandWin: 'Stop-Service SMTPSVC -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep :25',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 25',
    firewallUfw: 'sudo ufw deny 25/tcp',
    dockerRun: 'docker run -p 25:25 -d namshi/smtp',
    commonError: 'Connection timed out trying to reach mail server on port 25 (Cloud provider blocked)',
  },
  {
    port: 587,
    slug: 'port-587',
    name: 'Port 587',
    service: 'SMTP Submission (STARTTLS)',
    protocol: 'TCP',
    category: 'Networking',
    description: 'Port 587 is the modern standard port for email client-to-server message submission (e.g. SendGrid, Mailgun, Amazon SES) protected by mandatory STARTTLS encryption.',
    defaultProcess: 'postfix, exim4',
    riskLevel: 'Medium',
    securityNote: 'Requires SMTP authentication before relaying any messages to prevent open-relay abuse.',
    killCommandLinux: 'sudo systemctl restart postfix',
    killCommandWin: 'Get-NetTCPConnection -LocalPort 587',
    checkCommandLinux: 'openssl s_client -starttls smtp -connect smtp.gmail.com:587',
    checkCommandWin: 'Test-NetConnection -ComputerName smtp.sendgrid.net -Port 587',
    firewallUfw: 'sudo ufw allow 587/tcp',
    dockerRun: 'docker run -p 587:587 -d my-mail-server',
    commonError: '535 5.7.8 Error: authentication failed on SMTP port 587',
  },

  // --- Messaging & Event Streaming ---
  {
    port: 9092,
    slug: 'port-9092',
    name: 'Port 9092',
    service: 'Apache Kafka Broker',
    protocol: 'TCP',
    category: 'Messaging & Cache',
    description: 'Port 9092 is the default port for Apache Kafka distributed event streaming brokers.',
    defaultProcess: 'java, kafka',
    riskLevel: 'High',
    securityNote: 'Ensure SASL/SCRAM or mTLS authentication is enabled (`listeners=SASL_PLAINTEXT://:9092` or `SSL://:9092`).',
    killCommandLinux: 'kill -9 $(lsof -t -i:9092)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 9092).OwningProcess -Force',
    checkCommandLinux: 'sudo ss -tulpn | grep 9092',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 9092',
    firewallUfw: 'sudo ufw allow from 10.0.0.0/8 to any port 9092 proto tcp',
    dockerRun: 'docker run -p 9092:9092 -d apache/kafka:latest',
    commonError: 'org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms (port 9092)',
  },
  {
    port: 5672,
    slug: 'port-5672',
    name: 'Port 5672',
    service: 'RabbitMQ AMQP Protocol',
    protocol: 'TCP',
    category: 'Messaging & Cache',
    description: 'Port 5672 is the default standard port for the Advanced Message Queuing Protocol (AMQP 0-9-1 and 1.0) utilized by RabbitMQ.',
    defaultProcess: 'beam.smp, rabbitmq',
    riskLevel: 'Medium',
    securityNote: 'Disable the default `guest/guest` account for remote access or restrict it strictly to localhost.',
    killCommandLinux: 'sudo systemctl stop rabbitmq-server',
    killCommandWin: 'Stop-Service RabbitMQ -Force',
    checkCommandLinux: 'sudo rabbitmq-diagnostics check_port_connectivity',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 5672',
    firewallUfw: 'sudo ufw allow 5672/tcp',
    dockerRun: 'docker run -p 5672:5672 -p 15672:15672 -d rabbitmq:3-management',
    commonError: 'AMQP connection failed: Connection refused at localhost:5672',
  },
  {
    port: 15672,
    slug: 'port-15672',
    name: 'Port 15672',
    service: 'RabbitMQ Management Web UI',
    protocol: 'TCP',
    category: 'Messaging & Cache',
    description: 'Port 15672 is the HTTP web management dashboard and REST monitoring API for RabbitMQ.',
    defaultProcess: 'beam.smp',
    riskLevel: 'Medium',
    securityNote: 'Set strong passwords for all administrator accounts and avoid exposing 15672 directly to the internet.',
    killCommandLinux: 'kill -9 $(lsof -t -i:15672)',
    killCommandWin: 'Stop-Process -Id (Get-NetTCPConnection -LocalPort 15672).OwningProcess -Force',
    checkCommandLinux: 'curl -I http://localhost:15672',
    checkCommandWin: 'Get-NetTCPConnection -LocalPort 15672',
    firewallUfw: 'sudo ufw allow 15672/tcp',
    dockerRun: 'docker run -p 15672:15672 -d rabbitmq:management',
    commonError: 'HTTP 401 Unauthorized: Access to management dashboard on 15672 refused.',
  },
];

export function getAllPorts(): PortData[] {
  return PORTS_DATA;
}

export function getPortBySlug(slug: string): PortData | undefined {
  return PORTS_DATA.find((p) => p.slug === slug);
}
