export interface RegexDefinition {
  slug: string;
  title: string;
  category: 'validation' | 'web' | 'formatting' | 'security';
  pattern: string;
  flags: string;
  description: string;
  sampleMatch: string;
  sampleFail: string;
  explanation: string[];
}

export const REGEX_PATTERNS: RegexDefinition[] = [
  {
    slug: 'email-validation-regex',
    title: 'Email Address Validation Regex',
    category: 'validation',
    pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$',
    flags: 'i',
    description: 'Standard RFC-compliant email address validation pattern for form inputs.',
    sampleMatch: 'developer@example.com',
    sampleFail: 'developer@.com',
    explanation: [
      '^[a-zA-Z0-9._%+-]+ : Matches username with allowed email characters',
      '@[a-zA-Z0-9.-]+ : Matches domain name and subdomains',
      '\\.[a-zA-Z]{2,}$ : Matches top-level domain extension (at least 2 letters)',
    ],
  },
  {
    slug: 'strong-password-regex',
    title: 'Strong Password Policy Regex',
    category: 'security',
    pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$',
    flags: '',
    description: 'Enforces minimum 8 chars, at least 1 uppercase, 1 lowercase, 1 digit, and 1 special symbol.',
    sampleMatch: 'P@ssw0rd2026!',
    sampleFail: 'password',
    explanation: [
      '(?=.*[a-z]) : At least one lowercase letter',
      '(?=.*[A-Z]) : At least one uppercase letter',
      '(?=.*\\d) : At least one digit',
      '(?=.*[@$!%*?&]) : At least one special symbol',
      '{8,} : Minimum length of 8 characters',
    ],
  },
  {
    slug: 'url-validation-regex',
    title: 'HTTP/HTTPS URL Validation Regex',
    category: 'web',
    pattern: '^https?:\\/\\/(?:www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b(?:[-a-zA-Z0-9()@:%_\\+.~#?&\\/=]*)$',
    flags: 'i',
    description: 'Validates web URLs including domain, optional port, and query parameter path.',
    sampleMatch: 'https://devtransform-hub.vercel.app/tools/',
    sampleFail: 'htp://invalid-url',
    explanation: [
      '^https?:\\/\\/ : Matches http or https protocol',
      '(?:www\\.)? : Optional www prefix',
      '[-a-zA-Z0-9...]{1,256} : Domain name',
      '\\.[a-zA-Z0-9()]{1,6} : Valid TLD extension',
    ],
  },
  {
    slug: 'ipv4-address-regex',
    title: 'IPv4 Address Validation Regex',
    category: 'security',
    pattern: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$',
    flags: '',
    description: 'Validates standard dotted decimal IPv4 network address within range 0.0.0.0 to 255.255.255.255.',
    sampleMatch: '192.168.1.1',
    sampleFail: '999.12.34.56',
    explanation: [
      '25[0-5] : Matches numbers 250-255',
      '2[0-4][0-9] : Matches numbers 200-249',
      '[01]?[0-9][0-9]? : Matches numbers 0-199',
      '\\. : Period delimiter repeated 3 times',
    ],
  },
  {
    slug: 'uuid-v4-regex',
    title: 'UUID v4 Identifier Validation Regex',
    category: 'validation',
    pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
    flags: 'i',
    description: 'Validates 36-character canonical random UUID version 4 format.',
    sampleMatch: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    sampleFail: 'invalid-uuid-string',
    explanation: [
      '^[0-9a-f]{8} : 8 hex digits',
      '-[0-9a-f]{4} : 4 hex digits',
      '-4[0-9a-f]{3} : Version 4 prefix with 3 hex digits',
      '-[89ab][0-9a-f]{3} : Variant bits (8, 9, a, or b)',
      '-[0-9a-f]{12}$ : 12 hex digits node identifier',
    ],
  },
  {
    slug: 'hex-color-regex',
    title: 'Hex Color Code Regex (#RGB and #RRGGBB)',
    category: 'web',
    pattern: '^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$',
    flags: 'i',
    description: 'Matches 3-digit or 6-digit CSS hexadecimal color notation.',
    sampleMatch: '#10b981',
    sampleFail: '#12345',
    explanation: [
      '^# : Requires starting hash symbol',
      '[A-Fa-f0-9]{6} : Matches full 6-digit hex format',
      '| : Or',
      '[A-Fa-f0-9]{3} : Matches shorthand 3-digit hex format',
    ],
  },
  {
    slug: 'slug-url-regex',
    title: 'SEO Friendly URL Slug Regex',
    category: 'web',
    pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$',
    flags: '',
    description: 'Enforces lowercase alphanumeric words separated only by single hyphens with no trailing dashes.',
    sampleMatch: 'universal-developer-tools-2026',
    sampleFail: 'Invalid--Slug_Name',
    explanation: [
      '^[a-z0-9]+ : Starts with lowercase letter or digit',
      '(?:-[a-z0-9]+)*$ : Hyphen followed by alphanumeric segment repeated',
    ],
  },
  {
    slug: 'us-phone-number-regex',
    title: 'US Phone Number Format Regex',
    category: 'formatting',
    pattern: '^\\(?([0-9]{3})\\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$',
    flags: '',
    description: 'Validates 10-digit North American telephone numbers in formats like (123) 456-7890 or 123-456-7890.',
    sampleMatch: '(555) 234-5678',
    sampleFail: '12345',
    explanation: [
      '^\\(?([0-9]{3})\\)? : 3-digit area code with optional parentheses',
      '[-. ]? : Optional delimiter (hyphen, period, or space)',
      '([0-9]{3}) : 3-digit exchange code',
      '([0-9]{4})$ : 4-digit subscriber line number',
    ],
  },
  {
    slug: 'date-yyyy-mm-dd-regex',
    title: 'ISO 8601 Date (YYYY-MM-DD) Regex',
    category: 'formatting',
    pattern: '^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$',
    flags: '',
    description: 'Matches standard ISO year-month-day calendar dates.',
    sampleMatch: '2026-09-04',
    sampleFail: '2026-13-45',
    explanation: [
      '^\\d{4} : 4-digit year',
      '-(0[1-9]|1[0-2]) : Month between 01 and 12',
      '-(0[1-9]|[12]\\d|3[01])$ : Day between 01 and 31',
    ],
  },
  {
    slug: 'jwt-token-regex',
    title: 'JSON Web Token (JWT) Format Regex',
    category: 'security',
    pattern: '^[A-Za-z0-9-_=]+\\.[A-Za-z0-9-_=]+\\.?[A-Za-z0-9-_.+/=]*$',
    flags: '',
    description: 'Validates structure of Base64URL-encoded Header.Payload.Signature JWT strings.',
    sampleMatch: 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dozGzN_ce9Trqnh9xsmvrmA6Y8b0VfP_w1sL8sR',
    sampleFail: 'not-a-jwt-token',
    explanation: [
      '^[A-Za-z0-9-_=]+ : Base64URL encoded header',
      '\\. : Period delimiter',
      '[A-Za-z0-9-_=]+ : Base64URL encoded payload',
      '\\.?... : Optional cryptographic signature block',
    ],
  },
  {
    slug: 'semver-version-regex',
    title: 'Semantic Versioning (SemVer) Regex',
    category: 'validation',
    pattern: '^v?(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$',
    flags: '',
    description: 'Validates official Semantic Versioning 2.0.0 strings including pre-release and build metadata.',
    sampleMatch: 'v2.4.1-alpha.3+build.2026',
    sampleFail: '2.4',
    explanation: [
      '^v? : Optional leading v prefix',
      '(0|[1-9]\\d*) : Major version number without leading zeros',
      '\\.(0|[1-9]\\d*) : Minor version number',
      '\\.(0|[1-9]\\d*) : Patch version number',
      '(?:-...) : Optional pre-release identifiers',
    ],
  },
  {
    slug: 'base64-string-regex',
    title: 'Base64 Encoded String Validation Regex',
    category: 'validation',
    pattern: '^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$',
    flags: '',
    description: 'Validates standard RFC 4648 Base64 encoded strings with valid length multiples of 4 and padding.',
    sampleMatch: 'SGVsbG8gV29ybGQh',
    sampleFail: 'Invalid Base64 string==',
    explanation: [
      '(?:[A-Za-z0-9+/]{4})* : Matches multiples of 4 base64 characters',
      '(?:...==|...=)? : Validates 0, 1, or 2 trailing padding equals signs',
    ],
  },
  {
    slug: 'hex-color-code-regex',
    title: 'Hexadecimal Color Code (#HEX) Regex',
    category: 'formatting',
    pattern: '^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$',
    flags: '',
    description: 'Matches 3-digit shorthand, 6-digit RGB, or 8-digit RGBA hex color codes.',
    sampleMatch: '#10b981',
    sampleFail: '#10b981999',
    explanation: [
      '^# : Requires hashtag prefix',
      '[0-9a-fA-F]{3} : 3-digit shorthand (#RGB)',
      '[0-9a-fA-F]{6} : 6-digit standard (#RRGGBB)',
      '[0-9a-fA-F]{8} : 8-digit alpha (#RRGGBBAA)',
    ],
  },
  {
    slug: 'credit-card-number-regex',
    title: 'Credit Card Number (Visa / Master / Amex) Regex',
    category: 'validation',
    pattern: '^(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|6(?:011|5[0-9]{2})[0-9]{12})$',
    flags: '',
    description: 'Validates primary card major industry identifiers for Visa, MasterCard, American Express, and Discover.',
    sampleMatch: '4111111111111111',
    sampleFail: '1234567890123456',
    explanation: [
      '4[0-9]{12}(?:[0-9]{3})? : Visa card format (13 or 16 digits starting with 4)',
      '5[1-5][0-9]{14} : MasterCard format (16 digits starting 51-55)',
      '3[47][0-9]{13} : American Express format (15 digits starting 34 or 37)',
    ],
  },
  {
    slug: 'mac-address-regex',
    title: 'Hardware MAC Address Regex',
    category: 'formatting',
    pattern: '^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$',
    flags: '',
    description: 'Matches standard 48-bit physical MAC addresses formatted with colons or hyphens.',
    sampleMatch: '00:1A:2B:3C:4D:5E',
    sampleFail: '00:1A:2B:3C:4D',
    explanation: [
      '([0-9A-Fa-f]{2}[:-]){5} : First five pairs of hex digits followed by colon or dash',
      '([0-9A-Fa-f]{2}) : Final hex octet pair',
    ],
  },
  {
    slug: 'port-number-regex',
    title: 'TCP / UDP Network Port (1-65535) Regex',
    category: 'validation',
    pattern: '^([1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$',
    flags: '',
    description: 'Validates network port numbers strictly between 1 and 65,535.',
    sampleMatch: '8080',
    sampleFail: '70000',
    explanation: [
      'Matches all valid 16-bit unsigned integer port boundaries up to 65535 without leading zeros.',
    ],
  },
  {
    slug: 'git-commit-hash-regex',
    title: 'Git Commit Hash (SHA-1 / SHA-256) Regex',
    category: 'validation',
    pattern: '^[0-9a-fA-F]{7,40}$',
    flags: '',
    description: 'Matches short (7-char) and full (40-char SHA-1) Git commit hashes.',
    sampleMatch: '7075d8a',
    sampleFail: 'git-commit-xyz',
    explanation: [
      '^[0-9a-fA-F]{7,40}$ : Hexadecimal string between 7 and 40 characters in length.',
    ],
  },
  {
    slug: 'cuid-validation-regex',
    title: 'CUID & CUID2 Collision-Resistant ID Regex',
    category: 'validation',
    pattern: '^[a-z0-9]{24,32}$',
    flags: '',
    description: 'Validates modern secure collision-resistant identifiers (CUID and CUID2) used in high-scale distributed systems.',
    sampleMatch: 'cl01abcde000001l0abcdefgh',
    sampleFail: 'INVALID_CUID_WITH_UPPERCASE!',
    explanation: [
      '^[a-z0-9]{24,32}$ : Matches lowercase alphanumeric string between 24 and 32 characters',
    ],
  },
  {
    slug: 'cron-expression-regex',
    title: '5-Field Unix Cron Expression Regex',
    category: 'validation',
    pattern: '^(@(annually|yearly|monthly|weekly|daily|hourly|reboot))|(@every (\\d+(ns|us|µs|ms|s|m|h))+)|((((\\d+,)+\\d+|(\\d+(\\/|-)\\d+)|\\d+|\\*) ?){5,7})$',
    flags: '',
    description: 'Validates standard 5-to-7 field crontab expressions including wildcard, ranges, steps, and shortcuts.',
    sampleMatch: '*/15 0 1,15 * 1-5',
    sampleFail: 'invalid cron string',
    explanation: [
      'Matches standard 5 to 7 space-separated fields for minute, hour, day of month, month, and day of week.',
    ],
  },
  {
    slug: 'nanoid-validation-regex',
    title: 'NanoID (21-character) URL-Friendly ID Regex',
    category: 'validation',
    pattern: '^[A-Za-z0-9_-]{21}$',
    flags: '',
    description: 'Validates default 21-character URL-friendly, compact NanoID strings.',
    sampleMatch: 'V1StGXR8_Z5jdHi6B-myT',
    sampleFail: 'too_short_id',
    explanation: [
      '^[A-Za-z0-9_-]{21}$ : Matches exactly 21 URL-safe characters from the A-Z, a-z, 0-9, _, - alphabet.',
    ],
  },
  {
    slug: 'youtube-video-id-regex',
    title: 'YouTube Video ID & URL Extractor Regex',
    category: 'web',
    pattern: '^(?:https?:\\/\\/)?(?:www\\.)?(?:youtu\\.be\\/|youtube\\.com\\/(?:embed\\/|v\\/|watch\\?v=|watch\\?.+&v=))([\\w-]{11})(?:\\S+)?$',
    flags: 'i',
    description: 'Matches YouTube video URLs and captures the 11-character unique video identifier.',
    sampleMatch: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    sampleFail: 'https://vimeo.com/123456',
    explanation: [
      'Captures the 11-character alphanumeric YouTube ID from youtu.be, embed, or watch URLs.',
    ],
  },
  {
    slug: 'html-tag-regex',
    title: 'HTML Opening & Closing Tag Stripper Regex',
    category: 'web',
    pattern: '<\\/?[a-zA-Z][^>]*>',
    flags: 'g',
    description: 'Finds and strips opening, closing, and self-closing HTML/XML markup tags from rich text strings.',
    sampleMatch: '<div class="active" data-id="10">',
    sampleFail: 'Plain text with no markup',
    explanation: [
      '< : Opening bracket',
      '\\/? : Optional forward slash for closing tags',
      '[a-zA-Z] : Starts with tag element letter',
      '[^>]*> : Matches all attribute characters until closing bracket',
    ],
  },
  {
    slug: 'markdown-image-link-regex',
    title: 'Markdown Image Syntax Regex',
    category: 'web',
    pattern: '!\\[([^\\]]*)\\]\\(([^\\s)]+)(?:\\s+"([^"]+)")?\\)',
    flags: 'g',
    description: 'Extracts alt text, image URL, and optional title from standard Markdown image tags.',
    sampleMatch: '![Company Logo](https://example.com/logo.png "Brand")',
    sampleFail: '[Normal link](https://example.com)',
    explanation: [
      '! : Image indicator exclamation mark',
      '\\[([^\\]]*)\\] : Captures alt text within brackets',
      '\\(([^\\s)]+) : Captures image URL within parentheses',
      '(?:\\s+"([^"]+)")?\\) : Captures optional title quote before closing parenthesis',
    ],
  },
  {
    slug: 'semantic-version-semver-regex',
    title: 'Semantic Versioning (SemVer 2.0.0) Regex',
    category: 'validation',
    pattern: '^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$',
    flags: '',
    description: 'Official SemVer 2.0.0 regular expression supporting MAJOR.MINOR.PATCH, prerelease identifiers, and build metadata.',
    sampleMatch: '2.1.0-alpha.1+build.847',
    sampleFail: '01.2.3',
    explanation: [
      '^(0|[1-9]\\d*) : Major version with no leading zeros',
      '\\.(0|[1-9]\\d*) : Minor version with no leading zeros',
      '\\.(0|[1-9]\\d*) : Patch version with no leading zeros',
      '(?:-((...)))? : Optional prerelease tag (e.g. -beta.1)',
      '(?:\\+((...)))? : Optional build metadata (e.g. +sha.49a8f2)',
    ],
  },
  {
    slug: 'docker-image-tag-regex',
    title: 'Docker Image Repository & Tag Name Regex',
    category: 'validation',
    pattern: '^(?:(?=[^:\\/]{1,253})(?!-)[a-zA-Z0-9-]{1,63}(?<!-)(?:\\.(?!-)[a-zA-Z0-9-]{1,63}(?<!-))*(?::[0-9]{1,5})?\\/)?(?:[a-z0-9]+(?:[._-][a-z0-9]+)*\\/)*[a-z0-9]+(?:[._-][a-z0-9]+)*(?::[\\w][\\w.-]{0,127})?$',
    flags: '',
    description: 'Validates complete Docker image references including optional registry domain, namespace, image name, and tag.',
    sampleMatch: 'ghcr.io/org/service-app:v1.4.2',
    sampleFail: 'Invalid Image Name : With Spaces',
    explanation: [
      'Matches optional registry host (e.g. registry.hub.docker.com:5000/)',
      'Matches multi-tier organization or username repositories',
      'Matches standard Docker tag with colon separator',
    ],
  },
  {
    slug: 'hex-uuid-clean-regex',
    title: 'Un-hyphenated 32-Char Hexadecimal UUID Regex',
    category: 'formatting',
    pattern: '^[0-9a-fA-F]{32}$',
    flags: '',
    description: 'Validates 32-character compact hexadecimal UUIDs/GUIDs stripped of standard hyphen delimiters.',
    sampleMatch: 'e7236c525b5b444da6428c3ed5a29340',
    sampleFail: 'e7236c52-5b5b-444d-a642-8c3ed5a29340',
    explanation: [
      '^[0-9a-fA-F]{32}$ : Matches exactly thirty-two hexadecimal digits from start to end without hyphens.',
    ],
  },
  {
    slug: 'sql-injection-heuristic-regex',
    title: 'SQL Injection Attack Detection Heuristic Regex',
    category: 'security',
    pattern: '(?i)(?:\\b(select|union|insert|update|delete|drop|alter|create|truncate|exec|execute)\\b|--|/\\*|\\*/|xp_cmdshell|\\bwaitfor\\s+delay\\b)',
    flags: 'i',
    description: 'Detects common SQL injection attack signatures, comments, and dangerous stored procedures in user inputs.',
    sampleMatch: "1' UNION SELECT username, password FROM users --",
    sampleFail: 'john_doe_99',
    explanation: [
      '(?i) : Case insensitive match',
      '\\b(select|union|...) : Matches high-risk SQL keywords as discrete tokens',
      '--|/\\* : Detects inline SQL comment syntax intended to truncate remaining queries',
    ],
  },
];

export function getAllRegexPatterns(): RegexDefinition[] {
  return REGEX_PATTERNS;
}

export function getRegexPattern(slug: string): RegexDefinition | null {
  return REGEX_PATTERNS.find((r) => r.slug === slug) || null;
}
