import { ToolDefinition, ToolCategory, CATEGORIES } from '@/types/tool';

// Text Tools
import { WordCounter } from '@/components/tools/text/WordCounter';
import { CaseConverter } from '@/components/tools/text/CaseConverter';
import { TextDiff } from '@/components/tools/text/TextDiff';
import { LoremIpsumGenerator } from '@/components/tools/text/LoremIpsumGenerator';
import { MarkdownPreviewer } from '@/components/tools/text/MarkdownPreviewer';

// Image Tools
import { ImageCompressor } from '@/components/tools/image/ImageCompressor';
import { ImageConverter } from '@/components/tools/image/ImageConverter';
import { QrCodeGenerator } from '@/components/tools/image/QrCodeGenerator';
import { SvgOptimizer } from '@/components/tools/image/SvgOptimizer';
import { ColorPaletteExtractor } from '@/components/tools/image/ColorPaletteExtractor';

// PDF Tools
import { PdfMerge } from '@/components/tools/pdf/PdfMerge';
import { PdfSplit } from '@/components/tools/pdf/PdfSplit';
import { ImageToPdf } from '@/components/tools/pdf/ImageToPdf';
import { PdfRotate } from '@/components/tools/pdf/PdfRotate';

// Calculator Tools
import { PercentageCalculator } from '@/components/tools/calculator/PercentageCalculator';
import { AspectRatioCalculator } from '@/components/tools/calculator/AspectRatioCalculator';
import { TimezoneConverter } from '@/components/tools/calculator/TimezoneConverter';
import { UnitConverter } from '@/components/tools/calculator/UnitConverter';

// Dev Tools
import { JsonFormatterValidator } from '@/components/tools/dev/JsonFormatterValidator';
import { Base64EncoderDecoder } from '@/components/tools/dev/Base64EncoderDecoder';
import { HashGenerator } from '@/components/tools/dev/HashGenerator';
import { UuidGenerator } from '@/components/tools/dev/UuidGenerator';
import { JwtDecoder } from '@/components/tools/dev/JwtDecoder';
import { CurlConverter } from '@/components/tools/dev/CurlConverter';
import { RegexTester } from '@/components/tools/dev/RegexTester';
import { UnixTimestampConverter } from '@/components/tools/dev/UnixTimestampConverter';
import { UrlEncoderDecoder } from '@/components/tools/dev/UrlEncoderDecoder';
import { GlassmorphismGenerator } from '@/components/tools/dev/GlassmorphismGenerator';
import { BoxShadowGenerator } from '@/components/tools/dev/BoxShadowGenerator';
import { SqlFormatter } from '@/components/tools/dev/SqlFormatter';
import { HtmlMinifier } from '@/components/tools/dev/HtmlMinifier';
import { PasswordGenerator } from '@/components/tools/dev/PasswordGenerator';
import { MarkdownTableGenerator } from '@/components/tools/text/MarkdownTableGenerator';
import { Base64ImageConverter } from '@/components/tools/image/Base64ImageConverter';
import { FlexboxPlayground } from '@/components/tools/dev/FlexboxPlayground';
import { GradientGenerator } from '@/components/tools/dev/GradientGenerator';
import { ClampCalculator } from '@/components/tools/dev/ClampCalculator';
import { HtmlEntityEncoder } from '@/components/tools/dev/HtmlEntityEncoder';
import { SlugGenerator } from '@/components/tools/text/SlugGenerator';
import { TriangleGenerator } from '@/components/tools/dev/TriangleGenerator';
import { ChmodCalculator } from '@/components/tools/dev/ChmodCalculator';
import { MetaTagGenerator } from '@/components/tools/dev/MetaTagGenerator';
import { CsvJsonConverter } from '@/components/tools/dev/CsvJsonConverter';
import { MockDataGenerator } from '@/components/tools/dev/MockDataGenerator';
import { BoxModelVisualizer } from '@/components/tools/dev/BoxModelVisualizer';
import { PlaceholderGenerator } from '@/components/tools/image/PlaceholderGenerator';
import { JsMinifier } from '@/components/tools/dev/JsMinifier';
import { JsonToTsGenerator } from '@/components/tools/dev/JsonToTsGenerator';
import { GridGenerator } from '@/components/tools/dev/GridGenerator';
import { UrlParser } from '@/components/tools/dev/UrlParser';
import { CryptoSuite } from '@/components/tools/dev/CryptoSuite';
import { CubicBezierVisualizer } from '@/components/tools/dev/CubicBezierVisualizer';
import { KeycodeInspector } from '@/components/tools/dev/KeycodeInspector';
import { AspectRatioVisualizer } from '@/components/tools/calculator/AspectRatioVisualizer';
import { BulkUuidGenerator } from '@/components/tools/dev/BulkUuidGenerator';
import { DnsInspector } from '@/components/tools/dev/DnsInspector';
import { JsonPathEvaluator } from '@/components/tools/dev/JsonPathEvaluator';
import { MarkdownHtmlConverter } from '@/components/tools/text/MarkdownHtmlConverter';
import { BcryptSimulator } from '@/components/tools/dev/BcryptSimulator';

export const TOOLS_REGISTRY: ToolDefinition[] = [
  // A. Text & Content
  {
    id: 'word-counter',
    slug: 'word-counter',
    title: 'Word Counter & Text Analyzer',
    shortDesc: 'Calculate words, characters, sentences, paragraphs, reading time, and keyword density.',
    category: 'text',
    keywords: ['word counter', 'character count', 'reading time', 'text analysis', 'keyword density', 'sentences'],
    icon: 'FileText',
    isPopular: true,
    seoDescription: 'Free online word counter and text statistics analyzer. Computes word count, character count without spaces, reading duration, and keyword frequencies in real-time client-side.',
    faqs: [
      {
        question: 'How is reading time calculated?',
        answer: 'Reading time is estimated using the standard average reading speed of 200 words per minute (WPM), while speaking time is based on 130 WPM.',
      },
      {
        question: 'Is my text stored or uploaded to any server?',
        answer: 'No. All calculations occur locally in your browser memory via pure JavaScript.',
      },
    ],
    component: WordCounter,
  },
  {
    id: 'case-converter',
    slug: 'case-converter',
    title: 'Case Converter & Text Formatter',
    shortDesc: 'Convert text to UPPERCASE, lowercase, Title Case, camelCase, snake_case, kebab-case, and PascalCase.',
    category: 'text',
    keywords: ['case converter', 'uppercase', 'lowercase', 'title case', 'camelcase', 'snake_case', 'kebab-case', 'pascalcase'],
    icon: 'Type',
    isPopular: true,
    seoDescription: 'Transform text across multiple letter cases and programming variable naming conventions instantly online.',
    faqs: [
      {
        question: 'What casing styles are supported?',
        answer: 'We support UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE, and extra whitespace cleanup.',
      },
    ],
    component: CaseConverter,
  },
  {
    id: 'text-diff',
    slug: 'text-diff',
    title: 'Text Diff & Comparison Checker',
    shortDesc: 'Compare two text snippets side-by-side with color-coded line and word additions and deletions.',
    category: 'text',
    keywords: ['text diff', 'diff checker', 'compare text', 'text difference', 'code comparison'],
    icon: 'GitCompare',
    seoDescription: 'Compare two text documents or code snippets side-by-side to highlight additions, removals, and changes.',
    component: TextDiff,
  },
  {
    id: 'lorem-ipsum-generator',
    slug: 'lorem-ipsum-generator',
    title: 'Lorem Ipsum Dummy Text Generator',
    shortDesc: 'Generate custom placeholder dummy text by paragraphs, sentences, or word count with HTML tags.',
    category: 'text',
    keywords: ['lorem ipsum', 'dummy text', 'placeholder text', 'filler text', 'generator'],
    icon: 'AlignLeft',
    seoDescription: 'Customizable Lorem Ipsum generator for designers, developers, and copywriters. Output raw paragraphs or HTML markup.',
    component: LoremIpsumGenerator,
  },
  {
    id: 'markdown-previewer',
    slug: 'markdown-previewer',
    title: 'Live Markdown Previewer & HTML Exporter',
    shortDesc: 'Edit Markdown with live split-screen rendered HTML preview, code highlighting, and clean export.',
    category: 'text',
    keywords: ['markdown previewer', 'markdown to html', 'md editor', 'markdown viewer'],
    icon: 'FileCode',
    seoDescription: 'Real-time client-side Markdown editor and HTML previewer. Format headings, tables, blockquotes, and code snippets.',
    component: MarkdownPreviewer,
  },

  // B. Image & Media
  {
    id: 'image-compressor',
    slug: 'image-compressor',
    title: 'Client-Side Image Compressor',
    shortDesc: 'Compress PNG, JPG, and WebP images directly in your browser with target file size and resolution controls.',
    category: 'image',
    keywords: ['image compressor', 'compress image', 'reduce image size', 'compress png', 'compress jpg', 'webp compressor'],
    icon: 'Minimize2',
    isPopular: true,
    seoDescription: 'High-quality lossy and lossless image compression running 100% locally in your browser via WebAssembly and Canvas. Zero server uploads.',
    faqs: [
      {
        question: 'How much can I reduce image size?',
        answer: 'You can typically achieve 60% to 90% file size reduction with minimal visual quality loss by adjusting target MB and max dimension sliders.',
      },
    ],
    component: ImageCompressor,
  },
  {
    id: 'image-converter',
    slug: 'image-converter',
    title: 'Image Format Converter (WebP, PNG, JPG)',
    shortDesc: 'Convert images to WebP, PNG, or JPEG with adjustable quality settings using browser Canvas.',
    category: 'image',
    keywords: ['image converter', 'png to webp', 'jpg to png', 'convert image format', 'webp converter'],
    icon: 'Image',
    isPopular: true,
    seoDescription: 'Convert any image format to WebP, PNG, or JPEG in seconds without uploading files to remote servers.',
    component: ImageConverter,
  },
  {
    id: 'qr-code-generator',
    slug: 'qr-code-generator',
    title: 'Custom QR Code Generator',
    shortDesc: 'Create high-resolution QR codes with custom colors, URLs, Wi-Fi networks, emails, and download as PNG/SVG.',
    category: 'image',
    keywords: ['qr code generator', 'create qr code', 'custom qr', 'wifi qr code', 'svg qr code'],
    icon: 'QrCode',
    isPopular: true,
    seoDescription: 'Generate custom QR codes online for URLs, Wi-Fi passwords, contact cards, and plain text. Download high-res PNG and vector SVG.',
    component: QrCodeGenerator,
  },
  {
    id: 'svg-optimizer',
    slug: 'svg-optimizer',
    title: 'SVG Optimizer & Minifier',
    shortDesc: 'Clean SVG files, strip metadata, comments, and unused attributes for maximum web performance.',
    category: 'image',
    keywords: ['svg optimizer', 'minify svg', 'clean svg', 'svg compressor', 'svg minifier'],
    icon: 'Sparkles',
    seoDescription: 'Optimize SVG markup, remove bloated editor metadata, and reduce vector file sizes with real-time visual preview.',
    component: SvgOptimizer,
  },
  {
    id: 'color-palette-extractor',
    slug: 'color-palette-extractor',
    title: 'Image Color Palette Extractor',
    shortDesc: 'Extract dominant color palettes and Hex/RGB swatches from uploaded images using Canvas pixel sampling.',
    category: 'image',
    keywords: ['color palette extractor', 'extract colors from image', 'image color picker', 'dominant colors'],
    icon: 'Palette',
    seoDescription: 'Upload any image to generate harmonious dominant color swatches with one-click HEX and RGB copying.',
    component: ColorPaletteExtractor,
  },

  // C. PDF & Documents
  {
    id: 'pdf-merge',
    slug: 'pdf-merge',
    title: 'PDF Merger & Combiner',
    shortDesc: 'Merge multiple PDF documents into a single organized file with drag-and-drop page ordering.',
    category: 'pdf',
    keywords: ['pdf merge', 'combine pdf', 'join pdf', 'merge pdf files', 'pdf combiner online'],
    icon: 'Layers',
    isPopular: true,
    seoDescription: 'Merge PDF files online privately. 100% client-side manipulation using pdf-lib with zero server uploads.',
    faqs: [
      {
        question: 'Are my confidential documents secure?',
        answer: 'Yes! PDF merging executes 100% locally inside your browser via WebAssembly and pdf-lib. Zero bytes leave your device.',
      },
    ],
    component: PdfMerge,
  },
  {
    id: 'pdf-split',
    slug: 'pdf-split',
    title: 'PDF Splitter & Page Extractor',
    shortDesc: 'Extract specific pages or custom page ranges (e.g. 1-3, 5, 8) from any PDF document.',
    category: 'pdf',
    keywords: ['pdf split', 'extract pdf pages', 'split pdf online', 'separate pdf pages'],
    icon: 'Scissors',
    isPopular: true,
    seoDescription: 'Split large PDF files into smaller documents or extract custom page intervals privately on your device.',
    component: PdfSplit,
  },
  {
    id: 'image-to-pdf',
    slug: 'image-to-pdf',
    title: 'Image to PDF Converter',
    shortDesc: 'Convert multiple PNG and JPG images into printable multi-page A4 PDF documents.',
    category: 'pdf',
    keywords: ['image to pdf', 'jpg to pdf', 'png to pdf', 'convert photos to pdf'],
    icon: 'FileUp',
    seoDescription: 'Turn photos and images into structured A4 PDF pages online in seconds with zero data transmission.',
    component: ImageToPdf,
  },
  {
    id: 'pdf-rotate',
    slug: 'pdf-rotate',
    title: 'PDF Page Rotator',
    shortDesc: 'Rotate PDF pages permanently by 90, 180, or 270 degrees clockwise or counter-clockwise.',
    category: 'pdf',
    keywords: ['pdf rotate', 'rotate pdf pages', 'rotate pdf permanently', 'turn pdf'],
    icon: 'RotateCw',
    seoDescription: 'Permanently rotate upside-down or sideways PDF pages by 90°, 180°, or 270° directly in your browser.',
    component: PdfRotate,
  },

  // D. Daily Calculators
  {
    id: 'percentage-calculator',
    slug: 'percentage-calculator',
    title: 'Percentage & Discount Calculator',
    shortDesc: 'Calculate percentage of a number, percentage changes (increase/decrease), and final sale discounts.',
    category: 'calculator',
    keywords: ['percentage calculator', 'percent change', 'discount calculator', 'percent increase', 'math tools'],
    icon: 'Percent',
    isPopular: true,
    seoDescription: 'Fast multi-mode percentage calculator. Compute what is X% of Y, percentage increase or decrease, and sale discounts.',
    component: PercentageCalculator,
  },
  {
    id: 'aspect-ratio-calculator',
    slug: 'aspect-ratio-calculator',
    title: 'Aspect Ratio & Dimension Calculator',
    shortDesc: 'Calculate 16:9, 4:3, 1:1, 21:9 responsive dimensions and scale resolutions with live preview.',
    category: 'calculator',
    keywords: ['aspect ratio calculator', '16:9 calculator', 'image dimensions', 'screen ratio', 'resolution scaler'],
    icon: 'Maximize2',
    seoDescription: 'Calculate aspect ratios and proportional dimensions for video editing, web design, photography, and UI layouts.',
    component: AspectRatioCalculator,
  },
  {
    id: 'timezone-converter',
    slug: 'timezone-converter',
    title: 'Timezone Converter & World Clock',
    shortDesc: 'Compare global times and schedule meetings across major world cities with an interactive hour slider.',
    category: 'calculator',
    keywords: ['timezone converter', 'world clock', 'time difference', 'utc converter', 'gmt offset'],
    icon: 'Clock',
    seoDescription: 'Interactive timezone converter comparing live time in New York, London, Tokyo, Istanbul, and Sydney.',
    component: TimezoneConverter,
  },
  {
    id: 'unit-converter',
    slug: 'unit-converter',
    title: 'Universal Unit Converter',
    shortDesc: 'Convert units across Length, Weight, Temperature, Data Storage, Speed, and Area.',
    category: 'calculator',
    keywords: ['unit converter', 'metric converter', 'celsius to fahrenheit', 'bytes to mb', 'km to miles'],
    icon: 'ArrowRightLeft',
    seoDescription: 'Comprehensive unit conversion tool for metric and imperial standards across length, mass, temperature, and digital storage.',
    component: UnitConverter,
  },

  // E. Developer & Data
  {
    id: 'json-formatter-validator',
    slug: 'json-formatter-validator',
    title: 'JSON Formatter, Beautifier & Validator',
    shortDesc: 'Format, beautify, validate, and minify JSON payloads with syntax error diagnostic markers.',
    category: 'dev',
    keywords: ['json formatter', 'json beautifier', 'json validator', 'minify json', 'json lint'],
    icon: 'Braces',
    isPopular: true,
    seoDescription: 'Online JSON formatter and linter powered by CodeMirror 6 and Prettier. Highlights exact error lines and minifies payloads.',
    component: JsonFormatterValidator,
  },
  {
    id: 'base64-encoder-decoder',
    slug: 'base64-encoder-decoder',
    title: 'Base64 Encoder & Decoder',
    shortDesc: 'Encode and decode plain text and data to Base64 with URL-safe RFC 4648 formatting.',
    category: 'dev',
    keywords: ['base64 encoder', 'base64 decoder', 'btoa', 'atob', 'url safe base64'],
    icon: 'Binary',
    isPopular: true,
    seoDescription: 'Convert plain text and binary strings to Base64 and decode Base64 back to text with URL-safe option.',
    component: Base64EncoderDecoder,
  },
  {
    id: 'hash-generator',
    slug: 'hash-generator',
    title: 'Hash Generator (SHA-256, SHA-512, SHA-1)',
    shortDesc: 'Generate cryptographic hashes from input strings using the hardware-accelerated Web Crypto API.',
    category: 'dev',
    keywords: ['hash generator', 'sha256', 'sha512', 'sha1', 'md5', 'cryptography', 'checksum'],
    icon: 'Hash',
    seoDescription: 'Generate instant SHA-256, SHA-512, SHA-384, and SHA-1 cryptographic hashes via Web Crypto API in your browser.',
    component: HashGenerator,
  },
  {
    id: 'uuid-generator',
    slug: 'uuid-generator',
    title: 'Bulk UUID v4 Generator',
    shortDesc: 'Generate cryptographically random UUID v4 identifiers in bulk with uppercase, hyphen, and brace toggles.',
    category: 'dev',
    keywords: ['uuid generator', 'guid generator', 'random uuid', 'bulk uuid', 'uuid v4'],
    icon: 'Fingerprint',
    seoDescription: 'Generate thousands of random UUID v4 identifiers instantly. Export as plain text with customizable hyphenation.',
    component: UuidGenerator,
  },
  {
    id: 'jwt-decoder',
    slug: 'jwt-decoder',
    title: 'JWT Token Decoder & Expiration Inspector',
    shortDesc: 'Decode JSON Web Token headers, payload claims, timestamps, and verify expiration dates privately.',
    category: 'dev',
    keywords: ['jwt decoder', 'decode jwt', 'jwt inspector', 'bearer token', 'json web token'],
    icon: 'Key',
    isPopular: true,
    seoDescription: 'Inspect and debug JWT tokens without sending sensitive authorization credentials or secrets over the wire.',
    component: JwtDecoder,
  },
  {
    id: 'curl-to-code',
    slug: 'curl-to-code',
    title: 'cURL to Code Converter (Fetch, Axios, Python, Go, Rust)',
    shortDesc: 'Convert cURL command syntax into native JavaScript fetch, Axios, Python requests, Go http, and Rust reqwest.',
    category: 'dev',
    keywords: ['curl to fetch', 'curl to python', 'curl to code', 'curl to axios', 'curl to go', 'curl converter'],
    icon: 'Terminal',
    isPopular: true,
    isNew: true,
    seoDescription: 'Instantly convert cURL API requests into clean, idiomatic JavaScript Fetch, Axios, Python Requests, Go net/http, and Rust reqwest code in your browser.',
    component: CurlConverter,
  },
  {
    id: 'regex-tester',
    slug: 'regex-tester',
    title: 'Regex Tester & Match Visualizer',
    shortDesc: 'Test regular expressions in real-time with capture group extraction, flags support, and error diagnostics.',
    category: 'dev',
    keywords: ['regex tester', 'regular expression', 'regex matcher', 'regex debugger', 'regex online'],
    icon: 'Terminal',
    isPopular: true,
    isNew: true,
    seoDescription: 'Test and debug JavaScript regular expressions in real-time with capture groups and flags.',
    component: RegexTester,
  },
  {
    id: 'unix-timestamp',
    slug: 'unix-timestamp',
    title: 'Unix Timestamp & Epoch Converter',
    shortDesc: 'Convert epoch seconds and milliseconds to human-readable dates (UTC, Local, ISO-8601) and vice-versa.',
    category: 'dev',
    keywords: ['unix timestamp', 'epoch converter', 'epoch to date', 'timestamp to date', 'current epoch'],
    icon: 'Clock',
    isPopular: true,
    isNew: true,
    seoDescription: 'Live Unix epoch clock and bidirectional date-to-timestamp converter.',
    component: UnixTimestampConverter,
  },
  {
    id: 'url-encoder-decoder',
    slug: 'url-encoder-decoder',
    title: 'URL & URI Component Encoder / Decoder',
    shortDesc: 'Encode and decode URI strings, escape query parameters, and parse URL search query parameters.',
    category: 'dev',
    keywords: ['url encoder', 'url decoder', 'encode uri', 'decode uri', 'query string parser'],
    icon: 'Binary',
    isPopular: true,
    isNew: true,
    seoDescription: 'Encode, decode, and parse URL query parameters instantly in your browser.',
    component: UrlEncoderDecoder,
  },
  {
    id: 'css-glassmorphism',
    slug: 'css-glassmorphism',
    title: 'CSS Glassmorphism & Frosted Glass Generator',
    shortDesc: 'Create modern frosted glass UI with backdrop-blur, specular transparency, and Tailwind CSS code.',
    category: 'dev',
    keywords: ['glassmorphism generator', 'css glassmorphism', 'backdrop filter blur', 'frosted glass css', 'tailwind glassmorphism'],
    icon: 'Sparkles',
    isPopular: true,
    isNew: true,
    seoDescription: 'Interactive Glassmorphism generator with real-time backdrop blur and Tailwind CSS class exports.',
    component: GlassmorphismGenerator,
  },
  {
    id: 'css-box-shadow',
    slug: 'css-box-shadow',
    title: 'CSS Box Shadow & Glow Generator',
    shortDesc: 'Design layered drop shadows, neon glows, and inset shadows with visual live interactive canvas.',
    category: 'dev',
    keywords: ['box shadow generator', 'css box shadow', 'drop shadow generator', 'neon glow css', 'shadow generator'],
    icon: 'Layers',
    isPopular: true,
    isNew: true,
    seoDescription: 'Design smooth multi-layered CSS box shadows, 3D elevations, and neon glows with one-click copy.',
    component: BoxShadowGenerator,
  },
  {
    id: 'sql-formatter',
    slug: 'sql-formatter',
    title: 'SQL Query Formatter & Beautifier',
    shortDesc: 'Format, prettify, and indent SQL queries with uppercase keyword highlighting and custom spacing.',
    category: 'dev',
    keywords: ['sql formatter', 'format sql', 'sql beautifier', 'sql prettifier', 'sql indent'],
    icon: 'Database',
    isPopular: true,
    isNew: true,
    seoDescription: 'Format and beautify complex SQL queries directly in your browser with uppercase keywords.',
    component: SqlFormatter,
  },
  {
    id: 'html-minifier',
    slug: 'html-minifier',
    title: 'HTML & XML Code Minifier / Compressor',
    shortDesc: 'Minify and compress HTML markup, strip comments, collapse whitespace, and reduce payload size.',
    category: 'dev',
    keywords: ['html minifier', 'minify html', 'compress html', 'html compressor', 'strip html comments'],
    icon: 'Code2',
    isPopular: true,
    isNew: true,
    seoDescription: 'Minify and compress HTML code in real-time to boost webpage load performance.',
    component: HtmlMinifier,
  },
  {
    id: 'password-generator',
    slug: 'password-generator',
    title: 'Strong Password & Passphrase Generator',
    shortDesc: 'Generate cryptographically secure random passwords with customizable length and entropy scoring.',
    category: 'dev',
    keywords: ['password generator', 'strong password', 'random password', 'secure password', 'generate password'],
    icon: 'Lock',
    isPopular: true,
    isNew: true,
    seoDescription: 'Generate quantum-safe cryptographic passwords with customizable character sets and entropy scoring.',
    component: PasswordGenerator,
  },
  {
    id: 'markdown-table-generator',
    slug: 'markdown-table-generator',
    title: 'Markdown Table Generator & Spreadsheet Grid',
    shortDesc: 'Design Markdown tables with interactive grid editing, column alignments, and instant markdown output.',
    category: 'text',
    keywords: ['markdown table generator', 'markdown table', 'table generator', 'md table', 'table builder'],
    icon: 'Table',
    isPopular: true,
    isNew: true,
    seoDescription: 'Interactive visual Markdown table generator with custom alignments and real-time preview.',
    component: MarkdownTableGenerator,
  },
  {
    id: 'image-to-base64',
    slug: 'image-to-base64',
    title: 'Image to Base64 & Base64 to Image Decoder',
    shortDesc: 'Convert PNG, JPG, SVG to Base64 data URIs, HTML img tags, and decode Base64 back to image files.',
    category: 'image',
    keywords: ['image to base64', 'base64 to image', 'base64 image decoder', 'data uri generator', 'base64 png'],
    icon: 'FileImage',
    isPopular: true,
    isNew: true,
    seoDescription: 'Convert images to Base64 strings and decode Base64 to PNG/JPG downloads with HTML and CSS snippets.',
    component: Base64ImageConverter,
  },
  {
    id: 'css-flexbox-playground',
    slug: 'css-flexbox-playground',
    title: 'CSS Flexbox Visualizer & Interactive Playground',
    shortDesc: 'Interactive CSS Flexbox sandbox with direction, alignment, justify, wrap, and Tailwind code generator.',
    category: 'dev',
    keywords: ['flexbox playground', 'css flexbox', 'flexbox generator', 'flexbox visualizer', 'tailwind flexbox'],
    icon: 'Layout',
    isPopular: true,
    isNew: true,
    seoDescription: 'Visual CSS Flexbox builder with interactive items, alignment toggles, and live CSS export.',
    component: FlexboxPlayground,
  },
  {
    id: 'css-gradient-generator',
    slug: 'css-gradient-generator',
    title: 'CSS Gradient Generator (Linear & Radial)',
    shortDesc: 'Create smooth multi-color linear and radial CSS gradients with live angle controls and color presets.',
    category: 'dev',
    keywords: ['gradient generator', 'css gradient', 'linear gradient', 'radial gradient', 'color gradient'],
    icon: 'Palette',
    isPopular: true,
    isNew: true,
    seoDescription: 'Interactive CSS Gradient Generator with real-time live canvas and one-click CSS exports.',
    component: GradientGenerator,
  },
  {
    id: 'css-clamp-calculator',
    slug: 'css-clamp-calculator',
    title: 'CSS Clamp & Fluid Typography Calculator',
    shortDesc: 'Calculate responsive fluid font sizes using CSS clamp(min, preferred, max) with real-time viewport scaling.',
    category: 'dev',
    keywords: ['clamp calculator', 'css clamp', 'fluid typography', 'responsive font size', 'clamp font size'],
    icon: 'Type',
    isPopular: true,
    isNew: true,
    seoDescription: 'Generate fluid responsive CSS typography using modern clamp() functions.',
    component: ClampCalculator,
  },
  {
    id: 'html-entity-encoder',
    slug: 'html-entity-encoder',
    title: 'HTML Entity Encoder & Decoder',
    shortDesc: 'Encode special characters into HTML entities (&amp;, &lt;, &gt;, &quot;) and decode entities back to text.',
    category: 'dev',
    keywords: ['html entity encoder', 'html decode', 'encode html entities', 'escape html', 'html special chars'],
    icon: 'Code',
    isPopular: true,
    isNew: true,
    seoDescription: 'Encode and decode HTML special entities with named and numeric representation modes.',
    component: HtmlEntityEncoder,
  },
  {
    id: 'url-slug-generator',
    slug: 'url-slug-generator',
    title: 'SEO Friendly URL Slugify & Permalink Generator',
    shortDesc: 'Convert blog post titles, Turkish & international characters into clean SEO URL slugs.',
    category: 'text',
    keywords: ['slug generator', 'slugify', 'url slug', 'permalink generator', 'turkish char to slug'],
    icon: 'Link2',
    isPopular: true,
    isNew: true,
    seoDescription: 'Generate clean, search-engine-friendly URL slugs with international character transliteration.',
    component: SlugGenerator,
  },
  {
    id: 'css-triangle-generator',
    slug: 'css-triangle-generator',
    title: 'Pure CSS Triangle & Arrow Generator',
    shortDesc: 'Generate pure CSS border triangles for tooltips, modals, and speech bubbles with 8 direction modes.',
    category: 'dev',
    keywords: ['css triangle', 'triangle generator', 'css arrow', 'tooltip arrow css', 'css shape generator'],
    icon: 'Play',
    isPopular: true,
    isNew: true,
    seoDescription: 'Create pure CSS border triangles with custom direction, width, height, and color.',
    component: TriangleGenerator,
  },
  {
    id: 'chmod-calculator',
    slug: 'chmod-calculator',
    title: 'Linux Chmod Permissions Calculator',
    shortDesc: 'Calculate Linux / Unix file permissions in octal (755, 644) and symbolic notation (rwxr-xr-x).',
    category: 'dev',
    keywords: ['chmod calculator', 'chmod 777', 'chmod 755', 'chmod 644', 'linux permissions calculator'],
    icon: 'Terminal',
    isPopular: true,
    isNew: true,
    seoDescription: 'Calculate and convert Linux file permissions into octal chmod commands and symbolic format.',
    component: ChmodCalculator,
  },
  {
    id: 'meta-tag-generator',
    slug: 'meta-tag-generator',
    title: 'SEO Meta Tag & Social Card Previewer',
    shortDesc: 'Generate OpenGraph, Twitter card, and Google search snippet meta tags with live interactive cards.',
    category: 'dev',
    keywords: ['meta tag generator', 'opengraph generator', 'twitter card generator', 'social preview', 'seo meta'],
    icon: 'Globe',
    isPopular: true,
    isNew: true,
    seoDescription: 'Generate complete HTML OpenGraph, Twitter, and search engine meta tags with live social previews.',
    component: MetaTagGenerator,
  },
  {
    id: 'csv-to-json-converter',
    slug: 'csv-to-json-converter',
    title: 'CSV to JSON & JSON to CSV Table Converter',
    shortDesc: 'Bidirectional CSV and JSON tabular data converter with delimiter options and file downloads.',
    category: 'dev',
    keywords: ['csv to json', 'json to csv', 'csv converter', 'json table converter', 'csv parser'],
    icon: 'FileSpreadsheet',
    isPopular: true,
    isNew: true,
    seoDescription: 'Convert CSV spreadsheets to JSON arrays and JSON to CSV files directly in your browser.',
    component: CsvJsonConverter,
  },
  {
    id: 'mock-data-generator',
    slug: 'mock-data-generator',
    title: 'Fake Data & Mock JSON/CSV/SQL Generator',
    shortDesc: 'Generate realistic mock user data, emails, roles, companies in JSON, CSV, and SQL INSERT formats.',
    category: 'dev',
    keywords: ['mock data generator', 'fake json generator', 'mock user data', 'test data generator', 'sql insert generator'],
    icon: 'Database',
    isPopular: true,
    isNew: true,
    seoDescription: 'Generate custom mock JSON records, CSV spreadsheets, and SQL statements for development and testing.',
    component: MockDataGenerator,
  },
  {
    id: 'css-box-model-visualizer',
    slug: 'css-box-model-visualizer',
    title: 'CSS Box Model & Padding/Margin Visualizer',
    shortDesc: 'Interactive nested visualizer for Margin, Border, Padding, Content with border-box / content-box modes.',
    category: 'dev',
    keywords: ['css box model', 'box model visualizer', 'padding margin visualizer', 'box-sizing calculator'],
    icon: 'Box',
    isPopular: true,
    isNew: true,
    seoDescription: 'Visualize and calculate rendered element dimensions with CSS box model and box-sizing properties.',
    component: BoxModelVisualizer,
  },
  {
    id: 'placeholder-image-generator',
    slug: 'placeholder-image-generator',
    title: 'SVG Placeholder & Dummy Image Generator',
    shortDesc: 'Create customized SVG and WebP placeholder images with custom dimensions, colors, and Data URIs.',
    category: 'image',
    keywords: ['placeholder image generator', 'svg placeholder', 'dummy image', 'data uri image generator'],
    icon: 'Image',
    isPopular: true,
    isNew: true,
    seoDescription: 'Generate lightweight SVG placeholder images and Data URIs with custom dimensions and colors.',
    component: PlaceholderGenerator,
  },
  {
    id: 'js-minifier',
    slug: 'js-minifier',
    title: 'JavaScript & TypeScript Code Minifier',
    shortDesc: 'Compress and minify JavaScript/TypeScript code by stripping comments and compacting whitespace.',
    category: 'dev',
    keywords: ['js minifier', 'javascript compressor', 'minify js', 'compress typescript', 'clean js code'],
    icon: 'FileCode',
    isPopular: true,
    isNew: true,
    seoDescription: 'Minify JavaScript and TypeScript code online with instant file size reduction and download.',
    component: JsMinifier,
  },
  {
    id: 'json-to-typescript',
    slug: 'json-to-typescript',
    title: 'JSON to TypeScript Interfaces & Types Converter',
    shortDesc: 'Convert JSON payloads into clean, strongly typed TypeScript interfaces with nested type inference.',
    category: 'dev',
    keywords: ['json to typescript', 'json to ts', 'json to interface', 'generate ts types', 'typescript generator'],
    icon: 'Code2',
    isPopular: true,
    isNew: true,
    seoDescription: 'Generate strongly typed TypeScript interfaces and type definitions from JSON data structures.',
    component: JsonToTsGenerator,
  },
  {
    id: 'css-grid-generator',
    slug: 'css-grid-generator',
    title: 'CSS Grid Interactive Matrix & Layout Generator',
    shortDesc: 'Visual CSS Grid playground with customizable rows, columns, gaps, and instant Tailwind classes.',
    category: 'dev',
    keywords: ['css grid generator', 'grid layout visualizer', 'css grid playground', 'tailwind grid generator'],
    icon: 'LayoutGrid',
    isPopular: true,
    isNew: true,
    seoDescription: 'Interactive visual CSS Grid generator for responsive web layouts and Tailwind CSS utilities.',
    component: GridGenerator,
  },
  {
    id: 'url-parser',
    slug: 'url-parser',
    title: 'URL Parser & Query String Parameter Inspector',
    shortDesc: 'Deconstruct URLs into protocol, hostname, path, hash, and interactive query parameters table.',
    category: 'dev',
    keywords: ['url parser', 'query string builder', 'url inspector', 'parse url params', 'query parameters'],
    icon: 'Link2',
    isPopular: true,
    isNew: true,
    seoDescription: 'Parse and inspect URL components, query parameters, protocol, hostname, and path elements.',
    component: UrlParser,
  },
  {
    id: 'crypto-hash-suite',
    slug: 'crypto-hash-suite',
    title: 'Multi-Algorithm Cryptographic Hash Suite',
    shortDesc: 'Generate SHA-256, SHA-512, SHA-384, and SHA-1 cryptographic digests with client-side Web Crypto.',
    category: 'dev',
    keywords: ['sha512 generator', 'sha256 generator', 'crypto hash suite', 'sha384 hash', 'sha1 generator'],
    icon: 'Lock',
    isPopular: true,
    isNew: true,
    seoDescription: 'Compute high-security cryptographic hashes (SHA-256, SHA-512, SHA-384, SHA-1) entirely client-side.',
    component: CryptoSuite,
  },
  {
    id: 'cubic-bezier-generator',
    slug: 'cubic-bezier-generator',
    title: 'CSS Cubic Bezier & Animation Timing Generator',
    shortDesc: 'Interactive cubic bezier curve visualizer with animation playground and standard CSS export.',
    category: 'dev',
    keywords: ['cubic bezier generator', 'css timing function', 'cubic bezier curve', 'css transition generator'],
    icon: 'Play',
    isPopular: true,
    isNew: true,
    seoDescription: 'Design and preview custom CSS cubic-bezier transition curves with a real-time animation comparison.',
    component: CubicBezierVisualizer,
  },
  {
    id: 'javascript-keycode-inspector',
    slug: 'javascript-keycode-inspector',
    title: 'JavaScript KeyCode & KeyboardEvent Live Inspector',
    shortDesc: 'Inspect JavaScript event.key, event.code, keyCode, which, and modifier keys on any keypress.',
    category: 'dev',
    keywords: ['keycode', 'javascript keycode', 'keyboard event inspector', 'event which', 'key code finder'],
    icon: 'Keyboard',
    isPopular: true,
    isNew: true,
    seoDescription: 'Real-time JavaScript KeyboardEvent inspector showing key, code, keyCode, location, and modifiers.',
    component: KeycodeInspector,
  },
  {
    id: 'aspect-ratio-calculator',
    slug: 'aspect-ratio-calculator',
    title: 'Responsive Aspect Ratio & Resolution Calculator',
    shortDesc: 'Calculate proportional dimensions for 16:9, 4:3, 1:1, 9:16 (TikTok) with instant CSS snippets.',
    category: 'calculator',
    keywords: ['aspect ratio calculator', '16 9 calculator', 'image ratio calculator', 'screen resolution ratio'],
    icon: 'Ratio',
    isPopular: true,
    isNew: true,
    seoDescription: 'Calculate responsive aspect ratios, image pixel dimensions, and CSS aspect-ratio properties.',
    component: AspectRatioVisualizer,
  },
  {
    id: 'bulk-uuid-generator',
    slug: 'bulk-uuid-generator',
    title: 'Bulk UUID & GUID v4 Generator',
    shortDesc: 'Generate up to 500 random UUID v4s at once with uppercase/lowercase and JSON array formatting.',
    category: 'dev',
    keywords: ['bulk uuid generator', 'guid generator', 'random uuid', 'bulk guid', 'generate 100 uuids'],
    icon: 'Fingerprint',
    isPopular: true,
    isNew: true,
    seoDescription: 'Generate batches of random cryptographic UUID / GUID v4 identifiers with custom formatting options.',
    component: BulkUuidGenerator,
  },
  {
    id: 'dns-lookup-inspector',
    slug: 'dns-lookup-inspector',
    title: 'Live DNS over HTTPS (DoH) Record Inspector',
    shortDesc: 'Lookup A, AAAA, MX, TXT, CNAME, NS, SOA records with real-time TTL and Cloudflare 1.1.1.1 resolver.',
    category: 'dev',
    keywords: ['dns lookup', 'dns checker', 'mx lookup', 'txt record lookup', 'dns inspector'],
    icon: 'Globe',
    isPopular: true,
    isNew: true,
    seoDescription: 'Perform live DNS over HTTPS queries for A, AAAA, MX, TXT, and CNAME domain records.',
    component: DnsInspector,
  },
  {
    id: 'jsonpath-evaluator',
    slug: 'jsonpath-evaluator',
    title: 'JSONPath & JSON Query Expression Evaluator',
    shortDesc: 'Extract and query nested JSON properties using JSONPath expressions with live result formatting.',
    category: 'dev',
    keywords: ['jsonpath evaluator', 'json query', 'jsonpath online', 'parse json path', 'json filter'],
    icon: 'Search',
    isPopular: true,
    isNew: true,
    seoDescription: 'Evaluate JSONPath queries against JSON documents with instant sub-tree results and match counts.',
    component: JsonPathEvaluator,
  },
  {
    id: 'markdown-to-html-converter',
    slug: 'markdown-to-html-converter',
    title: 'Markdown to HTML & HTML to Markdown Converter',
    shortDesc: 'Bidirectional converter for Markdown text and HTML tags with live preview and code export.',
    category: 'text',
    keywords: ['markdown to html', 'html to markdown', 'md to html', 'markdown converter', 'html to md'],
    icon: 'FileText',
    isPopular: true,
    isNew: true,
    seoDescription: 'Convert Markdown to clean HTML code and HTML back to Markdown syntax with live preview.',
    component: MarkdownHtmlConverter,
  },
  {
    id: 'bcrypt-generator-verifier',
    slug: 'bcrypt-generator-verifier',
    title: 'Bcrypt Hash Generator & Password Verifier',
    shortDesc: 'Simulate bcrypt salted password hashing with customizable cost rounds (4-14) and match verification.',
    category: 'dev',
    keywords: ['bcrypt generator', 'bcrypt hash', 'bcrypt password checker', 'salt rounds bcrypt', 'bcrypt simulator'],
    icon: 'Lock',
    isPopular: true,
    isNew: true,
    seoDescription: 'Generate salted bcrypt password hashes and verify plaintext strings against hash signatures.',
    component: BcryptSimulator,
  },
];

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOLS_REGISTRY.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): ToolDefinition[] {
  return TOOLS_REGISTRY.filter((t) => t.category === category);
}

export function getPopularTools(): ToolDefinition[] {
  return TOOLS_REGISTRY.filter((t) => t.isPopular);
}
