export type ToolCategoryKey =
  | 'all'
  | 'pdf'
  | 'image'
  | 'text'
  | 'dev'
  | 'converters'
  | 'calculators';

export interface CategoryFilterItem {
  key: ToolCategoryKey;
  label: string;
  iconName: string;
}

export interface DeveloperToolItem {
  id: string;
  slug: string;
  title: string;
  description: string;
  category: ToolCategoryKey;
  categoryLabel: string;
  icon: string;
  tags: string[];
  isPopular?: boolean;
  isNew?: boolean;
  path: string;
}

export const CATEGORY_FILTERS: CategoryFilterItem[] = [
  { key: 'all', label: 'Tüm Araçlar / All Tools', iconName: 'Sparkles' },
  { key: 'pdf', label: '📄 PDF & Belgeler', iconName: 'FileSpreadsheet' },
  { key: 'image', label: '🖼️ Görsel & Fotoğraf', iconName: 'Image' },
  { key: 'text', label: '✍️ Metin & Yazı', iconName: 'FileText' },
  { key: 'dev', label: '💻 Geliştirici & API', iconName: 'Terminal' },
  { key: 'converters', label: '🔄 Kod Dönüştürücüler', iconName: 'ArrowRightLeft' },
  { key: 'calculators', label: '🧮 Hesaplayıcılar', iconName: 'Calculator' },
];

export const DEVELOPER_TOOLS: DeveloperToolItem[] = [
  // 1. PDF & Belgeler (Öncelikli Günlük Araçlar)
  {
    id: 'pdf-merge',
    slug: 'pdf-merge',
    title: 'PDF Birleştirici (PDF Merge)',
    description: 'Birden fazla PDF belgesini tek bir dosyada güvenle birleştirin. Dosyalarınız asla sunucuya yüklenmez, %100 tarayıcıda işlenir.',
    category: 'pdf',
    categoryLabel: 'PDF & Belgeler',
    icon: 'FileSpreadsheet',
    tags: ['#pdf', '#merge', '#birleştir', '#wasm'],
    isPopular: true,
    path: '/tools/pdf-merge/',
  },
  {
    id: 'pdf-split',
    slug: 'pdf-split',
    title: 'PDF Sayfa Bölücü (PDF Split)',
    description: 'PDF belgelerinizdeki belirli sayfaları ayırın veya ayrı ayrı PDF dosyalarına bölün.',
    category: 'pdf',
    categoryLabel: 'PDF & Belgeler',
    icon: 'FileText',
    tags: ['#pdf', '#split', '#böl', '#sayfa'],
    isPopular: true,
    path: '/tools/pdf-split/',
  },
  {
    id: 'image-to-pdf',
    slug: 'image-to-pdf',
    title: 'Görselden PDF Oluşturucu (Image to PDF)',
    description: 'JPG, PNG ve WebP formatındaki fotoğraflarınızı tek tıkla yüksek kaliteli PDF belgesine dönüştürün.',
    category: 'pdf',
    categoryLabel: 'PDF & Belgeler',
    icon: 'Image',
    tags: ['#pdf', '#image', '#jpgtopdf', '#pngtopdf'],
    isPopular: true,
    path: '/tools/image-to-pdf/',
  },
  {
    id: 'pdf-rotate',
    slug: 'pdf-rotate',
    title: 'PDF Sayfa Döndürücü (PDF Rotate)',
    description: 'Ters veya yan taranmış PDF sayfalarınızı 90°, 180° veya 270° döndürün ve kaydedin.',
    category: 'pdf',
    categoryLabel: 'PDF & Belgeler',
    icon: 'RotateCw',
    tags: ['#pdf', '#rotate', '#döndür'],
    path: '/tools/pdf-rotate/',
  },

  // 2. Görsel & Fotoğraf & Medya (Öncelikli Günlük Araçlar)
  {
    id: 'image-compressor',
    slug: 'image-compressor',
    title: 'Görsel & Resim Boyutu Sıkıştırıcı (Compressor)',
    description: 'PNG, JPG ve WebP görsellerinizi kaliteden ödün vermeden %80\'e varan oranlarda tarayıcınızda küçültün.',
    category: 'image',
    categoryLabel: 'Görsel & Fotoğraf',
    icon: 'Image',
    tags: ['#compress', '#küçült', '#resim', '#webp'],
    isPopular: true,
    path: '/tools/image-compressor/',
  },
  {
    id: 'image-converter',
    slug: 'image-converter',
    title: 'Fotoğraf Format Dönüştürücü (PNG/JPG/WebP/SVG)',
    description: 'Fotoğraflarınızı PNG, JPG, WebP ve SVG formatları arasında anında ve sınırsızca dönüştürün.',
    category: 'image',
    categoryLabel: 'Görsel & Fotoğraf',
    icon: 'Maximize2',
    tags: ['#convert', '#pngtojpg', '#jpgtowebp', '#svg'],
    isPopular: true,
    path: '/tools/image-converter/',
  },
  {
    id: 'qr-code-generator',
    slug: 'qr-code-generator',
    title: 'Özelleştirilebilir QR Kod Üretici',
    description: 'Web siteleri, WiFi şifreleri, WhatsApp ve vCard için renkli, logolu ve SVG vektör formatında QR kod oluşturun.',
    category: 'image',
    categoryLabel: 'Görsel & Fotoğraf',
    icon: 'QrCode',
    tags: ['#qrcode', '#qrkod', '#svg', '#wifi'],
    isPopular: true,
    path: '/tools/qr-code-generator/',
  },
  {
    id: 'color-palette-extractor',
    slug: 'color-palette-extractor',
    title: 'Fotoğraftan Renk Paleti Çıkarıcı',
    description: 'Yüklediğiniz herhangi bir fotoğraftaki dominant renkleri, HEX ve RGB kodlarını anında tespit edin.',
    category: 'image',
    categoryLabel: 'Görsel & Fotoğraf',
    icon: 'Wand2',
    tags: ['#color', '#hex', '#palette', '#rgb'],
    path: '/tools/color-palette-extractor/',
  },
  {
    id: 'svg-optimizer',
    slug: 'svg-optimizer',
    title: 'SVG Dosya Optimize Edici & Minifier',
    description: 'Vektör SVG dosyalarınızdaki gereksiz etiketleri ve boşlukları temizleyerek dosya boyutunu küçültün.',
    category: 'image',
    categoryLabel: 'Görsel & Fotoğraf',
    icon: 'Sparkles',
    tags: ['#svg', '#vector', '#minify', '#assets'],
    path: '/tools/svg-optimizer/',
  },

  // 3. Metin & Yazı Araçları
  {
    id: 'word-counter',
    slug: 'word-counter',
    title: 'Kelime & Karakter Sayacı (Word Counter)',
    description: 'Kelime, harf, cümle, paragraf sayısı, okuma süresi ve anahtar kelime yoğunluğunu canlı analiz edin.',
    category: 'text',
    categoryLabel: 'Metin & Yazı',
    icon: 'FileText',
    tags: ['#kelimesayacı', '#karakter', '#words', '#readingtime'],
    isPopular: true,
    path: '/tools/word-counter/',
  },
  {
    id: 'case-converter',
    slug: 'case-converter',
    title: 'Büyük / Küçük Harf & Case Dönüştürücü',
    description: 'Metinleri BÜYÜK HARF, küçük harf, Başlık Hali, camelCase, snake_case ve kebab-case formatlarına çevirin.',
    category: 'text',
    categoryLabel: 'Metin & Yazı',
    icon: 'Type',
    tags: ['#case', '#uppercase', '#lowercase', '#camelcase'],
    isPopular: true,
    path: '/tools/case-converter/',
  },
  {
    id: 'text-diff',
    slug: 'text-diff',
    title: 'Metin & Kod Farkı Karşılaştırıcı (Diff)',
    description: 'İki metin veya kod bloğu arasındaki eklenen, silinen ve değişen satırları yan yana görsel olarak karşılaştırın.',
    category: 'text',
    categoryLabel: 'Metin & Yazı',
    icon: 'GitCompare',
    tags: ['#diff', '#karşılaştır', '#compare', '#git'],
    isPopular: true,
    path: '/tools/text-diff/',
  },
  {
    id: 'markdown-previewer',
    slug: 'markdown-previewer',
    title: 'Canlı Markdown Editörü & HTML Çıktısı',
    description: 'GitHub tarzı tablolar ve kod bloklarıyla canlı Markdown yazın, HTML veya formatlı belge olarak dışa aktarın.',
    category: 'text',
    categoryLabel: 'Metin & Yazı',
    icon: 'FileEdit',
    tags: ['#markdown', '#gfm', '#html', '#preview'],
    path: '/tools/markdown-previewer/',
  },
  {
    id: 'lorem-ipsum-generator',
    slug: 'lorem-ipsum-generator',
    title: 'Lorem Ipsum Sahte Metin Üretici',
    description: 'Tasarım ve mizanpaj çalışmalarınız için paragraf, cümle veya kelime bazlı Lorem Ipsum metinleri oluşturun.',
    category: 'text',
    categoryLabel: 'Metin & Yazı',
    icon: 'FileText',
    tags: ['#lorem', '#ipsum', '#placeholder', '#dummy'],
    path: '/tools/lorem-ipsum-generator/',
  },

  // 4. Geliştirici & API Araçları
  {
    id: 'curl-to-code',
    slug: 'curl-to-code',
    title: 'cURL to Code Converter (Fetch, Axios, Python, Go, Rust)',
    description: 'cURL komutlarını anında temiz JavaScript Fetch, Axios, Python Requests, Go net/http ve Rust reqwest koduna çevirin.',
    category: 'dev',
    categoryLabel: 'Geliştirici & API',
    icon: 'Terminal',
    tags: ['#curl', '#fetch', '#axios', '#python', '#golang', '#rust'],
    isPopular: true,
    isNew: true,
    path: '/tools/curl-to-code/',
  },
  {
    id: 'jwt-decoder',
    slug: 'jwt-decoder',
    title: 'JWT Token Çözücü & Süre Denetleyici',
    description: 'JSON Web Token (JWT) başlıklarını, yetki claim\'lerini ve son kullanma tarihlerini sıfır sunucu ile güvenle inceleyin.',
    category: 'dev',
    categoryLabel: 'Geliştirici & API',
    icon: 'Key',
    tags: ['#jwt', '#bearer', '#auth', '#token', '#decode'],
    isPopular: true,
    path: '/tools/jwt-decoder/',
  },
  {
    id: 'json-formatter-validator',
    slug: 'json-formatter-validator',
    title: 'JSON Biçimlendirici & Hata Denetleyici (Validator)',
    description: 'Bozuk veya sıkışmış JSON verilerinizi güzelleştirin, girintileyin ve sözdizimi hatalarını satır satır tespit edin.',
    category: 'dev',
    categoryLabel: 'Geliştirici & API',
    icon: 'CheckCircle2',
    tags: ['#json', '#beautify', '#validate', '#prettier'],
    isPopular: true,
    path: '/tools/json-formatter-validator/',
  },
  {
    id: 'base64-encoder-decoder',
    slug: 'base64-encoder-decoder',
    title: 'Base64 Kodlayıcı & Çözücü (Encoder / Decoder)',
    description: 'Metinleri ve ikili verileri standart ya da URL-Safe Base64 formatına güvenle dönüştürün.',
    category: 'dev',
    categoryLabel: 'Geliştirici & API',
    icon: 'Binary',
    tags: ['#base64', '#encode', '#decode', '#rfc4648'],
    isPopular: true,
    path: '/tools/base64-encoder-decoder/',
  },
  {
    id: 'hash-generator',
    slug: 'hash-generator',
    title: 'Web Crypto Hash Üretici (SHA-256 / SHA-512)',
    description: 'SHA-256, SHA-512, SHA-384 ve SHA-1 kriptografik özet değerlerini donanım hızlandırmalı Web Crypto ile üretin.',
    category: 'dev',
    categoryLabel: 'Geliştirici & API',
    icon: 'Fingerprint',
    tags: ['#sha256', '#sha512', '#crypto', '#hash'],
    path: '/tools/hash-generator/',
  },
  {
    id: 'uuid-generator',
    slug: 'uuid-generator',
    title: 'Toplu UUID v4 Benzersiz Kimlik Üretici',
    description: 'Tek seferde binlerce rastgele, standart UUID v4 kimliği oluşturun ve tek tıkla kopyalayın.',
    category: 'dev',
    categoryLabel: 'Geliştirici & API',
    icon: 'Fingerprint',
    tags: ['#uuid', '#guid', '#v4', '#random'],
    path: '/tools/uuid-generator/',
  },

  // 5. Kod & Tip Dönüştürücüler
  {
    id: 'json-to-typescript',
    slug: 'json-to-typescript',
    title: 'JSON to TypeScript Interface Dönüştürücü',
    description: 'JSON objelerini ve dizilerini güçlü tipli TypeScript Interface ve Type tanımlarına dönüştürün.',
    category: 'converters',
    categoryLabel: 'Kod Dönüştürücüler',
    icon: 'Code2',
    tags: ['#typescript', '#json', '#interfaces', '#types'],
    isPopular: true,
    path: '/json-to-typescript/',
  },
  {
    id: 'json-to-go',
    slug: 'json-to-go',
    title: 'JSON to Go Struct Dönüştürücü',
    description: 'JSON verilerinizden `json:""` etiketlerine sahip standart Go struct yapıları sentezleyin.',
    category: 'converters',
    categoryLabel: 'Kod Dönüştürücüler',
    icon: 'Code2',
    tags: ['#golang', '#struct', '#json'],
    isPopular: true,
    path: '/json-to-go/',
  },
  {
    id: 'json-to-rust',
    slug: 'json-to-rust',
    title: 'JSON to Rust Serde Struct',
    description: 'Rust #[derive(Serialize, Deserialize)] niteliklerine sahip güçlü tipli Rust modelleri oluşturun.',
    category: 'converters',
    categoryLabel: 'Kod Dönüştürücüler',
    icon: 'Layers',
    tags: ['#rust', '#serde', '#structs'],
    isPopular: true,
    path: '/json-to-rust/',
  },
  {
    id: 'yaml-to-json',
    slug: 'yaml-to-json',
    title: 'YAML to JSON Dönüştürücü',
    description: 'Kubernetes ve Docker Compose YAML yapılandırmalarını hızlıca JSON verisine çevirin.',
    category: 'converters',
    categoryLabel: 'Kod Dönüştürücüler',
    icon: 'FileCode',
    tags: ['#yaml', '#k8s', '#json', '#compose'],
    isPopular: true,
    path: '/yaml-to-json/',
  },
  {
    id: 'csv-to-json',
    slug: 'csv-to-json',
    title: 'CSV & Excel to JSON Dönüştürücü',
    description: 'Büyük CSV ve TSV tablolarını JSON dizi objelerine hatasız olarak ayrıştırın.',
    category: 'converters',
    categoryLabel: 'Kod Dönüştürücüler',
    icon: 'Table',
    tags: ['#csv', '#excel', '#json', '#tabular'],
    path: '/csv-to-json/',
  },
  {
    id: 'sql-formatter',
    slug: 'sql-formatter',
    title: 'SQL Sorgu Güzelleştirici & Biçimlendirici',
    description: 'PostgreSQL, MySQL ve SQLite sorgularınızı okunabilir ve standart girintili hale getirin.',
    category: 'converters',
    categoryLabel: 'Kod Dönüştürücüler',
    icon: 'Sparkles',
    tags: ['#sql', '#postgres', '#mysql', '#beautify'],
    isPopular: true,
    path: '/formatters/sql/',
  },

  // 6. Hesaplayıcılar & Birimler
  {
    id: 'percentage-calculator',
    slug: 'percentage-calculator',
    title: 'Çok Fonksiyonlu Yüzde Hesaplayıcı',
    description: 'Yüzde artış/azalış, indirim tutarı, KDV hesaplama ve oran farklarını anında hesaplayın.',
    category: 'calculators',
    categoryLabel: 'Hesaplayıcılar',
    icon: 'Percent',
    tags: ['#yüzde', '#hesaplama', '#indirim', '#oran'],
    isPopular: true,
    path: '/tools/percentage-calculator/',
  },
  {
    id: 'aspect-ratio-calculator',
    slug: 'aspect-ratio-calculator',
    title: 'En-Boy Oranı & Çözünürlük Hesaplayıcı (Aspect Ratio)',
    description: 'Fotoğraf ve video boyutlandırmalarında 16:9, 4:3, 21:9 oranlarını orantılı şekilde hesaplayın.',
    category: 'calculators',
    categoryLabel: 'Hesaplayıcılar',
    icon: 'Maximize2',
    tags: ['#aspectratio', '#16x9', '#çözünürlük', '#ekran'],
    path: '/tools/aspect-ratio-calculator/',
  },
  {
    id: 'unit-converter',
    slug: 'unit-converter',
    title: 'Evrensel Birim Dönüştürücü (Uzunluk, Ağırlık, Veri)',
    description: 'Bayt, KB, MB, GB, metre, inç, kg ve sıcaklık birimlerini birbirine anında çevirin.',
    category: 'calculators',
    categoryLabel: 'Hesaplayıcılar',
    icon: 'Calculator',
    tags: ['#birim', '#mb', '#gb', '#metre', '#inch'],
    path: '/tools/unit-converter/',
  },
];
